### ISSUE TITLE
Sligthly different values in get_top_coefficient.

### ISSUE THREAD

**Issue by odutfoy** [iit-cs579/main#102]
Hello,

Here is my output of get_top_coefficient : 

top positive coefs: [(u'worth', 0.612026958201496), (u'film', 0.54737364161575786), (u'have', 0.47928273189755111), (u'best', 0.46199108787610971), (u'great', 0.45368029926332248)]
top negative coefs: [(u'worst', -0.85392289056442039), (u'nothing', -0.73758348632027915), (u'waste', -0.66700704570523806), (u'boring', -0.56750539182022008), (u'bad', -0.56574411471065134)]

As you can see, the values are really similar but are not exactly the same. I was wondering if anyone and slightly different values as well and it was due to the calculations on float which may not be as precise depending on the machine.

Every other output before that is exactly the same.

Any input is welcome,
Thank you

**Comment by prateekagrawal06** [comment]
M also getting slightly different values

**Comment by aronwc** [comment]
If the coefs don't match after ~4-5 decimal points, you most likely don't need to worry about it.
