### ISSUE TITLE
slightly high values of accuracy in tokenizer_expt..fine or bug?

### ISSUE THREAD

**Issue by hinagarg** [iit-cs579/main#106]
Hi,

Expected values of accuracy in tokenizer_expt method is:

[0.73999999999999999, 0.74499999999999988, 0.74749999999999994]

But my output is:

[0.73999999999999999, 0.75500000000000012, 0.75749999999999995]

Is my output fine?

**Comment by aronwc** [comment]
No, that's more than a rounding error.

**Comment by hinagarg** [comment]
fixed.

**Comment by FatemaT** [comment]
I seem to be getting something similar to those values too, was the problem in the tokenization?

**Comment by hinagarg** [comment]
Yea, the problem was in tokenizer_punct .. try to use other examples given by professor as below:

not the fiancée of not Henri
tokenize: not, the, fianc, e, of, not, henri
tokenize_with_punct: not, the, fianc, é, e, of, not, henri
tokenize_with_not: not, not_the, not_fianc, é, e, of, not, not_henri


tokenize_with_punct(u'hi there\n how are you?')
[u'hi', u'there', u'how', u'are', u'you', u'?']
tokenize_with_punct(u'hi there \x85 how are you?')
[u'hi', u'there', u'how', u'are', u'you', u'?']
tokenize_with_punct(u'hi there \r how are you?')
[u'hi', u'there', u'how', u'are', u'you', u'?']

fix ur tokenizer_punct ..u will get correct values

**Comment by hinagarg** [comment]
Here's another example to help:

nonascii_string = u'énot the\x85fiancéée-\n\rof not Henrié '
print 'tokenize:', tokenize(nonascii_string)
print 'with punct:', tokenize_with_punct(nonascii_string)
print 'with not:', tokenize_with_not(nonascii_string)
# \n \r and \x85 are newlines
# é is non-ASCII (\xe9)


tokenize: [u'not', u'the', u'fianc', u'e', u'of', u'not', u'henri']
with punct: [u'\xe9', u'not', u'the', u'fianc', u'\xe9', u'\xe9', u'e', u'-', u'of', u'not', u'henri', u'\xe9']
with not: [u'\xe9', u'not', u'not_the', u'not_fianc', u'\xe9', u'\xe9', u'e', u'-', u'of', u'not', u'not_henri', u'not_\xe9']

**Comment by FatemaT** [comment]
yes i noticed in this test i actually print the \x85 and it doesn't remove it 
my code works with all cases except when there is \x85 been trying to fix it for awhile now

**Comment by FatemaT** [comment]
here is something i find as strange my code now show the same result as the provided one's but when i try one of the test cases that has \x85 it still prints \x85

**Comment by hinagarg** [comment]
use regex to remove \x85  in re.findall..just add \x85 in the list of items u don wanna keep..

**Comment by FatemaT** [comment]
Thanks!! I don't why didn't I do that! it was fixed
