### ISSUE TITLE
what does train_after_removing_features method do?

### ISSUE THREAD

**Issue by nishu2901** [iit-cs579/main#107]
does it delete the entire column with that feature name? or rename that column as 0? or the data in that column should be made 0?

**Comment by aronwc** [comment]
The last one.
E.g.,  if X is this:
```python
[[1,2,3],
 [4,5,6]]
```
vocabulary is ['a', 'b', 'c'], and features_to_rem=['b'], then you'll make a copy of X that looks like this:
```python
[[1,0,3],
 [4,0,6]]
```

then, refit your classifier on this new X and return the resulting classifier.

**Comment by nishu2901** [comment]
so we make a new object? or edit the existing X? And how to edit X?

**Comment by aronwc** [comment]
X is a csr_matrix. Here's its documentation:
http://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html
The `copy` method will make a copy. 
You'll have to read docs and/or experiment to figure out how to modify a column.

**Comment by nishu2901** [comment]
Thanks. I got it
