### ISSUE TITLE
regarding train_after_removing_features()

### ISSUE THREAD

**Issue by morlowsk** [iit-cs579/main#108]
I don't really understand how I am supposed to do this function. Why would I want to set the column to zero when I can just remove the column? Also, I don't understand what we're supposed to set to 0. If you get a column with the getcol() method, what do the tuples represent?

**Comment by aronwc** [comment]
Have you seen #107 ?

Setting values to zero (as opposed to removing the column) may be desirable because that way we don't need to change the vocabulary in CountVectorizer to account for the change in the meaning of each column.

**Comment by morlowsk** [comment]
I see. But I still don't see how the CSR data structure works from with respect to definition given in class. Here's an example in the docs where they build one:

```
>>> row = array([0,0,1,2,2,2])
>>> col = array([0,2,2,0,1,2])
>>> data = array([1,2,3,4,5,6])
>>> csr_matrix( (data,(row,col)), shape=(3,3) ).todense()
matrix([[1, 0, 2],
        [0, 0, 3],
        [4, 5, 6]])
```

I don't get how there can be duplicate values in row when row is supposed to give you the columns where each row begins

**Comment by aronwc** [comment]
That's just a convenient way to construct the matrix. The actual representation we discussed in class is in the attributes `indices`,  `indptr`, and `data` attributes:

```python
row = np.array([0, 0, 1, 2, 2, 2])
col = np.array([0, 2, 2, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6])
m = csr_matrix((data, (row, col)), shape=(3, 3))
m.toarray()
array([[1, 0, 2],
       [0, 0, 3],
       [4, 5, 6]])
```
```python
print(m.indices)
print(m.indptr)
print(m.data)
[0 2 2 0 1 2]
[0 2 3 6]
[1 2 3 4 5 6]
```

**Comment by morlowsk** [comment]
I think I get what's going on now. Thanks
