### ISSUE TITLE
Warning when computing train_after_removing_features

### ISSUE THREAD

**Issue by odutfoy** [iit-cs579/main#109]
My solution brings up the following warning : 
SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  
Is that supposed to happen or should I improve my solution?

**Comment by aronwc** [comment]
If you convert X to a lil_matrix prior to modifying, this warning should go away.
However, it's okay if you leave it as is.
