### ISSUE TITLE
TypeError: 1615 is not JSON serializable

### ISSUE THREAD

**Issue by jiranun** [iit-cs579/main#110]
I've finished my asg3, and all result are similar to the expected result. However, I got an error from the last block where output.txt is created. It seems like because most_predictive_term_in_doc(X_test[10], clf, 1) from 
![screen shot 2015-11-05 at 9 25 37 pm](https://cloud.githubusercontent.com/assets/13938351/10988639/ce9fc346-8403-11e5-8b06-a4239b2573b0.png)
return 1615 which is a number. 

This problem will be solved if I use 
![screen shot 2015-11-05 at 9 26 27 pm](https://cloud.githubusercontent.com/assets/13938351/10988652/eb898b5e-8403-11e5-9fec-c05537c2109b.png) instead. 

Is that OK?

The error is 
![screen shot 2015-11-05 at 9 19 09 pm](https://cloud.githubusercontent.com/assets/13938351/10988592/403db89c-8403-11e5-9f9a-6d05e0ac9c5a.png)
![screen shot 2015-11-05 at 9 19 23 pm](https://cloud.githubusercontent.com/assets/13938351/10988593/4330e812-8403-11e5-848d-5a1128d98468.png)

**Comment by odutfoy** [comment]
Weird, I don't have an issue with 'pred_term' however i do get the same error : "TypeError: 0 is not JSON serializable" for 'rem_feat'

**Comment by Aceman1982** [comment]
Even i get the same error but for vec_nonbinary ( line 11), commenting the specific line seems to make it work. Anyone else has the same issue ?

**Comment by hinagarg** [comment]
I am also facing the same error

**Comment by Aceman1982** [comment]
converting it to string (str(...)) and storing  works okay for this specific line. Anyways only the actual values are converted to string it should be fine I guess.

**Comment by aronwc** [comment]
@jiranun  Ick. No, the problems is that your `most_predictive_term_in_doc` function returns a `np.int32` object instead of an `int` object; unbelievably, `json` knows how to write the former, but not the latter. See [here](http://stackoverflow.com/questions/11561932/why-does-json-dumpslistnp-arange5-fail-while-json-dumpsnp-arange5-tolis).

`json` *does* know how to write ints. E.g., this works fine:
```python
json.dump({'a': 1}, open('output2.txt', 'wt'))
```

Rather than modifying the final cell, please just cast the returned value in `most_predictive_term_in_doc` to int. E.g., `int(x)`.

**Comment by jiranun** [comment]
Solved! Thank you!

**Comment by shreeshbhat** [comment]
I am getting [ **TypeError: 11 is not JSON serializable** ] error even after returning int(idx) for most_predictive_term_in_doc.
I have also changed the return type in **do_cross_validation()** method : 
from **numpy.float64** to **float**.
It didn't help though.
Anyone knows the solution for this?

**Comment by poojamankani** [comment]
Even I get the same error " TypeError: 11 is not JSON serializable" for vec_nonbinary (line 11)

Any suggestions on how to resolve this?

**Comment by jiranun** [comment]
@shreeshbhat weird , my do_cross_validation() returns numpy.float64, and it doesn't have any problem.

@poojamankani "vec_nonbinary" prints value from do_vectorize(), and do_vectorize() should not return 11. Are you sure that the error is for vec_nonbinary?

**Comment by poojamankani** [comment]
Yes. I guess, 11 is the first element in the list of vec_nonbinary.

**Comment by shreeshbhat** [comment]
I m mentioning numpy.float64 because i thought this JSON error is due to
numpy numbers and I changed numpy numbers to its python equivalent & still
facing the issue.

**Comment by czhao18** [comment]
@poojamankani @shreeshbhat 
I got the same error as yours
are you guys using Windows OS? 
os.sep would convert forward slash into back slash like below
"data\train\pos\10057_9.txt" 
but back slash might escape some of the characters.
Could this be the reason causing the problem?

**Comment by poojamankani** [comment]
I am on windows os. But do you think that could cause an issue? Because it
works fine for all the other function calls. It's just failing at this
point. Not sure on that though.

**Comment by shreeshbhat** [comment]
Aah yes. I m using windows! But we shouldn't change the last block of code,
right?

**Comment by czhao18** [comment]
once I turned 'vec_nonbinary' into comments, block work fine.
(do_vectorize) and (get_files) are the methods called, must be one of them

**Comment by czhao18** [comment]
@poojamankani  @shreeshbhat 
Problem solved, you need to specify the data type instead using default in do_vectorize method when you create the CountVectorizer object

**Comment by shreeshbhat** [comment]
Great catch! I didn't understand what exactly we need to set in that method
though. Do you mean dtype = int ( normal python type)?

**Comment by czhao18** [comment]
yes, that would do the trick

**Comment by shreeshbhat** [comment]
Thank you :)

**Comment by poojamankani** [comment]
Great that worked.!! Thanks @czhao18 :+1:

**Comment by carolgrrr** [comment]
@odutfoy did you ever figure out which function was returning 0 is not JSON serializable? I am getting the same error as you... have tried the other solutions proposed in this thread but they aren't working

**Comment by odutfoy** [comment]
@carolgrrr Unfortunatly I could not figure it out :/

**Comment by carolgrrr** [comment]
I was able to correct this in my code. For me, the source of the error was the get_true_labels method. I created a numpy array of 0s, initialized as type np.int32. When I changed the type to generic int, the JSON error stopped and my final output file generates as expected.
