### ISSUE TITLE
Get different result in tokenizer_expt method

### ISSUE THREAD

**Issue by czhao18** [iit-cs579/main#112]
[0.73999999999999999, 0.73999999999999999, 0.73750000000000004]
I got this result instead of the one professor gave. 
each tokenizer method works fine.

any thought?

**Comment by syembadi** [comment]
Then you might want to take a look at how you are implementing tokenize_with_punct(), did you get a chance to go through the issue #100 ?

**Comment by czhao18** [comment]
@syembadi  I used wrong method in do_vectorize to read files, problem solved! Appreciate!
