### ISSUE TITLE
tokenier_expt values

### ISSUE THREAD

**Issue by FatemaT** [iit-cs579/main#116]
in the tokenizer_ext i get these value and I can see they are almost similar to the given values and i don't know how to fix it 
my values [0.73999999999999999, 0.75, 0.74750000000000005]
the shown values 
[0.73999999999999999, 0.74499999999999988, 0.74749999999999994]

would it be alright with these values?

**Comment by hpandya2** [comment]
I'm getting all the values identical.... I don't know what is going wrong... 
[0.73999999999999999, 0.73999999999999999, 0.739999999999]

**Comment by FatemaT** [comment]
I had that problem before it was a problem with a parameter  check the parameter order in the methods you put inside and make sure you don't set the binary value inside a method but only one the parameter outside.
