### ISSUE TITLE
Output in Read testing data

### ISSUE THREAD

**Issue by maiky1806** [iit-cs579/main#117]
Hi! I am getting this output after executing the first piece of code of the "Read testing data":

*X_test represents 400 documents with 4734 features
y_test has 200 positive and 200 negative labels
first testing file is data/test/pos/10055_10.txt
last testing file is data/test/neg/9972_3.txt
testing accuracy=0.5*

The expected accuracy is 78% and the rest of the code above have been checked and works as expected (I get the exactly same output). What could be the problem?

**Comment by FatemaT** [comment]
I got that error once, though when I cleared and re-ran the program it was fixed, so I'm not sure what the problem was.
