### ISSUE TITLE
error in output file

### ISSUE THREAD

**Issue by mamtakanvinde** [iit-cs579/main#118]
while writing outputs in the output file i am getting the following error:
TypeError: 11 is not JSON serializable.
I am not understanding this error. Please guide

**Comment by FatemaT** [comment]
one of the issue discussed this problem just cast the return value in most_predective_term to int 

e.g int(x)

**Comment by bpraveen92** [comment]
see #110

**Comment by mamtakanvinde** [comment]
its done thanku
