### ISSUE TITLE
do_cross_validation

### ISSUE THREAD

**Issue by dmartiinez** [iit-cs579/main#119]
How do we get the block to print fold 0 accuraccy=...fold 4.. without it being part of the function?

When I run the block after do_expt, it is printing that too when calling do_expt because my do_expt calls do_cross_validation.

**Comment by czhao18** [comment]
the value in verbose would control this printing part, if true, print else not

**Comment by dmartiinez** [comment]
can you explain the verbose part.. I was confused about that and don't think I used that.

**Comment by czhao18** [comment]
do_cross_validation(X, y, n_folds=5, verbose=False) 
as part of arguments, in this case, method wouldn't print out the accuracy list

do_cross_validation(X, y, n_folds=5, verbose=True) 
you can use this argument as a flag to control if clause

**Comment by dmartiinez** [comment]
Thank You!
