### ISSUE TITLE
tokenize_with punctuation

### ISSUE THREAD

**Issue by dmartiinez** [iit-cs579/main#120]
Anyone know how to remove white space from the list.. I am using re.split to split on punctuation but I get white spaces in my list.

**Comment by goutkannan** [comment]
String has a function called strip() that could remove the whitespaces

**Comment by dmartiinez** [comment]
I tried this didn't work.

**Comment by ishanbilolikar** [comment]
try adding \s in your match list. worked for me

**Comment by dmartiinez** [comment]
wait, you are using re.match?

**Comment by ishanbilolikar** [comment]
nope...using re.findall..in that specify in the exclude list that you dont
want white space. \s defines white space in regex.
you can you '^' to exclude
check out the documentation

**Comment by dmartiinez** [comment]
But findall just takes a pattern, what do you mean exclude list. I read the documentation but I don't think I understand exactly what it does

**Comment by ishanbilolikar** [comment]
put something like this in your findall

[^\s] ..this excludes the white spaces

check this out
http://stackoverflow.com/questions/2758921/regular-expression-that-finds-and-replaces-non-ascii-characters-with-python

**Comment by dmartiinez** [comment]
ok. I did that but now its giving me every character as an element in the list, separating every word to a single character. I don't think I am doing this right.

**Comment by ishanbilolikar** [comment]
'[\w]+|' -> for word match.

**Comment by goutkannan** [comment]
You can do in two ways , either my not matching the whitespaces as
mentioned by Ishan ,  Using strip , get the tokens using your regular
expression and then  Return all "string" if they pass string.strip()
