### ISSUE TITLE
Getting testing accuracy 0.5 for 'Read Testing data'

### ISSUE THREAD

**Issue by lkshmi** [iit-cs579/main#122]
Hi,
I have got correct output for all blocks until  the one containing 'get_top_coefficients'. But, testing accuracy is 0.5 for 'Read testing data' instead of 0.78. Cant figure out what is wrong. Did anyone faced similar problem?

Regards,
Lakshmi Karle

**Comment by ishanbilolikar** [comment]
I am facing the same problem
Output to all methods above is correct and it differs here
Not able to figure out

**Comment by mamtakanvinde** [comment]
check issue #103

**Comment by lkshmi** [comment]
WoW! It worked.

Thanks a ton,
Lakshmi

**Comment by lkshmi** [comment]
Check the link which Mamta has provided.
When you are callind transform, instead of passing file names as
parameters, pass file contents. It will work.

Sorry, saw your mail just now.

Regards,
Lakshmi Karle
