### ISSUE TITLE
output file

### ISSUE THREAD

**Issue by dmartiinez** [iit-cs579/main#124]
when i run my last block to create the output.txt file, I only get the last graph. anyone know why this might be?

**Comment by bpraveen92** [comment]
see if you've included plt.show() in each of the graph modules.

**Comment by dmartiinez** [comment]
thanks, no its showing the first two graphs in one :/

**Comment by bpraveen92** [comment]
I faced the same issue and by including show() I was able to print separate graphs. I don't understand why the opposite happens in your case.

**Comment by dmartiinez** [comment]
i got it! Thank you!
