### ISSUE TITLE
Values of accuracies getting rounded of

### ISSUE THREAD

**Issue by shivakumar-15** [iit-cs579/main#126]
The output i am getting for 
def min_df_expt(filenames, y):

[0.74749999999999994,
 0.76000000000000001,
 0.75,
 0.74249999999999994,
 0.75,
 0.74249999999999994,
 0.74749999999999994,
 0.73750000000000004,
 0.72750000000000004,
 0.72999999999999998]

but the given output is

[0.74749999999999994,
 0.76000000000000001,
 0.75000000000000011,
 0.74249999999999994,
 0.74999999999999989,
 0.74249999999999994,
 0.74749999999999994,
 0.73750000000000004,
 0.72750000000000004,
 0.73000000000000009]

some of the values are differing by 0.00000000000001
and hence getting rounded of 
Is this okay ??
This is also happening for max_df

**Comment by spate141** [comment]
:+1: Yup, its oky
