### ISSUE TITLE
norm(csr_matrix([3,4]))

### ISSUE THREAD

**Issue by jaydeeppatel1701** [iit-cs579/main#127]
can someone elaborate what this function does?

**Comment by aronwc** [comment]
The `norm` function should do this:
https://en.wikipedia.org/wiki/Norm_(mathematics)#Euclidean_norm

E.g., the norm of the vector [3,4] = sqrt(3^2 + 4^2) = 5

**Comment by xsu11** [comment]
Prof,
Can we use the given scipy.spatial.distance.euclidean(u, v) method to calculate the Euclidean norm?

**Comment by aronwc** [comment]
No, but you can use .dot.
