### ISSUE TITLE
Different output for document_frequencies()

### ISSUE THREAD

**Issue by shreeshbhat** [iit-cs579/main#128]
The first column of the matrix has the values : 
![capture](https://cloud.githubusercontent.com/assets/13938682/11202698/7978d578-8cb0-11e5-94ba-e629250c6f71.JPG)

And the output of document_frequencies() is :
![c2](https://cloud.githubusercontent.com/assets/13938682/11202703/8df48056-8cb0-11e5-9412-0a826b9f15c2.JPG)

**Shouldn't the first value be 4?**
I am getting the output as :
![capture](https://cloud.githubusercontent.com/assets/13938682/11202721/cfb95e26-8cb0-11e5-9d09-8a8e49bad931.JPG)

Because of this, tfidf method's output is also affected.

**Comment by jaydeeppatel1701** [comment]
you are adding the column values. You have to calculate when there is non zero value present

**Comment by aronwc** [comment]
Right, the example looks correct. `document_frequencies` returns is the number of documents the term appears in, not the total number of times the term appears.

**Comment by shreeshbhat** [comment]
Thanks for the clarification!
