### ISSUE TITLE
Weighted average

### ISSUE THREAD

**Issue by lakshmyu** [iit-cs579/main#130]
Hi,
Could someone please help how to calculate weighted average of tfidf vectors of each movie rated? I couldn't figure out from the example provided.
Thank You

**Comment by jaydeeppatel1701** [comment]
divide each term of movie_term_matrix by their document_frequencies

**Comment by lakshmyu** [comment]
I referred to computing weighted average in make_user_profiles() for creating user profile matrix

**Comment by jaydeeppatel1701** [comment]
it is weighted average of each user's rating with its tfidf vectors divided by total user rating

**Comment by lakshmyu** [comment]
Does tfidf vector represent each row of tfidf_matrix?

**Comment by jaydeeppatel1701** [comment]
yes

**Comment by shreeshbhat** [comment]
As per my understanding, tfidf vector represents the the each movie's term.
For tfidf matrix below:
![image](https://cloud.githubusercontent.com/assets/13938682/11233301/a6902d0a-8d81-11e5-9fda-b84d66c278cb.png)

For first iteration : 
tfidf vector will be : 
[ 0,
  1,
  1,
  0]

For ratings : 
![image](https://cloud.githubusercontent.com/assets/13938682/11233319/dbaae958-8d81-11e5-9a24-410421b3de4a.png)

The first values will be : 
[.1, 0, .2, 0]

Sum of the row 1 ratings = .3
Weighted avg becomes 0.2/0.3 = 0.66666667

Correct?

**Comment by jaydeeppatel1701** [comment]
yes exactly

**Comment by lakshmyu** [comment]
Thanks a lot both of you!

**Comment by mamtakanvinde** [comment]
Weighted avg becomes 0.2/0.3 = 0.66666667
how did you calculate 0.2?

**Comment by jaydeeppatel1701** [comment]
multiply two vectors given by @shreeshbhat

**Comment by mamtakanvinde** [comment]
oh ok thanks!

**Comment by dmartiinez** [comment]
Hi guys! How did you create the car matrix?

**Comment by dmartiinez** [comment]
im confused as to how we are building it so that each user has 14 weighted averages.
