### ISSUE TITLE
Wrong decimal point in user_profile matrix

### ISSUE THREAD

**Issue by lkshmi** [iit-cs579/main#131]
Hi,

I am getting following values for user_profile matrix, when I run python notebook for the first time.
matrix([[  6.66666667e-001,   3.33333333e-001,   3.33333333e-001,
           1.66666667e-001,   3.33333333e-001,   2.22222222e-001,
           0.00000000e+000,   3.33333333e-001,   6.66666667e-001,
           3.33333333e-001,   2.50000000e-001,   3.33333333e-001,
           3.33333333e-001,   3.12854638e+180],
        [  7.50000000e-001,   3.75000000e-001,   1.25000000e-001,
           1.25000000e-001,   3.75000000e-001,   3.33333333e-001,
           7.50000000e-001,   0.00000000e+000,   0.00000000e+000,
           0.00000000e+000,   2.50000000e-001,   3.75000000e-001,
           0.00000000e+000,   2.46089262e-154],
        [  7.50000000e-001,   3.75000000e-001,   3.75000000e-001,
           1.25000000e-001,   3.75000000e-001,   2.50000000e-001,
           0.00000000e+000,   2.50000000e-001,   7.50000000e-001,
           2.50000000e-001,   2.50000000e-001,   3.75000000e-001,
           2.50000000e-001,   2.63527213e-086],
        [  0.00000000e+000,   0.00000000e+000,   5.00000000e-001,
           5.00000000e-001,   0.00000000e+000,   3.33333333e-001,
           0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
           0.00000000e+000,   2.50000000e-001,   0.00000000e+000,
           0.00000000e+000,   5.23490985e+180],
        [  4.28571429e-001,   2.14285714e-001,   5.00000000e-001,
           2.85714286e-001,   2.14285714e-001,   3.33333333e-001,
           0.00000000e+000,   0.00000000e+000,   4.28571429e-001,
           0.00000000e+000,   2.50000000e-001,   2.14285714e-001,
           0.00000000e+000,   1.02945045e+248]])

If I run it again, I will get proper values i.e.
matrix([[ 0.66666667,  0.33333333,  0.33333333,  0.16666667,  0.33333333,
          0.22222222,  0.        ,  0.33333333,  0.66666667,  0.33333333,
          0.25      ,  0.33333333,  0.33333333,  0.        ],
        [ 0.75      ,  0.375     ,  0.125     ,  0.125     ,  0.375     ,
          0.33333333,  0.75      ,  0.        ,  0.        ,  0.        ,
          0.25      ,  0.375     ,  0.        ,  0.        ],
        [ 0.75      ,  0.375     ,  0.375     ,  0.125     ,  0.375     ,
          0.25      ,  0.        ,  0.25      ,  0.75      ,  0.25      ,
          0.25      ,  0.375     ,  0.25      ,  0.        ],
        [ 0.        ,  0.        ,  0.5       ,  0.5       ,  0.        ,
          0.33333333,  0.        ,  0.        ,  0.        ,  0.        ,
          0.25      ,  0.        ,  0.        ,  0.        ],
        [ 0.42857143,  0.21428571,  0.5       ,  0.28571429,  0.21428571,
          0.33333333,  0.        ,  0.        ,  0.42857143,  0.        ,
          0.25      ,  0.21428571,  0.        ,  0.        ]])

Can't figure out what is the problem.

-Lakshmi

**Comment by lkshmi** [comment]
Hi,

Looks like, they are the same values but can't figure out why the representation differes when I run for the first time.

Regards,

**Comment by nishu2901** [comment]
Hi, How do you divide the matrix
i.e 
I have a matrix with sum of ratings
[ 0.3  1.2  1.2  0.4  0.7]

and for tfidf

[[ 0.2         0.1         0.1         0.05        0.1         0.06666667
   0.          0.1         0.2         0.1         0.075       0.1         0.1
   0.        ]
 [ 0.9         0.45        0.15        0.15        0.45        0.4         0.9
   0.          0.          0.          0.3         0.45        0.          0.9       ]
 [ 0.9         0.45        0.45        0.15        0.45        0.3         0.
   0.3         0.9         0.3         0.3         0.45        0.3         0.        ]
 [ 0.          0.          0.2         0.2         0.          0.13333333
   0.          0.          0.          0.          0.1         0.          0.
   0.        ]
 [ 0.3         0.15        0.35        0.2         0.15        0.23333333
   0.          0.          0.3         0.          0.175       0.15        0.
   0.        ]]

I know I have to divide each row of tfidf by respective elements of the rating matrix, but I don't know how to do that.

**Comment by lkshmi** [comment]
This is how I did it. Not sure if there is a better way.
- I first multipled tdif_col with i/sum
- Then performed vector multiplication of corresponsing ratings matrix row
and tf matrix col.

Regards,

**Comment by lkshmi** [comment]
i/sum --> 1/sum

**Comment by mamtakanvinde** [comment]
divide each element of matrix by corresponding dfs[col]
