### ISSUE TITLE
predict_ratings_w_user_profiles function

### ISSUE THREAD

**Issue by mamtakanvinde** [iit-cs579/main#133]
I am getting the output like this
[[ 0.1         0.48953468  0.2         0.35045309]
 [ 0.04514693  0.9         0.57142822  0.3       ]
 [ 0.3         0.51857187  0.9         0.33970573]
 [ 0.20920278  0.10678984  0.28972493  0.4       ]
 [ 0.          0.          0.3         0.4       ]]

instead of 
     matrix([[ 0.1       ,  0.48953468,  0.2       ,  0.35045309],
        [ 0.04514693,  0.9       ,  0.57142822,  0.3       ],
        [ 0.3       ,  0.51857187,  0.9       ,  0.33970573],
        [ 0.20920278,  0.10678984,  0.28972493,  0.4       ],
        [ 0.11225271,  0.46388588,  0.3       ,  0.4       ]])

**Comment by ishanbilolikar** [comment]
You should return a csr matrix

**Comment by mamtakanvinde** [comment]
yeah , my last row's values aren't coming as given. Thats what I wanted to show

**Comment by ishanbilolikar** [comment]
Check ur forloop limit
I am guessing its running only 4 times instead of 5

**Comment by mamtakanvinde** [comment]
there areonly 4 rows in tfidf and userprofiles matrices

**Comment by mamtakanvinde** [comment]
I know there is some silly mistake but I am not understanding what is it

**Comment by ishanbilolikar** [comment]
Those 4 rows are of movies
But ratings matrix has row of users and column of movies
There are 5 users and 4 movies

**Comment by mamtakanvinde** [comment]
oh so should I transpose the matrix?

**Comment by ishanbilolikar** [comment]
No no
Run the for loop on ratings
And when ever the value is 0 call the cosine function for that user and
corresponding movie

**Comment by mamtakanvinde** [comment]
oh ohk, I was looping over userprofiles and tfidf...I will try this

**Comment by mamtakanvinde** [comment]
its done thanks
