### ISSUE TITLE
tfidf csr_matrix

### ISSUE THREAD

**Issue by hpandya2** [iit-cs579/main#134]
I'm using .multiply() method of csr_matrix to multiply the inverse of document freq of terms with csr_matrix. Instead of getting a csr_matrix back, I am getting 'numpy.matrixlib.defmatrix.matrix' type of matrix back as a result. Does anyone know how to convert this matrix to csr_matrix??

**Comment by aronwc** [comment]
You can just pass the numpy matrix to the csr_matrix constructor:
```python
>>> import numpy as np
>>> from scipy.sparse import csr_matrix
>>> m = np.matrixlib.defmatrix.matrix([[1,2], [3,4]])
>>> m
matrix([[1, 2],
        [3, 4]])
>>> m2 = csr_matrix(m)
>>> m2.todense()
matrix([[1, 2],
        [3, 4]])
```

**Comment by hpandya2** [comment]
thank you! it works now
