### ISSUE TITLE
version mismatch error while opening lecture notes

### ISSUE THREAD

**Issue by lkshmi** [iit-cs579/main#137]
Hi,

I am getting the following error on ipython notebook while opening l16 and l20, and finally getting a blank notebook.
"This notebook has been converted from an older notebook format (v3) to the current notebook format (v4). The next time you save this notebook, the current notebook format will be used. Older versions of IPython may not be able to read the new format. To preserve the original version, close the notebook without saving it."
Is anyone else also facing same problem?

Regards,

**Comment by spate141** [comment]
there is nothing inside L16 & L20. they are empty, so no need to review!

**Comment by lkshmi** [comment]
ok.tx
