### ISSUE TITLE
scientific rigor?

### ISSUE THREAD

**Issue by aronwc** [iit-cs579/main#141]
> On Tue, Dec 1, 2015 at 11:05 AM, A Student wrote:
> Hello Professor,
> 
> I am not sure in what type of file we should write scientific rigor?(Means in docx?)

You don't need to write a separate file for that. That is simply a set of questions I will consider when evaluating your report.
-Aron

**Comment by pavithrachandrakasu** [comment]
Hello Aron,

So then there is no need to answer those questions with a separate heading as 'scientific rigor' in our report file right??

**Comment by aronwc** [comment]
No.
