### ISSUE TITLE
Cannot find candidates.txt under the fold a0

### ISSUE THREAD

**Issue by sure00** [iit-cs579/main#147]
1) I am trying to do implement the function of read_screen_names. 
But cannot find the file "candidates.txt". So i create one txt file which named candidates.txt and fulfill the 4 candidates name in it.  I am not sure that is a correct method or I need to access that file in twitter server?

2)I am trying to implement the function of "get_users". When i call this function with the screen_name and  return the error code -“ No user matches for specified terms”。Does that mean the those candidate do not exist in my twitter account?

**Comment by veereshr** [comment]
1) 

You need create a text file named 'candidates.txt' with the following names (one per line):
DrJillStein
GovGaryJohnson
HillaryClinton
realDonaldTrump

No need to access that file in twitter server.

**Comment by aronwc** [comment]
1) I've put the file 'candidates.txt' [there](https://github.com/iit-cs579/assignments/blob/master/a0/candidates.txt) just now.

2) Yes, perhaps the candidate's names is misformatted, or you're using the wrong API call. I'd try printing the string just before the request to ensure it is what you think it is.

**Comment by sure00** [comment]
Thanks for your help.

I meet another issue:
I am trying to use lookup command to fetch user data with screen_name with
below command but fail.

for user in screen_names:
    print("request %s " %user)
    request = robust_request(twitter, 'users/lookup', {'screen_name': user} )
    print (request.status_code)
    userList.append(request)


But after printing the request information, seems that is not correct.

May i invite your help to notice me how to use the lookup api to fetch data?

**Comment by ran-su** [comment]
You should build a string instead using  {'screen_name': user}.

eg.  request = robust_request(twitter, 'users/lookup', "screen_name=fakeDonaldTrump,HiliaryClinton" )
