### ISSUE TITLE
Questions about get_friends() method

### ISSUE THREAD

**Issue by pliu19** [iit-cs579/main#148]
Dear Professor, 

In the get_friends method, is it possible that the output of doctest is wrong?  

In the website of following page, I think the following people is ordered by the time line. However, the output of get_friends seems to be chosen randomly. 

[695023, 1697081, 8381682, 10204352, 11669522]
For example, 695023 is Bryan Routledge, but it's in the middle of the list..

If the output is correct, does it mean that the returning list of IDs is disordered, and we need to sort them?

Thanks for your time and best wishes,
Ping

**Comment by aronwc** [comment]
They should be sorted:

```
Returns:
    A list of ints, one per friend ID, sorted in ascending order
```

**Comment by pliu19** [comment]
Dear Professor, 

Thanks for replying. 
[695023, 1697081, 8381682, 10204352, 11669522] 

The list above is the output that you gave for doctest. What I meant is the first guy is not the top of list. The person of 695023 is Bryan Routledge, which is not the first guy that you follows. 

I'm sorry if I didn't explain clearly. 

Best wishes and many thanks, 
Ping Liu

**Comment by aronwc** [comment]
Hi Ping -

695023 is indeed not the first person I follow, but if you take the IDs of everyone I follow and sort them in ascending order, 695023 is the first ID.

-Aron

**Comment by pliu19** [comment]
Thanks so much. It was my misunderstanding of output which should be numerical order but not time-line order. 

Best wishes,
