### ISSUE TITLE
Trouble with pip install TwitterAPI

### ISSUE THREAD

**Issue by Smrutipatel14** [iit-cs579/main#150]
![image](https://cloud.githubusercontent.com/assets/14853001/18054641/4af5881c-6dca-11e6-89a8-915f4795534c.png)

**Comment by aronwc** [comment]
Not sure. Perhaps a firewall/proxy issue? See here:
<https://github.com/JulianEberius/SublimePythonIDE/issues/9#issuecomment-18452411>

If any Windows users have any suggestions, please feel free to chime in.

-Aron

**Comment by Smrutipatel14** [comment]
Modifying the Firewall Settings din't help!

**Comment by Smrutipatel14** [comment]
I tried on different system and it worked :+1: 

Thank you
