### ISSUE TITLE
Questions about the answer of User followed by Hillary and Donald

### ISSUE THREAD

**Issue by pliu19** [iit-cs579/main#153]
Dear Professor, 

I have a question about User followed by Hillary and Donald. 

Is it the same meaning with common friend that Hillary and Donald have? If it's, the answer in the log file indicates [REDACTED], which ID should be xxxx. However, I double checked that Hillary doesn't follow 'REDACTED', and Hillary and Donald have another common friend, but not 'REDACTED'.  

Thanks so much and best wishes, 
Ping

**Comment by aronwc** [comment]
HI Ping,

[REDACTED] is just a string I used to indicate that I removed the correct
answer, so you can find it yourself!

The user's name is indeed not 'REDACTED'

-Aron

**Comment by pliu19** [comment]
Thanks so much for replying and clarifying. 

Best wishes, 
Ping
