### ISSUE TITLE
print_num_friends use screen_name or name for sort?

### ISSUE THREAD

**Issue by davidghiurco** [iit-cs579/main#157]
As the title implies, I'm wondering if when we print the number of friends for each candidate, do we print it sorted according to screen_name or the actual name of the candidate?

function comment says: "Print the number of friends per candidate, sorted by candidate name.
    See Log.txt for an example."

However looking in Log.txt, it appears that the prints are sorted according to 'screen_name' not 'name'

**Comment by aronwc** [comment]
It should be 'screen_name'
