### ISSUE TITLE
Doctest fails when testing get_friends()

### ISSUE THREAD

**Issue by Neotrino** [iit-cs579/main#160]
When I tried to get professor's first five friends' IDs using get_friends(), it gave me different result from what the doctest supposed to have. I also found that the first two IDs in doctest not even in the professor's friend list anymore. Is it because some changes have happened in real life? Do we have to pass all the doctests before submitting the assignment?

**Comment by aronwc** [comment]
My friends have not changed; yes, you should pass all doctests, otherwise points will be deducted.

**Comment by davidghiurco** [comment]
professor's doctests are fine. Remember you need to return
"A list of ints, one per friend ID, sorted in ascending order." as per the comment above the function.
