### ISSUE TITLE
how to get 5000 friends ?

### ISSUE THREAD

**Issue by changediyasunny** [iit-cs579/main#163]
Hi Prof,
It always gives me error of object not subscriptable  even if I use "Cursor".
with simple API call, default friends count is 25 and max is 200.

Any suggestions ?

**Comment by changediyasunny** [comment]
After 3000 count, it gives me an error on max limit reached. How to test ?

**Comment by ClaytonTurner** [comment]
Can you be more specific with which function/issue you are having? Just want to make sure I'm actually helping with my explanations. If you have a question about your specific code, then send me an email.

**Comment by changediyasunny** [comment]
Emailed
