### ISSUE TITLE
followed_by_hillary_and_donald

### ISSUE THREAD

**Issue by sure00** [iit-cs579/main#164]
Hi professor
I have a little confuse about this function.
Per my understanding,  I need to find the followers of the four users by sending the command : robust_request(twitter, 'followers/ids', {'screen_name': user['screen_name']}, 5) to find out the followers
and then to check whether it include hillary and donald and then return the screen_name.

**Comment by ClaytonTurner** [comment]
You can alter the screen names you are sending to robust_request or you can just filter for the information you need afterwards. As long as you get the return result correct, then you should be fine.
