### ISSUE TITLE
who are rivals?

### ISSUE THREAD

**Issue by cicirao** [iit-cs579/main#165]
This is not a programming issue but it confuses me.
In the ShortAnswers.txt, the second question asks about "who are rivals?" But who are whose rivals? This overlap account's rivals? Or two candidates' rivals? Anyone can explain this a bit for me? Thanks!

**Comment by pliu19** [comment]
I think it implies the Hillary Clinton versus Donald Trump, these 2 guys are rivals.

**Comment by ClaytonTurner** [comment]
pliu19 is correct in saying that Clinton and Trump are the rivals.

The question, in part, reads: "why do you think this user is followed by both Hilary Clinton and Donald Trump, who are rivals?"

The "who" here are referring back to both Clinton and Trump.
