### ISSUE TITLE
Status Code

### ISSUE THREAD

**Issue by Poojitha-VD** [iit-cs579/main#167]
Hello Professor,
I have an issue with  "request.status_code" , as it returns 400(Bad Request) status code.

Kindly help

**Comment by ClaytonTurner** [comment]
You typically get a 400 if you are not authenticating correctly.

Do you also get a 400 when trying to run the l02 python code?

**Comment by Poojitha-VD** [comment]
Yes, 400 with l02 python code!

**Comment by ClaytonTurner** [comment]
Go into your settings where your twitter tokens were retrieved from and change your permissions as follows

![untitled](https://cloud.githubusercontent.com/assets/1231287/18228581/aef591be-721a-11e6-8ade-cefa65bdf9c9.png)

**Comment by kbalasu6** [comment]
Facing the same issue. Changed the permissions and regenerated the tokens. Still the same 400 status code.

**Comment by kbalasu6** [comment]
UPDATE:
The tokens from the config file "twitter.cfg" were not being read correctly by the config parser. Issue is solved for me.

**Comment by ClaytonTurner** [comment]
Did the permissions change fix the issue? Just asking to see if I can close the issue.

**Comment by Poojitha-VD** [comment]
Hi,
Yes the issue is fixed. Thank You!!
