### ISSUE TITLE
Can I import other module except the given ones?

### ISSUE THREAD

**Issue by liudan7** [iit-cs579/main#171]
In my get_user() and get_friends(), I use the return value of robust_request(), which is a TwitterResponse object. If I want to extract all the info from this object, I have to call its attribute '.text', which returns all the info by plain text. And I need to convert this text into a dict and return a list of them. So I import the module 'json'. It is convenient to do the cast by json.loads(). But is it allowed? If not, is there any other way to make it?

**Comment by n-getty** [comment]
The TwitterResponse is iterable. See the main() method for how to generate a list using the iterator. No outside modules are necessary for this task. Drawing readable graphs however...

**Comment by liudan7** [comment]
Thank you! I have worked it out

**Comment by liudan7** [comment]
Thank you! I have worked it out

**Comment by liudan7** [comment]
Thank you! I have worked it out

**Comment by liudan7** [comment]
Thank you! I have worked it out
