### ISSUE TITLE
Graph Specs

### ISSUE THREAD

**Issue by saiarjuntanguturi** [iit-cs579/main#172]
How alike do our graphs have to look? I have a graph that makes clear distinctions between candidates and friends, and pretty much allows you to estimate how many connections are in common between two candidates by looking at the density. Is that sufficient?

**Comment by ClaytonTurner** [comment]
As stated in class, the graphs don't have to look exactly alike but they need to convey the same information. Networkx is a little finicky with the way it makes the graphs sometimes.

**Comment by davidghiurco** [comment]
I plan on showing the professor my graph just to confirm that everything is all right. For some reason I can't figure out a way to make the edges be thin and so in the big cluster (Gary Johnson and Jill Stein), thick edges add on top of each other and it's not entirely clear which one is which. I can't figure out how to make the edge as thin as the example graph we were given, but everything else looks very similar, just different colors, etc

**Comment by Smrutipatel14** [comment]
David,
You can pass "width" parameter into your draw_networkx() function to solve your problem.
