### ISSUE TITLE
Log.txt and twitter.cfg

### ISSUE THREAD

**Issue by ranjeetkumar** [iit-cs579/main#173]
Hi TA/Prof,

1) Do we need to replace Log.txt with our own result?
2) Do we need to add twitter.cfg to private repo?

Thanks,
Ranjeet

**Comment by aronwc** [comment]
1) No, you don't have to replace Log.txt (though you can if you want).
2) No, your twitter credentials should be in a0.py. No need for the file twitter.cfg.

**Comment by ranjeetkumar** [comment]
Thanks prof, This comment "# This method is done for you. Make sure to put your credentials in the file twitter.cfg"  above get_twitter() method confused me. Now, I have removed cfg file and put the credential into the ao.py file

**Comment by aronwc** [comment]
You're right, that part of the documentation is incorrect. I've updated a0.py accordingly (see [commit](https://github.com/iit-cs579/assignments/commit/901c2a216d3b57d930944d2d8e1b407049f5cf30))
