### ISSUE TITLE
Latest output of a0

### ISSUE THREAD

**Issue by aronwc** [iit-cs579/main#174]
Hi all,

I've re-run the solution code with the latest data from Twitter. As predicted, the data have changed somewhat. You can see the [latest output](https://github.com/iit-cs579/assignments/blob/master/a0/Log_2016-09-07-09-15.txt) as well as a [diff](http://htmlpreview.github.io/?https://raw.githubusercontent.com/iit-cs579/assignments/master/a0/Log_Diff.html) with the prior output in the [assignment folder] (https://github.com/iit-cs579/assignments/tree/master/a0). These data were collected at 9:15am today.

**Comment by yepinxia** [comment]
Looks like Dr. Jill Stein has added some more following users after you ran the code :)

**Comment by aronwc** [comment]
My output as of 4:50pm:

```
Established Twitter connection.
Read screen names: ['DrJillStein', 'GovGaryJohnson', 'HillaryClinton', 'realDonaldTrump']
found 4 users with screen_names ['DrJillStein', 'GovGaryJohnson', 'HillaryClinton', 'realDonaldTrump']
Friends per candidate:
DrJillStein 4159
GovGaryJohnson 3123
HillaryClinton 748
realDonaldTrump 42
Most common friends:
[(15846407, 3), (19608297, 3), (41877508, 2), (12, 2), (65404941, 2)]
Friend Overlap:
[('DrJillStein', 'GovGaryJohnson', 349), ('GovGaryJohnson', 'realDonaldTrump', 12), ('DrJillStein', 'HillaryClinton', 10), ('GovGaryJohnson', 'HillaryClinton', 9), ('DrJillStein', 'realDonaldTrump', 8), ('HillaryClinton', 'realDonaldTrump', 1)]
User followed by Hillary and Donald: [REDACTED]
graph has 389 nodes and 772 edges
network drawn to network.png
```

**Comment by davidghiurco** [comment]
I know the assignment is over, but I'd just like to point out that the Donald has deleted the common user with Hilary from his friends list :(

**Comment by aronwc** [comment]
The beauty of live data. I bet there's a political intern somewhere watching our repository.

No worries -- I ran all your code at 12:01am when the assignment was due..

**Comment by cicirao** [comment]
Thank god! The assignment has been run!
