### ISSUE TITLE
Short Answers - question 4

### ISSUE THREAD

**Issue by hsingh1991** [iit-cs579/main#176]
Do we have to find list of users for all 4 uses or for only Donald Trump?

**Comment by ClaytonTurner** [comment]
I believe donald trump was only used in the wording there as an example. Do this for all the candidates.

**Comment by davidghiurco** [comment]
The intent of the question is to find the TOTAL requests for all the users. The professor just gave the Donald as an example

**Comment by Smrutipatel14** [comment]
Is there any measuring formula any1 is aware of? To help find out answer to this question.

**Comment by saiarjuntanguturi** [comment]
There's no specific formula, but it should just involve some arithmetic. 
[](https://dev.twitter.com/rest/reference/get/friends/ids)
[](https://dev.twitter.com/rest/public/rate-limiting)
Definitely look at the links mentioned in the question to understand how exactly Twitter gives us the information we want (i.e. how many requests we need to make), and how it limits the number of requests you make in a 15 minute window.

**Comment by AndrewLu1992** [comment]
I have asked Professor and this is the reply:

"""
The question refers to the friends of all candidates. In other words, given the entire graph you have collected so far in this assignment, how long would it take to collect one more "hop" to get the "friends of friends" of each candidate.
"""

I believe it is the total requests for all friends of initial feeds.

**Comment by davidghiurco** [comment]
You should read what the question is asking, and read the rules of the rate
limiting on twitter. You don't need any formula...it's just simple math.

Find total number of friends.
Make request to each friend. You can only make 15 requests every 15 minite
period. and get 5000 friends max per request. So how many requests do you
have to make and how many 15 minute periods do they translate to?
