### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by Shravni** [iit-cs579/main#179]
Hey, How do I get the output of the functions that do not have doctests? I've tried the "python -m doctest -v a0.py" This only tells me if all that all the tests have passed. But nothing from the other functions. Where am I going wrong here?

**Comment by Smrutipatel14** [comment]
Shravni,
             Adding "-v" into your command also gives you list of functions that do not have doctests

**Comment by Shravni** [comment]
figured it out. thanks.
