### ISSUE TITLE
Git need help

### ISSUE THREAD

**Issue by sandeep-17IIT** [iit-cs579/main#180]
Your branch and 'origin/master' have diverged,
and have 4 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
You have unmerged paths.
  (fix conflicts and run "git commit")

Unmerged paths:
  (use "git add <file>..." to mark resolution)

        both modified:   a0.py

no changes added to commit (use "git add" and/or "git commit -a")

pls help me out

**Comment by aronwc** [comment]
1. Copy a0.py to a backup: a0.py.bak
2. git pull
3. edit a0.py, fixing any conflicting lines (you'll see >>> indicating these)
4. git add a0.py
5. git commit -m 'fix' a0.py
6.git push
