### ISSUE TITLE
Creating folder for a1 in our private repo

### ISSUE THREAD

**Issue by vmanikes** [iit-cs579/main#183]
Hello Professor,
Will you be creating a folder a1 in our private repo or we have to do it?

**Comment by aronwc** [comment]
You should be able to do it using the commands in `update.sh`. E.g., for linux/mac:

```sh
cd [my_repo_folder]
./update.sh
```

For windows, you might just have to manually execute the commands:
```sh
cd [my_repo_folder]
git fetch template
git merge template/master
```
