### ISSUE TITLE
[hw1]can we call _single_source_shortest_path_basic(graph, s) to realize the function bfs?

### ISSUE THREAD

**Issue by sure00** [iit-cs579/main#184]
Hi professor
can we call the function _single_source_shortest_path_basic(graph, s) to find the shortest path for hw1?
Or we must realize the function which similar like  _single_source_shortest_path_basic ?

**Comment by davidghiurco** [comment]
as long as you do not use any other imported libraries other than what was imported when you first pulled the assignment, you can use any function that is available to you. (Read the assignment description)
