### ISSUE TITLE
very weird error with nosetests

### ISSUE THREAD

**Issue by kyao4** [iit-cs579/main#186]
I just ran nosetests on my first function bfs, all the other lines of tests are passed but the last one, but I have exactly the same output with the doctest.

Failed example:
    sorted((node, sorted(parents)) for node, parents in node2parents.items())
Expected:
    [('B', ['D']), ('D', ['E']), ('F', ['E']), ('G', ['D', 'F'])]  
Got:
    [('B', ['D']), ('D', ['E']), ('F', ['E']), ('G', ['D', 'F'])]

so why does it happen???

**Comment by aronwc** [comment]
Is there trailing whitespace in one of the lines? There shouldn't be...

**Comment by kyao4** [comment]
Oh, Thanks, I just solved my problem.

**Comment by RittickDatta** [comment]
Hi kai,

I am in a similar situation as you described above. My output matches with log.txt but the doc tests are failing. When you said "trailing whitespace", does it mean that we can't have empty lines between code?

**Comment by kyao4** [comment]
It means no whitespace after a line not between the lines.

**Comment by ClaytonTurner** [comment]
Check out the strip functions for help with this: https://docs.python.org/2/library/string.html
