### ISSUE TITLE
Using submodules of networkx

### ISSUE THREAD

**Issue by davidghiurco** [iit-cs579/main#187]
The assignment says we should not use ANY other imports other than the ones already listed originally. 

However this does not include submodules included in the imported modules correct?

For example, I want to use some features found in networkx.algorithms.centrality.betweenness I technically need to import that module because I only have the top level module.

I am allowed to use any submodules included in the top level import, even if this technically results in some subsequence imports. Is this correct? Or do we have to write all our algorithms from scratch?

**Comment by aronwc** [comment]
Please write your algorithms from scratch; no need to import from networks.algorithms.
