### ISSUE TITLE
Mid Term exam date

### ISSUE THREAD

**Issue by vchariharan** [iit-cs579/main#188]
Dear Professor, 

Can you please share the rough tentative mid term exam date ?

**Comment by ClaytonTurner** [comment]
Test 1 is October 12th as per: https://github.com/iit-cs579/main/blob/master/Schedule.md

**Comment by RittickDatta** [comment]
Hi Clayton, 

What will be the format of the exam: objective or subjective ?

**Comment by aronwc** [comment]
I'll give more details on the midterm in class. In brief:
- new algorithms: give pseudo code to solve a problem (perhaps a modified version of something we did in class)
- algorithm output: here's an algorithm we discussed in class, show me its output for this input
- algorithm inspection: Here are two methods A and B. What are the advantages/disadvantages of each.
- True / False

**Comment by thirumalrao** [comment]
Hi Prof, Could you please provide more details on the syllabus and what we can expect (any sample/practice questions ?).

**Comment by theTechie** [comment]
Hello Prof @aronwc - are we allowed to carry notes ?

**Comment by davidghiurco** [comment]
Exam is closed book, closed notes, closed neighbor, closed everything. 

Short answer: no. He said so in class.
