### ISSUE TITLE
[hw1][Function] partition_girvan_newman(graph, max_depth):

### ISSUE THREAD

**Issue by sure00** [iit-cs579/main#189]
Hi Professor:
I had a little confused about below requirement, could you help to explain more detail information?

  If there are ties in edge betweenness, break by edge name (e.g.,
    (('A', 'B'), 1.0) comes before (('B', 'C'), 1.0)).

**Comment by sure00** [comment]
Meanwhile, can we used the implement of nx.connected_component_subgraphs(newGraph) to get the component of graph?

**Comment by ClaytonTurner** [comment]
I'm pretty sure "break by edge name" means break it up in alphabetical order if there's a tie in the betweenness scores

**Comment by sure00** [comment]
Thanks Clayton.
Can we use nx.connected_component_subgraphs(newGraph) to get the component of graph in our code?

**Comment by ClaytonTurner** [comment]
I'm not 100% sure as this is technically not a submodule but I'm not sure what Dr Culotta's preference on this specific function is as per this issue: https://github.com/iit-cs579/main/issues/187

**Comment by ClaytonTurner** [comment]
Yes this is allowed
