### ISSUE TITLE
complexity_of_bfs(V, E, K)

### ISSUE THREAD

**Issue by davidghiurco** [iit-cs579/main#191]
As we all know,
time complexity of normal BFS (without any depth limitation) is O(V+E)
O(E) can vary from O(V) to O(V^2) (the latter which means that every vertex is connected to every other vertex)

The method asks us to return the WORST-CASE run-time of the algorithm which would be, (again I'm not taking into account depth-limiting here) more like O(V + V^2)

But the test case for it tests complexity_of_bfs where V = 13 and E = 23

E is nowehere near O(V^2) it's way closer to O(V)

And so my question is in order to return the correct worst-case run time of the algorithm,
do we have to manually check if E is O(V^2) or O(V) or can we just assume it will always be O(V^2) since that WOULD be the worst-case scenario.

And if we do have to check if O(E) is O(V^2) vs O(V), how do we set that arbitrary cutoff point where we decide that it's closer to the latter than the former, or vice versa?

**Comment by aronwc** [comment]
No, you don't need to compare E to V to answer this question.
