### ISSUE TITLE
A little bit confusing about path_score function

### ISSUE THREAD

**Issue by kyao4** [iit-cs579/main#192]
1. In the eqution s(x,y) = \beta^i n_{x,y,i} there is no parameter called m, so what does it mean to say "m........the m parameter in the equation above."?
2. if K is the number of links to recommend, then in the doctest when K = 4 , why there are 3 edges in the output?

```Python
# k........the number of links to recommend.

>>> path_score(train_graph, 'D', k=4, beta=.5, m=3)
[(('D', 'F'), 0.5), (('D', 'A'), 0.25), (('D', 'C'), 0.25)]
```

**Comment by aronwc** [comment]
@kyao4 That was a typo. You're right -- there should be no `m` parameter.
I've removed this in the latest [commit](https://github.com/iit-cs579/assignments/commit/7f631c5264f4ce14c6d60d69b31c97073f0b1542)

**Comment by kyao4** [comment]
eh... maybe m is the max_depth for the BFS search?

**Comment by aronwc** [comment]
It was, but I've removed that. You should pull the latest code and use that.
