### ISSUE TITLE
[score_max_depths] corner case: set T would be null.

### ISSUE THREAD

**Issue by sure00** [iit-cs579/main#197]
Hi Professor
    I meet one corner case.
![image](https://cloud.githubusercontent.com/assets/6347772/18899834/7ba03856-8501-11e6-9b8f-3168a8e7a272.png)
  When the max_dept is 1, the betweenness for each edge would be 1. If removing edge ('A', 'B'), and the graph cannot split into two sets, instead only one set which content all nodes ,  note those nodes as cut set S and cut set T is NULL. Then we calculate norm_cut, as cut set T is Null , so cut(S,T,graph)/volume(T,graph) will return error as volume(T) is 0.

Below is my solution:
1)	Must split graph into two components. If cannot split it into two parts, delete other edge. But it cannot work for a square.
2)	When T is null, return error.

I am confused about which one is better?

below is the log:

dep is  1
root is  G
{('F', 'G'): 1.0, ('D', 'G'): 1.0}
root is  C
{('B', 'C'): 1.0, ('A', 'C'): 1.0}
root is  D
{('B', 'D'): 1.0, ('D', 'E'): 1.0, ('D', 'G'): 1.0, ('D', 'F'): 1.0}
root is  E
{('E', 'F'): 1.0, ('D', 'E'): 1.0}
root is  B
{('B', 'D'): 1.0, ('B', 'C'): 1.0, ('A', 'B'): 1.0}
root is  F
{('E', 'F'): 1.0, ('F', 'G'): 1.0, ('D', 'F'): 1.0}
root is  A
{('A', 'B'): 1.0, ('A', 'C'): 1.0}
Counter({('A', 'B'): 2.0, ('E', 'F'): 2.0, ('D', 'E'): 2.0, ('F', 'G'): 2.0, ('D', 'G'): 2.0, ('D', 'F'): 2.0, ('B', 'D'): 2.0, ('B', 'C'): 2.0, ('A', 'C'): 2.0})
approximate_betweenness result is [(('A', 'B'), 1.0), (('E', 'F'), 1.0), (('D', 'E'), 1.0), (('F', 'G'), 1.0), (('D', 'G'), 1.0), (('D', 'F'), 1.0), (('B', 'D'), 1.0), (('B', 'C'), 1.0), (('A', 'C'), 1.0)]

remove  ('A', 'B')

**Comment by ClaytonTurner** [comment]
Interesting question!

I'm not sure what Dr Culotta would prefer as your coding solution, but max_depth is used to reduce complexity for BFS, so I'm thinking that a max_depth of 1 is an odd case that should not be worried about, but I'll leave it open for clarification.

**Comment by aronwc** [comment]
@sure00 The `partition_girvan_newman` function should iteratively remove edges until the graph is split into more than one component. So, we can assume that this function will always return at least two non-empty  components.

Furthermore, you can assume that the original graph is one connected component. So, each component returned by `partition_girvan_newman` will have volume > 0 (as each node in the original graph has at least one edge).
