### ISSUE TITLE
bottom_up root parameter?

### ISSUE THREAD

**Issue by davidghiurco** [iit-cs579/main#198]
Is it really necessary? bottom_up function receives node2distances, node2num_paths, and node2parents from outside calling bfs on root node. But bfs doesn't get called internally in bottom_up (or shouldn't, as far as I understand). And besides node2distances can easily give the root.

My implementation does not use the root parameter at all (and my IDE is mad at me for passing in unused parameters), and I pass the doctests, and so I'm wondering if it is actually intended to be used, or am I doing something wrong and maybe happened to pass the doctest by coincidence for this particular data set?

**Comment by ClaytonTurner** [comment]
It's possible to do this without using the root node (keep the signature the same, however, as that is needed for grading) - you'll want to verify this is working for the approximate_betweenness function

You could try creating different graphs or writing extra doctests to verify everything's working.

**Comment by davidghiurco** [comment]
I'm just curious in what scenario would the root be used? I didn't even notice it was a parameter and at no point when I was writing my code did I think I'd need it. I just noticed it after I saw my IDE warn me that I have unused parameters

**Comment by davidghiurco** [comment]
I wrote extra tests and I'm done with the whole assignment and everything prints out what is supposed to in Log.txt so I guess it's correct but still curious where root would have been used.
