### ISSUE TITLE
[HW1]  path_score(graph, root, k, beta):

### ISSUE THREAD

**Issue by sure00** [iit-cs579/main#199]
Hi Professor
     In order to calculate $i$ which is the length of the shortest path from $x$ to $y$ in the function of path_score,
     can we use nx.shortest_path_length(graph, root, n) to calculate the length of shortest path in the function of path_score ?

**Comment by aronwc** [comment]
No. See #187, #190, #193.
-Aron

**Comment by davidghiurco** [comment]
Does this mean we essentially have to call previously-implemented bfs() function to get that lenth?

**Comment by sure00** [comment]
if we use previously-implemented bfs(), we need the parameter max_depth().

**Comment by cicirao** [comment]
I think the max_depth can be len(graph.somemethod()).

**Comment by davidghiurco** [comment]
you could get the highest degree and pass it in as max_depth as workaround using max(graph.degree(graph.nodes()).items() but that would be a lot of unecessary work done just to get the max degree

**Comment by sure00** [comment]
can we use  len(graph.somemethod())? maybe can set the max_depth to infinity and modify the bfs function to break if all node had been visited.

**Comment by cicirao** [comment]
Then you'll have to modify the bfs rather than just use it.

**Comment by davidghiurco** [comment]
python does have a math.inf attribute that is basically bigger than anything it's compared to unless compared to another math.inf holding variable.

I guess could try that for max_depth?

**Comment by cicirao** [comment]
math.inf + unmodified bfs will give you an infinite loop I guess.

**Comment by davidghiurco** [comment]
the way I have bfs implemented, no loop depends on max_depth,
I just use max_depth in if statements. i.e. if depth is higher than max_depth I just don't do anything and move on.

**Comment by davidghiurco** [comment]
I can confirm max_depth = math.inf works (at least for the way I implemented bfs)
