### ISSUE TITLE
Jaccard accuracy and path accuracy are returning 0

### ISSUE THREAD

**Issue by vmanikes** [iit-cs579/main#200]
I am calculating the jaccard Accuracy and path accuracy and both have returning 0. Here is my log

**/home/krishna/anaconda3/bin/python /home/krishna/vmanikes/a1/a1.py
graph has 5062 nodes and 6060 edges
subgraph has 712 nodes and 1710 edges
norm_cut scores by max_depth:
[(1, 1.0070175438596491), (2, 1.0005847953216374), (3, 0.12177725118483412), (4, 0.12177725118483412)]
first partition: cluster 1 has 701 nodes and cluster 2 has 11 nodes
cluster 2 nodes:
['Arthur A. Levine Books', 'The Hunger Games', 'Scholastic', 'Scholastic Teachers', 'Scholastic Reading Club', 'WordGirl', 'Scholastic Parents', 'Scholastic Book Fairs', 'Clifford The Big Red Dog', 'READ 180', 'Scholastic Canada']
train_graph has 712 nodes and 1705 edges

top jaccard scores for Bill Gates:
[(('Bill Gates', 'Global Citizen'), 0.16216216216216217), (('Bill Gates', 'Bill & Melinda Gates Foundation'), 0.10344827586206896), (('Bill Gates', 'Grand Challenges Canada'), 0.09375), (('Bill Gates', 'I fucking love science'), 0.09375), (('Bill Gates', 'Girl Effect'), 0.09090909090909091)]
jaccard accuracy=0

top path scores for Bill Gates for beta=.1:
[(('Bill Gates', 'Bill & Melinda Gates Foundation'), 0.06000000000000001), (('Bill Gates', 'Global Citizen'), 0.06000000000000001), (('Bill Gates', 'Gavi, the Vaccine Alliance'), 0.04000000000000001), (('Bill Gates', 'FutureWeWant'), 0.030000000000000006), (('Bill Gates', 'Girl Effect'), 0.030000000000000006)]
path accuracy for beta .1=0

Process finished with exit code 0**

Everything matches with the given log.txt except these 2. And the scores are returning for the doctest correctly. 

Any ideas ????

**Comment by davidghiurco** [comment]
My guess is you hard-coded something that happens to work for one iteration on the example_graph but on the big graph probably requires multiple iterations.

I literally can't suggest anything else without actually seeing what your jaccard and path_score code is, though.

**Comment by davidghiurco** [comment]
I just noticed that your output for path_score and jaccard are actually 100% correct.
The accuracy comes from the evaluate() method. I bet anything that's where you made a mistake and are not calculating the accuracy of the algorithms.

**Comment by davidghiurco** [comment]
And I think I may even know what the mistake is.
In your accuracy calculation, you are dividing 2 integers by one another. If at least one of the numbers in the division is not a float, then that division will truncate. Since scores are decimal numbers between 0 and 1, integer division will always truncate the result to 0.

To fix, simply do accuracy = float(number1) / number2

**Comment by vmanikes** [comment]
Thanks for the reply @davidghiurco but I was doing that already, the problem might be something else, trying to figure it out
