### ISSUE TITLE
doctest for bfs is failing

### ISSUE THREAD

**Issue by RittickDatta** [iit-cs579/main#204]
Hi,

when i am running nosetests, i get error that bfs() missing 3 required positional arguments: 'graph', 'root'  and 'max_depth' but isn't the doctest passing these three values as example_graph(), 'E' and 5.

i ran this for nosetest  on bfs:
nosetests a1.py:bfs

Where could I be going wrong?

**Comment by kyao4** [comment]
Read the example in the instructions, It should be like 

```
nosetests --with-doctest a0.py:get_twitter
```
