### ISSUE TITLE
log is different from professor`s

### ISSUE THREAD

**Issue by sure00** [iit-cs579/main#205]
![image](https://cloud.githubusercontent.com/assets/6347772/19000255/2e43b468-8707-11e6-9e47-2fa10438e242.png)

Hi all
The result of cluster 2 nodes is different from that in professor`s log. The content of that is same but the sequence is different.
Do you have similar problem?

**Comment by cicirao** [comment]
In the class, the professor said this could happen and it's OK to have a different order as long as nodes are the same.

**Comment by sure00** [comment]
Thanks cicirao
