### ISSUE TITLE
approximate_betweenness output changes on every run

### ISSUE THREAD

**Issue by vinits91** [iit-cs579/main#206]
my test cases for bfs and bottom up passed successfully, but when I am summing the output returned by bottom-up for each max depth and created a Default Dictionary of an edge with value, the dictionary is changing on each run, giving different value of approximate_betweenness on each run.

Output of 1st execution:
 [(('A', 'B'), 1.0), (('A', 'C'), 0.75), (('B', 'C'), 1.0), (('B', 'D'), 2.4921875), (('D', 'E'), 1.25), (('D', 'F'), 1.125), (('D', 'G'), 1.0), (('E', 'F'), 1.0625), (('F', 'G'), 0.6875)]

 Output of 2nd execution:
[(('A', 'B'), 1.125), (('A', 'C'), 0.75), (('B', 'C'), 1.125), (('B', 'D'), 2.03125), (('D', 'E'), 1.0), (('D', 'F'), 0.875), (('D', 'G'), 1.25), (('E', 'F'), 0.8125), (('F', 'G'), 0.9375)]

Please help.

**Comment by vmanikes** [comment]
Did u see if the outputs are coming correctly from bottom-up and bfs. I saw that u r doctests are passing. but the values you got are misleading.
