### ISSUE TITLE
The running time of partition_girvan_newman is too long

### ISSUE THREAD

**Issue by qsong4** [iit-cs579/main#208]
The running time of partition_girvan_newman is more than 10 minutes, but the result is right. Does anyone have some advice?

**Comment by Swapnil2095** [comment]
It is taking  the time to calculate betweenness in when it is calling from partition_girvan_newman function -
And it is executing slow like -

subgraph has 712 nodes and 1710 edges
3----------->In partition_girvan_newman
3-----------> In approximate_betweenness
3-----------> Out approximate_betweenness
Highest betweenness Value Edge- ('Big History Project', 'Bill Gates')
3-----------> In approximate_betweenness
3-----------> Out approximate_betweenness
Highest betweenness Value Edge- ('Bill Gates', 'Microsoft')
3-----------> In approximate_betweenness

**Comment by davidghiurco** [comment]
I mean it's very possible that you're running it on a slow computer but,
still it should not take anywhere near that amount of time. My solution
runs in about 10 seconds.

Are you sure you're pruning the edges of the graph correctly? If yes, that
probably means your internal implementation of bfs is inefficient.

**Comment by qsong4** [comment]
Thank you david!
