### ISSUE TITLE
Peformance of the algorithms

### ISSUE THREAD

**Issue by Kirubakumaresh** [iit-cs579/main#212]
Will the performance of the algorithms be evaluated?

It takes approximately 5-6 minutes to compute partition with max depth as 3.

I am not sure if I should focus on optimizing the function modules.

**Comment by davidghiurco** [comment]
yes it will be. The professor's solution runs in 10-15 seconds

**Comment by aronwc** [comment]
Yes - there is not a hard cutoff of time, but it should be on the order of tens of seconds, not minutes.

Remember that your `bfs` implementation should be no worse than the complexity of traditional BFS, and that the `bottom_up` function should only visit each node once.

**Comment by Kirubakumaresh** [comment]
Thanks. I was computing the approximate_betweenness every time I remove an edge. This is the cause for the performance issue. Also the results were not matching with the logs. Now I compute it only once and everything works as expected.
