### ISSUE TITLE
[HW1] node2num_paths in the function bfs

### ISSUE THREAD

**Issue by pavanraocr** [iit-cs579/main#214]
Can someone give me more details about node2num_paths. According to the explanation it says for each node in the graph we should give the number of shortest paths passing through it so if this understanding of the variable is correct then the example output should have different values.
for Ex. 
```
node2distances, node2num_paths, node2parents = bfs(example_graph(), 'E', 2)
for node D - there are 2 shortest paths passing through it and they are 

> [path 1] E-D-B
> [path 2] E-D-G
```

So the number corresponding to this node should be 2 but it is being tested for 1.

Somewhere my understanding of the problem is wrong or the test case is incorrect.
Kindly someone help me realize what am I missing here.

Thank you.

**Comment by joezhang2** [comment]
I think the professor meant to say: node2num_paths is the number of shortest paths from the root node to the rest of the nodes. So for node D, there is only one shortest path from E to D (E-D). The only node in the example graph that has a different value is G, as there are two different paths of the same distance (E-F-G) and (E-D-G).

We calculate something similar to what you are suggesting in the bottom_up() function.

**Comment by pavanraocr** [comment]
Thank you for the clarification.

If that is what it is suppose to be then the testcase seems to be related, i have implemented the function to work in that way but the explanation of the variables seems to tell a different story so not sure on which is correct.

**Comment by aronwc** [comment]
@pavanraocr @joezhang2  Right -- to say it another way: node2num_paths is the number of shortest paths from the root node to this node. The test case is correct.

**Comment by pavanraocr** [comment]
@aronwc - Thank you professor for the clarification.
