### ISSUE TITLE
NetworkXError: The node T is not in the graph.

### ISSUE THREAD

**Issue by shorabhd** [iit-cs579/main#215]
Hi,

I am getting this error when I ran my code for the facebook data, backtracking to BFS function from main function when score_max_depths function is called. The code runs perfectly for example graph. 

Thanks

**Comment by anushamrl** [comment]
This happens if the deque is initialized with the root like deque(root). It is better to create a deque and then append the root. Hope this helps.

**Comment by shorabhd** [comment]
Thanks.  That worked,  Now I am getting Divide by zero error in norm_cut function

**Comment by aronwc** [comment]
@shorabhd see #197

**Comment by shorabhd** [comment]
Yes it worked. Thanks
