### ISSUE TITLE
path_score output changes on every run

### ISSUE THREAD

**Issue by kunaldhande** [iit-cs579/main#216]
I ran path_score couple of times. Here is my output:

1st run:

[(('Bill Gates', 'Bill & Melinda Gates Foundation'), 0.06000000000000001), (('Bill Gates', 'Gavi, the Vaccine Alliance'), 0.04000000000000001), (('Bill Gates', 'Al Gore'), 0.020000000000000004), (('Bill Gates', 'Ezra Klein'), 0.020000000000000004), (('Bill Gates', 'ASUS'), 0.010000000000000002)]
path accuracy for beta .1=0.4

2nd run:

[(('Bill Gates', 'Gavi, the Vaccine Alliance'), 0.04000000000000001), (('Bill Gates', 'Al Gore'), 0.020000000000000004), (('Bill Gates', 'CDC Global'), 0.020000000000000004), (('Bill Gates', 'Ezra Klein'), 0.020000000000000004), (('Bill Gates', 'Global Poverty Project'), 0.020000000000000004)]
path accuracy for beta .1=0.2

3rd run:
[(('Bill Gates', 'Bill & Melinda Gates Foundation'), 0.06000000000000001), (('Bill Gates', 'Global Citizen'), 0.06000000000000001), (('Bill Gates', 'Gavi, the Vaccine Alliance'), 0.04000000000000001), (('Bill Gates', 'MY World'), 0.030000000000000006), (('Bill Gates', 'Aeras'), 0.020000000000000004)]
path accuracy for beta .1=0.4

**Comment by aronwc** [comment]
Are you handling ties properly?
>  Ties are broken by alphabetical order of the terminal node in the edge.
