### ISSUE TITLE
Evaluate function values change on every run

### ISSUE THREAD

**Issue by shalinchopra** [iit-cs579/main#219]
**1st RUN**

top jaccard scores for Bill Gates:
[(('Bill Gates', 'Global Citizen'), 0.16216216216216217), (('Bill Gates', 'Bill & Melinda Gates Foundation'), 0.10344827586206896), (('Bill Gates', 'Grand Challenges Canada'), 0.0937
5), (('Bill Gates', 'I fucking love science'), 0.09375), (('Bill Gates', 'Girl Effect'), 0.09090909090909091)]
**jaccard accuracy=0.2**

top path scores for Bill Gates for beta=.1:
[(('Bill Gates', 'Bill & Melinda Gates Foundation'), 0.06000000000000001), (('Bill Gates', 'Global Citizen'), 0.06000000000000001), (('Bill Gates', 'Gavi, the Vaccine Alliance'), 0.0
4000000000000001), (('Bill Gates', 'FutureWeWant'), 0.030000000000000006), (('Bill Gates', 'Girl Effect'), 0.030000000000000006)]
**path accuracy for beta .1=0.4**

**2nd Run**
top jaccard scores for Bill Gates:
[(('Bill Gates', 'Global Citizen'), 0.16216216216216217), (('Bill Gates', 'Bill & Melinda Gates Foundation'), 0.10344827586206896), (('Bill Gates', 'Grand Challenges Canada'), 0.0937
5), (('Bill Gates', 'I fucking love science'), 0.09375), (('Bill Gates', 'Girl Effect'), 0.09090909090909091)]
**jaccard accuracy=0**

top path scores for Bill Gates for beta=.1:
[(('Bill Gates', 'Bill & Melinda Gates Foundation'), 0.06000000000000001), (('Bill Gates', 'Global Citizen'), 0.06000000000000001), (('Bill Gates', 'Gavi, the Vaccine Alliance'), 0.0
4000000000000001), (('Bill Gates', 'FutureWeWant'), 0.030000000000000006), (('Bill Gates', 'Girl Effect'), 0.030000000000000006)]
**path accuracy for beta .1=0**

**Comment by vmanikes** [comment]
I had the same issue and there are 2 solutions for it which I used:
1) check if you are doing graph.copy() for make training graph.
2) in sccore_max_depths for the norm_cut params use component[0].nodes() and component[1].nodes() instead of components[0] and components[1]

**Comment by Nirali28** [comment]
I did the same still facing same problem.

**Comment by theTechie** [comment]
check very closely how you are calculating the fraction; there is a peculiar thing about edges in graphs; i am not sure if i can disclose that here.

**Comment by Nirali28** [comment]
mine make_training_graph method  was wrong. I guess that was the reason. Now it works! 
Thank you all.

**Comment by shalinchopra** [comment]
I made a small mistake in make_training_graph method, and its working fine now.

Thank you all.
