### ISSUE TITLE
nx.is_connected() for partition girvan newman function

### ISSUE THREAD

**Issue by saiarjuntanguturi** [iit-cs579/main#221]
Hi,
Just wanted to make sure I could use the nx.is_connected() method in the partition girvan newman function? To check if the graph is still connected.

**Comment by aronwc** [comment]
Yes,  you can use that or `nx.connected_component_subgraphs`.
-Aron

On Mon, Oct 3, 2016 at 12:26 PM, saiarjuntanguturi <notifications@github.com
