### ISSUE TITLE
Cluster to nodes all values are same except  the order

### ISSUE THREAD

**Issue by vchariharan** [iit-cs579/main#222]
All values are same except the order..

Will marks be reduced for that?

Below the log

['Clifford The Big Red Dog', 'Arthur A. Levine Books', 'Scholastic Teachers', 'WordGirl', 'Scholastic Book Fairs', 'Scholastic Reading Club', 'READ 180', 'Scholastic Parents', 'The Hunger Games', 'Scholastic Canada', 'Scholastic']

**Comment by ClaytonTurner** [comment]
This is fine. See: https://github.com/iit-cs579/main/issues/205
