### ISSUE TITLE
Extension untill Friday, 7th oct 

### ISSUE THREAD

**Issue by ShrutiNaik1991** [iit-cs579/main#223]
Hi Professor/TA's,

Is it possible to give an extension for this assignment for 4 days and push the deadline to Friday night. 

There are couple of complexity issues with functions and it doesn't seem to fulfill all doc tests. An extension will be very helpful in completing the assignment more efficiently. Thank you.

**Comment by ClaytonTurner** [comment]
As you may have seen from Dr Culotta's email, the deadline has been extended to Wednesday, October 5th, 11:59pm

**Comment by ShrutiNaik1991** [comment]
Thank you so much.
