### ISSUE TITLE
tokenize() output correct but doctest not passing

### ISSUE THREAD

**Issue by hegdenagaraj4** [iit-cs579/main#227]
Dear Professor,
 I have the output correct. But the doctest is not passing. I am not sure of the reason. I am running the file on a ubuntu machine. (Not a vmd). Please take a look at the output.
File "/home/raj/OSNA/hegdenagaraj4/a2/a2.py", line 89, in tokenize
Failed example:
    tokenize(" Hi there! Isn't this fun?", keep_internal_punct=False)
Expected:
    array(['hi', 'there', 'isn', 't', 'this', 'fun'],
          dtype='<U5')
Got:
    array(['hi', 'there', 'isn', 't', 'this', 'fun'], 
          dtype='<U5')

File "/home/raj/OSNA/hegdenagaraj4/a2/a2.py", line 92, in tokenize
Failed example:
    tokenize("Hi there! Isn't this fun? ", keep_internal_punct=True)
Expected:
    array(['hi', 'there', "isn't", 'this', 'fun'],
          dtype='<U5')
Got:
    array(['hi', 'there', "isn't", 'this', 'fun'], 
          dtype='<U5')

----------------------------------------------------------------------
Ran 1 test in 0.005s

FAILED (failures=1)

**Comment by davidghiurco** [comment]
you cannot have a space in between the end quote of the comment that contains the doctest and the actual output that is expected
Example:
def foo():
"""
>>>foo
foo <--- NO LINE BREAK BETWEEN THIS
""" <----  AND THIS

**Comment by davidghiurco** [comment]
Ok I'm actually confused too because I'm getting something similar:
Expected:
    array(['hi', 'there', "isn't", 'this', 'fun'],
          dtype='<U5')
Got:
    array(['hi', 'there!', "isn't", 'this', 'fun?'],
          dtype='<U6')

**Comment by sgupta57** [comment]
There is a exclamation and question mark after there and fun respectively.
That's why it failed.

**Comment by davidghiurco** [comment]
I understand that. I'm working on fixing the regular expression to get rid of those, but still the dtype is different

**Comment by saiarjuntanguturi** [comment]
Also notice the dtype, where the U stands for unicode, and the number is the length of the largest string in the array (i.e. number of bytes for each element in the array). Your U6 is because of the extra exclamation. U5 means the largest string is 5 bytes of unicode chars (i.e. 5 chars).

**Comment by davidghiurco** [comment]
Ah I see. Does anyone have a good recommendation on how to figure out the regular expression? It's such an ethereal way of programming that I don't understand all the bunch of characters. It's really confusing :\

**Comment by hegdenagaraj4** [comment]
You can try using [ ].You can fix those exclamation and question mark.  Despite that I am not able to pass doictest though my outputs are correct.

**Comment by saiarjuntanguturi** [comment]
Don't want to give my implementation away, but these resources helped a lot!
https://docs.python.org/2/library/re.html
http://pythex.org/
Play around with different regexes and see where they match. Cannot emphasize how much pythex helped.

**Comment by davidghiurco** [comment]
ok so my False test cast passes now, and my True test case gives correct ouput but fails just like @hegdenagaraj4 

I'm finding all words based on [a-zA-Z0-9_'-.]+ which is essentially \w augmented with apostrophe and hyphen and dot

my output now: (False test case not shown, since it passes)
Failed example:
    tokenize("Hi there! Isn't this fun? ", keep_internal_punct=True)
Expected:
    array(['hi', 'there', "isn't", 'this', 'fun'],
          dtype='<U5')
Got:
    array(['hi', 'there', "isn't", 'this', 'fun'],
          dtype='<U5')

**Comment by saiarjuntanguturi** [comment]
Did you remove spaces after the doctest? You might've added one on accident. Make sure the line ends after the  dtype = '<U5') block. If there's a space right after, my test fails (just tried it right now). It must be a formatting issue since your first test passes, and the output for the second test is correct, but it fails.

**Comment by davidghiurco** [comment]
Yeah it was a formatting issue. My IDE was removing an empty space from the test and apparently that had to be there.
