### ISSUE TITLE
Internal Punctuation

### ISSUE THREAD

**Issue by saiarjuntanguturi** [iit-cs579/main#228]
Is '(apostrophe) the only type of internal punctuation? Or can it be ANY type of punctuation inside of a word?

**Comment by saiarjuntanguturi** [comment]
Okay hyphens and apostrophes can go in between words. Should we account for decimals, etc. too?

**Comment by aronwc** [comment]
Any type of punctuation.

**Comment by sure00** [comment]
Could you help to give some hint how to finish this without substitute the
word that has internal punctuation?

**Comment by saiarjuntanguturi** [comment]
Hmmm I would guess regex.

**Comment by davidghiurco** [comment]
Any type of punctuation? 

so "wo?rd" would be correct but "word?" would not be? How in the world do we write a regex for that?

**Comment by aronwc** [comment]
> so "wo?rd" would be correct but "word?" would not be?
Correct.

It doesn't have to be just a single regular expression. (It is possible to do with one regex, but you're welcome to find alternative solutions.)

**Comment by davidghiurco** [comment]
@aronwc  Professor I've tried for a couple of hours to write the one regex but I just can't seem to get a handle on it. Instead, what I do is I split on whitespace, keeping all punctuations, then I check the end of each token to see if it is not alphanumeric in which case I cut off the non-alphanumeric character, thus excluding external punctuation

Is that too inefficient?

**Comment by aronwc** [comment]
That should he fine.
