### ISSUE TITLE
token_features [a2]

### ISSUE THREAD

**Issue by davidghiurco** [iit-cs579/main#230]
the signature:
def token_features(tokens, feats):
    Params:
      tokens...array of token strings from a document.
      feats....dict from feature name to frequency

tokens is described to be a numpy array (that would supposedly be passed in from the tokenize() function.

but the doctest passes in a list:
token_features(['hi', 'there', 'hi'], feats)

So which is it, a numpy array or a list of tokens?

**Comment by sgupta57** [comment]
I don't think we need to call tokenize function to get the tokens.

**Comment by saiarjuntanguturi** [comment]
I think it'll be a numpy array, but the professor tested it with a list of tokens in the doctests. Iterating through either of them should be quite similar, so for the purpose of testing it shouldn't make a difference.

**Comment by davidghiurco** [comment]
I'm not saying we NEED to call the tokenize function anywhere ... but those tokens when running the program for real, need to come from somewhere, and that somewhere probably is the tokenize function.

In the case of the doctest, the tokens come from user input.

The problem is that I want to write the function correctly so that i both pass the doctest, and have the correct functionality so that I don't crash when running the real program due to incompatible data types.

So in order to pass the doctest and still follow the specification that tokens is an array, I changed:
token_pair_features(np.array(['a', 'b', 'c', 'd']), feats)
instead of
token_pair_features(['a', 'b', 'c', 'd'], feats)

But I need to make sure this is the way that token_features is supposed to work.

**Comment by saiarjuntanguturi** [comment]
For the intents of this function (iterate through array, and update feats accordingly), I don't think it should make a difference as to whether you're given a Python list, or a numpy array. A numpy array (of rank 1), and a list are very similar, although numpy is better on memory (notice the datatype constraint), and gives you a ton of extra functionality. You should be able to iterate through both of them in a similar fashion (my function works for both).

**Comment by davidghiurco** [comment]
oh the numpy array is iterable just like a list ... I missed that. Gotcha. thanks @saiarjuntanguturi
