### ISSUE TITLE
l09.ipynb 

### ISSUE THREAD

**Issue by pliu19** [iit-cs579/main#232]
Hi Professor, 

I think there is some display issues in I09.ipynb. It's in the Cascades and Clusters part, about the threshold of halting with a cluster...

Best wishes, 
Ping Liu

**Comment by aronwc** [comment]
Sometimes github doesn't render notebooks properly. Try downloading locally
and running the notebook yourself, or a different browser (I've had luck
with Firefox)
-Aron

**Comment by pliu19** [comment]
Thanks so much. I tried to open in NB viewer. Now it's OK.

Best wishes, 
Ping Liu

**Comment by sure00** [comment]
Yes, I find similar issue. So i checked the video instead of reading the
note.

**Comment by ClaytonTurner** [comment]
Just to add on to here for anyone with similar issues in the future. I bleive this is completely based on your browser. I've found that Firefox and Chrome load this perfectly typically, but some linux-based browsers have rendered it poorly or even as pure xml. So downloading/running locally or switching browsers are the ways to fix this with ease.
