### ISSUE TITLE
Solutions for Textbook/Sample questions.

### ISSUE THREAD

**Issue by ishujaswal** [iit-cs579/main#234]
Hello Prof/TA,

Can you please let me know where can I find the solutions for the sample questions(shared by you) , for the book "Mining of Massive Datasets".

**Comment by davidghiurco** [comment]
I second that notion :)

**Comment by aronwc** [comment]
Sorry, solutions are not available for those.
Best,
Aron

**Comment by joezhang2** [comment]
You can verify your solutions by modifying the graph in lecture 5 so it resembles the graph in problem 10.2.1. You can then run the section that outputs betweenness scores for the graph to verify 10.2.1 and 10.2.2 were done correctly. For 10.2.3 its pretty evident from just looking at the graph, we should remove edges: B-H, C-D, G-E, this can be verified from the betweenness scores you calculated and you can determine the threshold should be >=9.5

For the matricies in 10.4, you just need to modify the graph in lecture 6 and you can check if you are calculating the matrices correctly.

You will have to run the notebook and not view in github if that wasn't evident. I guess you could write a simple program in python using networkx to do this, but the code is pretty much already written by the professor so why bother.

**Comment by ishujaswal** [comment]
Thanks!!
