### ISSUE TITLE
Issue in list of functions in featurize

### ISSUE THREAD

**Issue by vmanikes** [iit-cs579/main#235]
Can some one tell me how the list of functions work. For example, the second parameter in featurize "[token_features, lexicon_features]" these 2 functions are not returning anything, so how to extract the result from these methods? If some link can be provided for such kind of syntax would also help.

Thanks in advance

**Comment by aronwc** [comment]
The `feature_fns` parameter to the `featurize` function is a list of Python function objects. (Functions can be passed just like ordinary variables). Here's an example:
```python
>>> def prod(x, y):
...   return x * y
... 
>>> def run_fn(function, x, y):
...   return function(x, y)

>>> run_fn(prod, 10, 20)
200

>>> def div(x, y):
...   return x / y

>>> run_fn(div, 10, 20)
0.5
```
Here, `run_fn` will run whatever function you pass in on the variables `x` and `y`.

In the assignment, all the feature functions (`lexicon_features`, `token_features`, etc.) have a second parameter called `feats`, which is a dict from feature name to value. Each feature function modifies that dict directly, so there is no need to return anything.

```python
>>> feats = {}
>>> def fake_feature(tokens, feats):
...   feats['foo'] = 'bar'
>>> fake_feature([], feats)
>>> feats
{'foo': 'bar'}
```

**Comment by vmanikes** [comment]
Thank you so much professor
