### ISSUE TITLE
Issues in vectorize 

### ISSUE THREAD

**Issue by vmanikes** [iit-cs579/main#236]
Hello professor 
Can you give me some links how the vectorize method works. I know it was discussed in clss but i am having a hard time understanding it how the matrix is getting generated. Can u provide me some links where i can i read through. Scikit documentation has a example but not a explanation.

**Comment by aronwc** [comment]
See the documentation on csr_matrix: https://goo.gl/f5TiF1 . There are examples of constructing and using these sparse matrices.

When constructing a csr_matrix, it's usually best to first create the data/rows/cols variables, then pass them to the constructor csr_matrix((data, (row_ind, col_ind)). 

The example they give is:

```python
>>> row = np.array([0, 0, 1, 2, 2, 2])
>>> col = np.array([0, 2, 2, 0, 1, 2])
>>> data = np.array([1, 2, 3, 4, 5, 6])
>>> csr_matrix((data, (row, col)), shape=(3, 3)).toarray()
array([[1, 0, 2],
       [0, 0, 3],
       [4, 5, 6]])
```

In the `vectorize` method, you'll loop through each document (represented as a list of tokens). You'll then call `featurize` on each document to create the feature list. Along the way, you'll need to store a mapping from each feature name to an integer, representing the column for that feature.

For example, for two documents:

```python
>>> docs = [['i', 'like', 'movies'], ['you', 'like', 'shows']]
>>> features = [{'token=i': 1, 'token=like': 1, 'token=movies': 1},
... {'token=you': 1, 'token=like': 1, 'token=shows': 1}]
>>> vocab = {'token=i': 0, 'token=like': 1, 'token=movies': 2, 'token=you': 3, 'token=shows': 4}
```
With those objects, you should then be able to construct the matrix.

Also keep in mind the `min_freq` and `vocab` parameters, which will complicate the above a little bit.

**Comment by vmanikes** [comment]
Do we need to call `featurize` or `token_features` from the `feature_fns` parameter.

**Comment by aronwc** [comment]
I don't quite understand your question. `feature_fns` is a list of Python function objects. The `vectorize` function will pass `feature_fns` to the `featurize` function. This is how the features will be computed for each document.

The `token_features` function will be one element of the `feature_fns` list. See this line from the `main` method
```python
feature_fns = [token_features, token_pair_features, lexicon_features]
```

**Comment by vmanikes** [comment]
Got it professor Thank you

**Comment by vmanikes** [comment]
Hello professor,
When I am doing the data part for the tokens `["Isn't this movie great?", "Horrible, horrible movie"]`, I am calling featurize on this array, here movie is repeated in 2 documents So I need to get movie 2 times in the features dict to fill the data part of the array but I am getting only once like this 
`
 {'token=isn': 1, 'token=movie': 1, 'token=horrible': 2, 'token=this': 1, 'token=t': 1, 'token=great': 1}
`which is making my data array to appear as
`[1,2,0,1,1,1,1] `instead of [1,2,0,1,1,1,1,1]
Can you give me any idea how to fix it??

**Comment by aronwc** [comment]
You should create one feature dict per document. In this example there are two "documents":
- "Isn't this movie great?"
- "Horrible, horrible move"

You should be calling featurize on each document separately. This results in two rows in the final feature matrix:
- [1, 0, 1, 1, 1, 1],
- [0, 2, 0, 1, 0, 0]]

with corresponding vocab

[('token=great', 0), ('token=horrible', 1), ('token=isn', 2), ('token=movie', 3), ('token=t', 4), ('token=this', 5)]

**Comment by vmanikes** [comment]
So in the actual data will there be only 2 documents or more than that?

**Comment by davidghiurco** [comment]
No the actual data is a big list of documents. There are not just 2
documents.....

**Comment by vmanikes** [comment]
Got it @davidghiurco . Thanks man
