### ISSUE TITLE
Questions about "min_freq" in vectorize function

### ISSUE THREAD

**Issue by pliu19** [iit-cs579/main#237]
Hi Professor, 

For "min_freq" parameter, is it for all the counts in all the docs, or for the counts in each document?

For example, 

|      | A | B | C | D |
|------|---|---|---|---|
| DOC1 | 1 | 0 | 1 | 3 |
| DOC2 | 0 | 2 | 1 | 0 |

If this is the X array, and the "min_freq=1", do we need to remove A or C?( Or A, C)

Best wishes, 
Ping Liu

**Comment by aronwc** [comment]
> Remove features that do not appear in at least min_freq different documents.

In your example, if min_freq=1, we would not remove any features, since all features appear in at least 1 document.

If we set min_freq=2, then we'd remove A, B, D.

**Comment by pliu19** [comment]
Thanks for replying and clarifying, Professor. 

Best wishes,

**Comment by Swapnil2095** [comment]
Does that mean we have to check appearance of non-zero values in respective feature column and if it is less than min-freq then we have to remove that feature from csr_matrix?

**Comment by aronwc** [comment]
Yes, though it may be easier to do this check prior to building the csr_matrix.

**Comment by Swapnil2095** [comment]
Thanks !!

**Comment by Swapnil2095** [comment]
Whenever I am tring to remove element from list using remove/pop/del  the index changed and I am not getting expected removal from row,col and data list (csr_matrix feed)

How to tackle this?

    row=  [0, 0, 0, 0, 0, 1, 1]
    col=   [0, 2, 3, 4, 5, 1, 3]
    data= [1, 1, 1, 1, 1, 2, 1]

    counter= Counter({3: 2, 0: 1, 1: 1, 2: 1, 4: 1, 5: 1})
    Columns to remove -
    index=0 col=0  occurances=1
    index=1 col=2  occurances=1
    index=3 col=4  occurances=1
    index=4 col=5  occurances=1
    index=5 col=1  occurances=1

     Columns to remove -
    index=0 col=0  occurances=1
    Removed -> index=0 col=0  occurances=1
    index=1 col=3  occurances=2
    index=2 col=4  occurances=1
    Removed -> index=2 col=4  occurances=1
    index=3 col=1  occurances=1
    Removed -> index=3 col=1  occurances=1
    row=  [0, 0, 0, 1]
    col=   [2, 3, 5, 3]
    data= [1, 1, 1, 1]

after removal index get changed and some elements not vising again. So how to tackle this?
