### ISSUE TITLE
doctests failing for tokenize()

### ISSUE THREAD

**Issue by thirumalrao** [iit-cs579/main#238]
Hi,

I am seeing the same problem reported in the issue #227 
Creating a new issue since the other was closed.

I am using mac and pycharm IDE, checked that the string is not automatically stripped of trailing whitespaces. 

My output is given below. 

File "/Users/thirumal/git/thirumalrao/a2/a2.py", line 113, in a2.tokenize
Failed example:
    tokenize(" Hi there! Isn't this fun?", keep_internal_punct=False)
Expected:
    array(['hi', 'there', 'isn', 't', 'this', 'fun'],
          dtype='<U5')
Got:
    array(['hi', 'there', 'isn', 't', 'this', 'fun'],
          dtype='<U5')

Failed example:
    tokenize("Hi there! Isn't this fun? ", keep_internal_punct=True)
Expected:
    array(['hi', 'there', "isn't", 'this', 'fun'],
          dtype='<U5')
Got:
    array(['hi', 'there', "isn't", 'this', 'fun'],
          dtype='<U5')

**Comment by aronwc** [comment]
In what you've pasted here, in the expected output, there appears to be a trailing space after '<U5')_<-here!

There shouldn't be that trailing space.

Many editors can be configured to highlight when trailing space exists; I'm sure PyCharm can do this somehow.

**Comment by thirumalrao** [comment]
Checked the expected and my output in BBEdit. It shows that expected output has a newline character at the end and mine doesn't have. Should I add a newline character at the end ?

<img width="353" alt="screen shot 2016-10-15 at 10 35 24 am" src="https://cloud.githubusercontent.com/assets/3600270/19412108/483e0626-92c3-11e6-8c23-d4b1ffd0126d.png">

**Comment by thirumalrao** [comment]
ok.. added report_NDIFF

Failed example:
    tokenize(" Hi there! Isn't this fun?", keep_internal_punct=False) #doctest: +REPORT_NDIFF
Differences (ndiff with -expected +actual):
    - array(['hi', 'there', 'isn', 't', 'this', 'fun'],
    + array(['hi', 'there', 'isn', 't', 'this', 'fun'],
    ?                                                  +
            dtype='<U5')

I do see the extra whitespace. But what I don't understand is how is this extra space getting added. I am converting a list to a bumpy array and I don't see any whitespace in the list.

**Comment by theTechie** [comment]
So, i believe we use NORMALIZE_WHITESPACE directive and ignore this error ?

**Comment by aronwc** [comment]
That's fine - as long as the tokens are correct, don't worry about the trailing whitespace. Just an artifact of the doctest string.

**Comment by thirumalrao** [comment]
Thanks !
