### ISSUE TITLE
KFold Cross Validation

### ISSUE THREAD

**Issue by saiarjuntanguturi** [iit-cs579/main#240]
For eval_all_combinations, what values do we use for k (i.e. number of folds) from cross_validation_accuracy? Should we try different values?

**Comment by aronwc** [comment]
5


On Fri, Oct 14, 2016 at 1:37 PM, saiarjuntanguturi <notifications@github.com

**Comment by aronwc** [comment]
This was also fixed in an earlier commit:
https://github.com/iit-cs579/assignments/commit/0bf145e04a5a3931fbb2e5d2a8ef1433405cb7fa

Please be sure to run `./update` to get the latest code before working on the assignment.
