### ISSUE TITLE
Is punctuation at the beginning of a word an in-word punctuation?

### ISSUE THREAD

**Issue by Neotrino** [iit-cs579/main#242]
e.g. "#awesome" if keep_in_punct is true, should we return "#awesome" or "awesome"?

**Comment by ClaytonTurner** [comment]
I'm thinking it should be "awesome" as "there!" does not retain the exclamation mark so the "!" is effectively not internal which makes sense for the beginning of the word to also not be internal and, rather, external.

**Comment by aronwc** [comment]
Correct. "awesome"

**Comment by KSP16SCM52J** [comment]
On Oct 14, 2016 8:00 PM, "Neotrino" <notifications@github.com> wrote:
>
> Closed #242 <https://github.com/iit-cs579/main/issues/242>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
<https://github.com/iit-cs579/main/issues/242#event-824715861>, or mute the
thread
