### ISSUE TITLE
Need help in vectorize function

### ISSUE THREAD

**Issue by Swapnil2095** [iit-cs579/main#243]
I am not getting how we can add sorted values of vocab dictionary in the CSR_matrix.

How we can arrange or rearrange the column of the matrix.

Do you need  separate loops over tokens_list as I am not able to fill vocab dict and csr_matrix in one single loop.

I tried, and I am able to add values in csr_matrix but those are not sorted alphabetically (column-wise)

Please give me some guidelines to tackle this.

**Comment by davidghiurco** [comment]
I think you've got the idea wrong. You don't have to rearrange matrix
columns. Instead sort the entries and then enter them sequentially into the
matrix

**Comment by Swapnil2095** [comment]
I know we have to sort but for that we require two time loop on token_list.
One for creating vocab dictionary and other for filling csr-matrix.
But still I don't get how to fill that matrix in second token_list loop.

**Comment by davidghiurco** [comment]
Sorting has to happen either way. Whether it happens internally in the csr
matrix or extrernally then the input is put into the matrix.
There's no way to do O(n) work in O (1) ..... if you do find a way....you'd
probably win a nobel prize.

**Comment by Swapnil2095** [comment]
You still don't get my point man.
**Whether it happens internally in the csr
matrix or extrernally then the input is put into the matrix.**
-> Sorting to happen in csr -> again cloumn are going to sort
-> extrernally then the input is put into the matrix -> for that we have to find entire vocabulary

See what I asked earlier -> For both thing we required to traverse token_list 2 times?

just give suggestions.
Don't be over-smart and give rubbish answers.

**Comment by aronwc** [comment]
Folks,

I appreciate having an active discussion here, but *please* let's be civil to one another. We are all here to learn.

To answer this question -- yes, it's fine if you do two loops; the first to compute all the features, then a second to create the data/rows/cols variables needed to construct the csr_matrix. In between these two loops, you should sort and prune the vocabulary.

Best,
Aron

**Comment by vmanikes** [comment]
Please refer issue #236

**Comment by Tsreenivasan** [comment]
By creating  two loops, My eval_all_combinations procedure takes over 5 minutes for processing the data as per the main method parameters. I'm still trying to find where i'm using redundant Loops/actions.

How are everybody else doing on the execution time?
