### ISSUE TITLE
# of experiments in eval_all_combinations function

### ISSUE THREAD

**Issue by pliu19** [iit-cs579/main#244]
Hi Professor/TA, 

About the number of experiments in eval_all_combinations function, is it 3 * 2 * 7 = 42 in total?

**Comment by vjonnala** [comment]
Can you explain me what 3,2,7 are ?

**Comment by pliu19** [comment]
7 is the combination of functions, 2 is [True, False] for punct_vals, 3 is the min_freq . I'm not sure it's correct or not....

**Comment by vjonnala** [comment]
Its given 
"In addition to looping over possible assignments to
    keep_internal_punct and min_freqs, we will enumerate all
    possible combinations of feature functions."
So, you are correct.

**Comment by cicirao** [comment]
So we have to go through not only all combinations of functions. Each combination should also go through each punct_vals and min_freq. Right?

**Comment by vjonnala** [comment]
Yes.
Refer the note:
"In addition to looping over possible assignments to
keep_internal_punct and min_freqs, we will enumerate all
possible combinations of feature functions."
