### ISSUE TITLE
Different with Log.text

### ISSUE THREAD

**Issue by Neotrino** [iit-cs579/main#245]
Hi professor,

My final output is slightly different with log.txt. Can I take a look at your entire output of function evaluate _all_combinations results, so that I can tell what is going wrong with my program. Thanks.

**Comment by ClaytonTurner** [comment]
In what ways is it different? It may just be some simple formatting issues that can be fixed. Also, make sure you have the most up to date repo via update.sh because an issue from an old repo could cause an issue.
