### ISSUE TITLE
token_pair_features

### ISSUE THREAD

**Issue by RittickDatta** [iit-cs579/main#247]
Hi professor, 

When I am generating the pairs, I have a condition that a duplicate pair cannot be generated but this is reducing the count of the pair by 1.

How should I go about implementing this method? I have too many data structures to handle the data.

**Comment by ClaytonTurner** [comment]
You shouldn't be off by 1 if you're only removing duplicates. Do you maybe have an off by 1 error in your loop?

**Comment by RittickDatta** [comment]
Referring to the doctest, if we have a numpy array as [a, b, c, d], then I get only a single b_c feature pair instead of 2 b_c pairs. Can you please explain the process to create those pairs while not removing two occurences of b_c ?

**Comment by davidghiurco** [comment]
You need a subroutine that gets all the "windows" of a list. Stackoverflow
has info about how to write this.
And then iterate over each window using a nested for loop to create all the
pairs.

**Comment by joezhang2** [comment]
Here is an example of a simple brute force approach. Dynamic programming/ a smarter algorithm to deal with duplicates would run faster, but I haven't quite figured out how to implement that. 

Assume tokens = [a, b, c, d, e, f] and k =4, where [a,b] += 1 means ['token_pair=a__b'] += 1 

Set the pointer to 'a' and current list = [a,b,c,d]
[a,b] += 1, [a,c] +=1, [a,d] += 1
[b,c] +=1, [b,d] += 1
[c,d] +=1
...
Set the pointer to 'b' and current list = [b,c,d,e]
[b,c] += 1, [b,d] +=1, [b,e] += 1
[c,d] +=1, [c,e] += 1
[d,e] +=1
...
etc

Hopefully the pattern is clear at this point. You can use recursion to make life easier, I needed around 10 lines of code and didn't have to make any additional data structures.

**Comment by davidghiurco** [comment]
I've figured out a much easier way. Can't really post my code here but I can post the stackoverflow posts that helped me out.

http://stackoverflow.com/questions/6822725/rolling-or-sliding-window-iterator-in-python

Like I said before, you want a subroutine the gets you all the k-length windows of a list, this is called a "rolling slider" or "window iterator." Python does not have it built-in so you have to write it. The link above gives quite a few ways to implement it.
Once you have that you can do something like:

for k_tuple in windows(tokens):
index = 0
while index < k:
    /// nested for loop here to get the first token and every other second token in the current    k_tuple
   /// make the token_pair here and update its value in the feats dict
 index += 1

This was the most logical way I found to do this method. It's easy on the eyes (no recursion or weird index manipulations going on)

**Comment by RittickDatta** [comment]
Thank you David and joe zhang, it was helpful of you guys. I think i should be able to implement it now.
