### ISSUE TITLE
Top coefficients for negative words

### ISSUE THREAD

**Issue by ranjeetkumar** [iit-cs579/main#249]
I am getting negative values of top coefficients for negative words. In log.txt, value is shown as positive. Do we have to take magnitude of the values of coefficients or my solution approach is wrong that result in negative values?

**Comment by vjonnala** [comment]
The method asks you to return the highest coefficients in the classifier for both positive and negative labels. For negative label, you need the negative of the coefficient and then sort it in descending order.

Hope this helps.

**Comment by vjonnala** [comment]
Yes.
Refer the note:
"In addition to looping over possible assignments to
keep_internal_punct and min_freqs, we will enumerate all
possible combinations of feature functions."
