### ISSUE TITLE
lexicon_features tokens parameter 

### ISSUE THREAD

**Issue by yepinxia** [iit-cs579/main#252]
In the doc tests for this method, one of the test case is "LOVE". But in tokenize method, all text should be converted to lowercase already. 

Are we supposed to handle non-token plain text as the parameter for this method? or can we assume the parameter passed through as tokens are actually tokens (which are lower case words without punctuations etc.)?

The test case only covers uppercase letters, if we can't assume the parameter contains only tokens, what are the other needed test cases? sentences, maybe?

Thanks.

**Comment by aronwc** [comment]
That test was to ensure your method follows the part of the instructions that says 
>The matching should ignore case.

The method otherwise can assume the input is a list of tokens, though it does not need to know how those tokens were processed.

**Comment by yepinxia** [comment]
gotcha, thanks!
