### ISSUE TITLE
parse_test_data

### ISSUE THREAD

**Issue by kyao4** [iit-cs579/main#253]
Hi, professor

Can you explain how can we make sure the feature mapping is consistent from training to testing by passing vocab into vectorize function?

**Comment by aronwc** [comment]
When you call `vectorize` to process the test data, make sure you pass the vocab you created when vectorizing the training data. In other words, don't create a new vocabulary when processing the test data. 

Furthermore, no new features should be added to the vocabulary when processing the testing data. 
E.g., if a word "unicorn" occurs only in the testing data, but not in the training data, it should not appear in your vocabulary. (It would be useless, as the classification model would have no corresponding coefficient.)

**Comment by kyao4** [comment]
Thnaks!
