### ISSUE TITLE
Using min_freq in vectorize()

### ISSUE THREAD

**Issue by vmanikes** [iit-cs579/main#254]
Hello professor ,
Do we need to use min_freq before creating a CSR matrix or after creating a CSR matrix ? I know the working of min_freq but not able to put the logic in place. Any ideas ??

**Comment by qsong4** [comment]
I think it can work both way, but I think its little complicated use it after creating a CST matrix

**Comment by vmanikes** [comment]
That's what is troubling me, can you suggest me which is the best way to do it  before or after?

**Comment by qsong4** [comment]
I think remove it before you create the matrix can help you create the matrix without using those unsatisfied features.
