### ISSUE TITLE
eval_all_combinations

### ISSUE THREAD

**Issue by qsong4** [iit-cs579/main#255]
Hello,

Is it possible we get same accuracy on different combination of features? For the same worst cross-validation, which one should we output?

**Comment by cicirao** [comment]
Sorry to use your issue to ask my earlier question (which was closed and I could not re-open it.) My question is, what does it mean to "construct a LogisticRegression classifier" for that setting? Is it using the LogisticRegression function? What would be the parameters? Would those functions be a part of the parameters?

**Comment by qsong4** [comment]
@cicirao You can use sklearn to construct the Logistic Regression classifier, I think we can use default value for the parameter of classifier.
After build the classifier you can use cross_validation_accuracy() function get the accuracy

**Comment by cicirao** [comment]
Thank you! I sort of understand it.. So functions are only used when we use featurize(), not construct the classifier?

**Comment by qsong4** [comment]
If the 'functions' you mean is the function use for generate features, then yes.

**Comment by cicirao** [comment]
Great! Thanks!

**Comment by vinits91** [comment]
In eval_all_combinations function, how can we get CSR matrix to be passed to cross_validation_accuracy() function ? after enumerating through all settings of combination, we have to call featurize() for each combination of functions which returns feature list where we will not be getting any CSR matrix.

**Comment by vjonnala** [comment]
You don't need to call featurize() method explicitly for each setting. Check for a function which does featurize() internally and returns you a CSR matrix. 
Hope this helps.

**Comment by davidghiurco** [comment]
@vinits91 vectorize() returns the CSR matrix that is meant to be passed to cross_validation_accuracy, and vectorize() is supposed to call featurize() internally
