### ISSUE TITLE
extension for assignment 2

### ISSUE THREAD

**Issue by sure00** [iit-cs579/main#256]
Hi Professor/TA's,

Is it possible to give an extension for this assignment for 3 days and push the deadline to Sunday night.

This two weeks a mid-term exam week and we put much more attention to prepare and take the exam which occupy us lots of time.

Thanks

**Comment by thirumalrao** [comment]
I second it ... Weekend will really help.

**Comment by Smrutipatel14** [comment]
Yes, an extension would be great

**Comment by aronwc** [comment]
Sorry, no extension this time.
