### ISSUE TITLE
Unicode issues in tokenize

### ISSUE THREAD

**Issue by nazanin90** [iit-cs579/main#260]
Hi everyone,

In the nosetest for the tokenize function this is what I get:

Expected:
    array(['hi', 'there', 'isn', 't', 'this', 'fun'], 
          dtype='<U5')
Got:
    array(['hi', 'there', 'isn', 't', 'this', 'fun'], 
          dtype='|S5')

It looks like the array elements should be of type unicode, but I get string. I tried converting them to unicode but then a u comes before each string.

Anyone has any idea what I'm missing here?

**Comment by ClaytonTurner** [comment]
Could you maybe try type-casting either the strings themselves or the array? http://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.astype.html

**Comment by saiarjuntanguturi** [comment]
I'm curious as to how you're making your numpy array. It should be sufficient to call the np.array(your_list_name) with your list of strings as an argument. If you did it by using np.chararray, you might have problems.

**Comment by nazanin90** [comment]
Dear Clayton,

When I do type-casting either strings or the array, this happens:
Expected:
    array(['hi', 'there', "isn't", 'this', 'fun'], 
          dtype='<U5')
Got:
    array([u'hi', u'there', u"isn't", u'this', u'fun'], 
          dtype='<U5')

saiarjuntanguturi:
I do it as np.array(your_list_name), and not np.chararray...

**Comment by nazanin90** [comment]
Another similar issue I have is this nosetest for vectorize-It doesn't show the dtype!

Expected:
    array([[1, 0, 1, 1, 1, 1],
           [0, 2, 0, 1, 0, 0]], dtype=int64)
Got:
    array([[1, 0, 1, 1, 1, 1],
           [0, 2, 0, 1, 0, 0]])

I even do this:
X = csr_matrix((data, (row, col)), shape=(N,M), dtype=np.int64)
but, it doesn't print it out in the output.

(When I change dtype to np.int8 or np.int32, it outputs it, but not when I set it to dtype=np.int64).

Does anyone know what could be the problem?

**Comment by ClaytonTurner** [comment]
Are you by-chance on a 32 bit system? If so, then try testing this on a 64 bit machine and see if it works. It could just be a native problem.

**Comment by anushamrl** [comment]
I'm also facing the same issue. Even I tried all the possible ways mentioned here with no success. Mine is a 64 bit machine, so not sure what is going wrong.

**Comment by aronwc** [comment]
I wouldn't worry too much about the dtype. The main thing is that the tokens are correct.
