### ISSUE TITLE
eval_all_combinations output questions

### ISSUE THREAD

**Issue by davidghiurco** [iit-cs579/main#262]
(you knew this was coming :P)

Log.txt gives the following output for best and worst results:
(*****modifed a bit to fix formatting issue in github display (removed the < > around functions*****)

best cross-validation result:
{'features': (function token_pair_features at 0x114172c80, function lexicon_features at 0x114172d08), 'punct': True, 'accuracy': 0.77000000000000013, 'min_freq': 2}
worst cross-validation result:
{'features': (function lexicon_features at 0x114172d08,), 'punct': True, 'accuracy': 0.64749999999999996, 'min_freq': 2}

My output is:

best cross-validation result:
{'punct': True, 'min_freq': 2, 'accuracy': 0.77000000000000013, 'features': (function token_pair_features at 0x7fd0c25dbbf8, function lexicon_features at 0x7fd0c25dbc80)}
worst cross-validation result:
{'punct': True, 'min_freq': 10, 'accuracy': 0.64749999999999996, 'features': (function lexicon_features at 0x7fd0c25dbc80,)}

I understand that it's not always going to be deterministic because dictionary keys are ordered more or less randomly.

However my question is about the worst cross-validation result:
Couple of disclaimers:
1) My result has the same accuracy (0.64749999999999996) for this worst result setting whether the min_freq = 2, 5 , or 10 (I checked the last 3 elements of the sorted dictionary list, they all had the same accuracy)
2) my program always returns the worst result with min_freq = 10 (since that's the last one in my list, the second to last being min_freq=5, and 3rd to last being min_freq=2, and the min_freq=2 result is seen in Log.txt)
3) eval_all_combinations instructions say: "This [list of dictionaries] should be SORTED in descending order of accuracy." It does not mention any other sorting criteria

My question is, *****is there another hidden/unmentioned sorting criteria in the professor solution?***** Because I don't see how the min_freq=2 result is in Log without adding another tie-breaking key to the sorting method on the dictionary list to sort tied results in descending min_freq order.

**Comment by cwang90** [comment]
I have the same problem, my worst cross validation result is minFreq = 10, and I just change minFreq to 2 keep other setting the same, the accuracy is the same. Is there any other sort criteria so that I can have same output as Log.txt?

**Comment by ClaytonTurner** [comment]
I don't think there is a hidden/unmentioned sorting criteria in Dr Culotta's solution

**Comment by viyatgandhi** [comment]
@davidghiurco @ClaytonTurner  I have same problem my result also have same accuracy for min_freq = 2, 5 , or 10. Professor has not mentioned any other criteria but I currently I have sorted against min _freq too to resolve dispute with original log.txt. Also, accuracy graph is matching so it should be fine to keep two sorting?

**Comment by ClaytonTurner** [comment]
Your logic makes sense, but I'm unsure of the extra sorting here because it will depend on the specific test cases run against your code. It's probably best for Dr Culotta to weigh in at this point as I don't know what the test cases look like yet.

**Comment by aronwc** [comment]
> 1) My result has the same accuracy (0.64749999999999996) for this worst result setting whether the min_freq = 2, 5 , or 10 (I checked the last 3 elements of the sorted dictionary list, they all had the same accuracy)

This is expected, since if we only use the lexicon features, there are only two features, and they occur in more than 10 documents. So, yes, there will be ties, so don't worry if the min_freq={2,5,10} is reported for the worst result.

**Comment by vinits91** [comment]
okay. So we will be only sorting result on accuracy resulting in different result than what is expected in log file for worst-case. No matter what [2,5,10] min_freq we get in worst-case. Thank you Professor.

**Comment by davidghiurco** [comment]
@aronwc that clears it up for me. Thank you.
