### ISSUE TITLE
vectorize - Content correct but format have problem

### ISSUE THREAD

**Issue by sure00** [iit-cs579/main#263]
Hi all 
    Have you meet this issue that scipy.sparse.csr.csr_matrix contain int 32 array while doctest require int 64? 
![image](https://cloud.githubusercontent.com/assets/6347772/19466123/8129099c-94ce-11e6-9f6e-8791a6deaa5a.png)

**Comment by pshah109** [comment]
Considering this example 

>>> row = np.array([0, 0, 1, 2, 2, 2])
>>> col = np.array([0, 2, 2, 0, 1, 2])
>>> data = np.array([1, 2, 3, 4, 5, 6])
>>> csr_matrix((data, (row, col)), shape=(3, 3)).toarray()
array([[1, 0, 2],
       [0, 0, 3],
       [4, 5, 6]])


Do something like

>>>row = np.array([0, 0, 1, 2, 2, 2],dtype='int64')
>>>col = np.array([0, 2, 2, 0, 1, 2],dtype='int64')
>>>data = np.array([1, 2, 3, 4, 5, 6],dtype='int64')
csr_matrix((data, (row, col)), shape=(3, 3)).toarray()


array([[1, 0, 2],
       [0, 0, 3],
       [4, 5, 6]], dtype=int64)

Hope this helps.

**Comment by davidghiurco** [comment]
I'm pretty sure this is a highly platform-specific..... are you running on a 32-bit machine?

**Comment by sure00** [comment]
Parth Shah . Thanks for your help.
