### ISSUE TITLE
different Mean Accuracies per Setting

### ISSUE THREAD

**Issue by viyatgandhi** [iit-cs579/main#265]
Hi,

The output of eval_all_combinations() is coming as expected in Log.txt but when I compute the mean_accuracy_per_setting() over same results the output differs with one in Log.txt with later few decimals.

Log.txt output:

Mean Accuracies per Setting:
features=token_pair_features lexicon_features: 0.75125
features=token_features token_pair_features lexicon_features: 0.74583
features=token_features token_pair_features: 0.73542
features=token_pair_features: 0.72875
min_freq=2: 0.72250
punct=False: 0.72024
min_freq=5: 0.71857
punct=True: 0.70810
min_freq=10: 0.70143
features=token_features lexicon_features: 0.69667
features=token_features: 0.69000
features=lexicon_features: 0.65125

My Output

Mean Accuracies per Setting:
features=token_pair_features lexicon_features: 0.75167
features=token_features token_pair_features lexicon_features: 0.74292
features=token_features token_pair_features: 0.73250
features=token_pair_features: 0.73000
min_freq=2: 0.72286
punct=False: 0.72012
min_freq=5: 0.71893
punct=True: 0.70821
min_freq=10: 0.70071
features=token_features lexicon_features: 0.70000
features=token_features: 0.69083
features=lexicon_features: 0.65125

It is because of [this](http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html).

_Notes
The underlying C implementation uses a random number generator to select features when fitting the model. It is thus not uncommon, to have slightly different results for the same input data. If that happens, try with a smaller tol parameter._

Is this expected or I have done something wrong in some method? Kindly help

**Comment by cwang90** [comment]
Same problem here, my output is:
features=token_pair_features lexicon_features: 0.75042
features=token_features token_pair_features lexicon_features: 0.74583
features=token_features token_pair_features: 0.73583
features=token_pair_features: 0.72875
min_freq=2: 0.72304
punct=False: 0.72024
min_freq=5: 0.71893
punct=True: 0.70845
min_freq=10: 0.70107
features=token_features lexicon_features: 0.69708
features=token_features: 0.69125
features=lexicon_features: 0.65125

Is that normal or did I miss something?

**Comment by aronwc** [comment]
Some variation is expected, though it's impossible for me to tell which variation is due to an error and which is not without looking at your code more closely.

Note that the comment about "The underlying C implementation..." doesn't apply here -- it only affects LogisticRegression when the parameter `penalty=l1`. But, there will still be small differences across platforms due to numerical stability issues.

**Comment by yepinxia** [comment]
Same... each of my accuracies are off ~0.002. 

Professor, could your share your Logistic Regression constructor parameters?

**Comment by aronwc** [comment]
I use the default constructor: `LogisticRegression()`

**Comment by viyatgandhi** [comment]
@aronwc Thank you professor for your comment. Hope what ever variation I have done is correct (Because I don't know what to check for and I have tested code for extra test cases too ). And if unfortunately not then I hope we have partial marks whatever we have done so far.
