### ISSUE TITLE
Top coefficient Function

### ISSUE THREAD

**Issue by pshah109** [iit-cs579/main#267]
Hi ,

The values I am getting are following, the tokens are correct however the values are different. Is that fine?
Also for negative coefficient I was getting values in negative which I have explicitly converted to positive. Is that approach correct?

TOP COEFFICIENTS PER CLASS:
negative words:
neg_words: 0.65930
token_pair=the__worst: 0.37445
token_pair=is__so: 0.31172
token_pair=about__the: 0.30080
token_pair=like__a: 0.26897

positive words:
pos_words: 0.52590
token_pair=it__is: 0.23952
token_pair=a__lot: 0.21045
token_pair=to__find: 0.20781
token_pair=the__and: 0.20571

**Comment by aronwc** [comment]
Some variation in the coefficients is expected.
Yes, you'll need to convert the negative coefficients to positive for printing purposes.

**Comment by vinits91** [comment]
So professor is it fine if our output doesn't match with one in Log.txt after few decimals ? because I am experiencing this problem while computing mean_accuracy_per_setting() which gives different decimals after few decimal numbers.

**Comment by aronwc** [comment]
Some variation in the coefficients is expected, but I cannot tell which variation is ok and which is not without grading your assignment.

**Comment by pshah109** [comment]
Thanks professor for clarification.
