### ISSUE TITLE
representing the setting of feature_fns in mean accuracies

### ISSUE THREAD

**Issue by vmanikes** [iit-cs579/main#268]
Hello 
In my `eval_all_combinations` I am getting the result as
 `{'features': (<function token_pair_features at 0x114172c80>, <function lexicon_features at 0x114172d08>), 'punct': True, 'accuracy': 0.77000000000000013, 'min_freq': 2}`.

When I want to do `mean_accuracy_per_setting` how do I represent the setting as `features=token_pair_features lexicon_features:` when I am getting the result as `<function token_pair_features at 0x114172c80>, <function lexicon_features at 0x114172d08>`

**Comment by vjonnala** [comment]
Search for a keyword to get the name of features from the result. There is an object in python which returns the name.

**Comment by vinaykai** [comment]
Even I am having the same problem, vmanikes were you able to solve it?
