### ISSUE TITLE
eval_all_combinations()

### ISSUE THREAD

**Issue by Swapnil2095** [iit-cs579/main#270]
I found out all combinations asked for -

   [{'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 2, 'punct': True}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 2, 'punct': True}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 2, 'punct': True}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 2, 'punct': True}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 2, 'punct': True}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 2, 'punct': True}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 2, 'punct': True}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 2, 'punct': False}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 2, 'punct': False}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 2, 'punct': False}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 2, 'punct': False}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 2, 'punct': False}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 2, 'punct': False}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 2, 'punct': False}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 5, 'punct': True}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 5, 'punct': True}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 5, 'punct': True}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 5, 'punct': True}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 5, 'punct': True}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 5, 'punct': True}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 5, 'punct': True}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 5, 'punct': False}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 5, 'punct': False}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 5, 'punct': False}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 5, 'punct': False}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 5, 'punct': False}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 5, 'punct': False}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 5, 'punct': False}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 10, 'punct': True}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 10, 'punct': True}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 10, 'punct': True}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 10, 'punct': True}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 10, 'punct': True}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 10, 'punct': True}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 10, 'punct': True}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 10, 'punct': False}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 10, 'punct': False}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 10, 'punct': False}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 10, 'punct': False}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 10, 'punct': False}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 10, 'punct': False}, 
    {'features': (<function token_features at 0x7f97c20c78c8>,), 'accuracy': 0, 'min_freq': 10, 'punct': False}]

Second ,I did
tokens_list = [tokenize(d) for d in docs]

Then for each combination,
               X, vocabulary = vectorize(tokens_list,feature,freq,vocabulary)
               value = cross_validation_accuracy(clf, X, labels, k=5)

Here my questions are,
1) What is the value we need to set for k i.e. number of folds ?
2) Do we require vocabulary returned from function-vectorize() . or we can overwrite it?
3)  I am just sending clf object to cross_validation_accuracy() - I need to ask is it fine, right? I don't want to do with it in eval_all_combinations().

**Comment by vjonnala** [comment]
1) #240 
2) There is no reason why to overwrite vocabulary returned in eval_all_combinations()
3) If clf is a Logistic Regression classifier, then it is correct.

Hope this helps,
