### ISSUE TITLE
lexcon features

### ISSUE THREAD

**Issue by hsingh1991** [iit-cs579/main#275]
def lexicon_features(tokens, feats):
    """
    Add features indicating how many time a token appears that matches either
    the neg_words or pos_words (defined above). The matching should ignore
    case.

    Params:
      tokens...array of token strings from a document.
      feats....dict from feature name to frequency
    Returns:
      nothing; feats is modified in place.

    In this example, 'LOVE' and 'great' match the pos_words,
    and 'boring' matches the neg_words list.
    >>> feats = defaultdict(lambda: 0)
    >>> lexicon_features(np.array(['i', 'LOVE', 'this', 'great', 'boring', 'movie']), feats)
    >>> sorted(feats.items())
    [('neg_words', 1), ('pos_words', 2)]
    """

what if their is no negative words in tokens:
should the output be   ['pos_words',2]
or it should be   [('neg_words', 0), ('pos_words', 2)]?

**Comment by ishujaswal** [comment]
I think it should be be ['pos_words',2] only.

**Comment by ranjeetkumar** [comment]
Technically speaking it should be what @ishujaswal said. But if we do that then doc test in featurize will fail. 

This is the doctest of featurize function: 
>>> feats = featurize(np.array(['i', 'LOVE', 'this', 'great', 'movie']), [token_features, lexicon_features])
    >>> feats
    [('neg_words', 0), ('pos_words', 2), ('token=LOVE', 1), ('token=great', 1), ('token=i', 1), ('token=movie', 1), ('token=this', 1)]

To pass doctest you should include neg_words count too

**Comment by saurabhsawhney** [comment]
@ishujaswal @hsingh1991- It should be [('neg_words', 0), ('pos_words', 2)]...... as in featurize if u dont include ('neg_words', 0) doc tests would fail.

**Comment by aronwc** [comment]
Right, include lexicon counts even if 0 (though technically this won't affect the resulting classifier, since omitted features have the value 0 by default).

**Comment by Swapnil2095** [comment]
Does that mean we have to keep ('neg_words', 0) in feat dictonary.
And it can be ignore during vectorize() function like 
for doc in tokens_list: 
        data = featurize(doc,feature_fns)
        for feature in data:                     
                if feature[1] >0 :+1: 
                   then only add to the feature of that particular doc

**Comment by Swapnil2095** [comment]
Does that mean we have to keep ('neg_words', 0) in feat dictonary.
And it can be ignore during vectorize() function like 
for doc in tokens_list: 
        data = featurize(doc,feature_fns)
        for feature in data:                     
                if feature[1] >0 :+1: 
                   then only add to the feature of that particular doc
