### ISSUE TITLE
How to print dic with original order

### ISSUE THREAD

**Issue by sure00** [iit-cs579/main#276]
Hi professor and all
    My log shows the order of dict items is different what i ordered. Is that OK?

    dict = ({'punct':punct, 'features':features,'min_freq': min_freq, 'accuracy': mean})
        

best cross-validation result:
{'min_freq': 2, 'accuracy': 0.77000000000000013, 'punct': True, 'features': (<function token_pair_features at 0x0000017AE7F8FBF8>, <function lexicon_features at 0x0000017AE7F8FC80>)}

**Comment by viyatgandhi** [comment]
ya it is fine. dictionary can't be printed like and are not designed to maintain the order, you can use OrderedDict() instead but it is not meant to be used in a2, so it should be fine.
