### ISSUE TITLE
csr_matrix bug?

### ISSUE THREAD

**Issue by joezhang2** [iit-cs579/main#277]
I tried creating a sparse matrix using the sample from today's lecture notes but the graph that python prints is wrong. 

This is the code I tried running:
```
indptr = [0, 1, 2, 4]
indices = [0, 3, 0, 1, 0]
data = [1, 2, 1, 1, 1]
print(csr_matrix((data, indices, indptr)).toarray())
```

But my output is missing the last row:
```
[[1 0 0 0]
 [0 0 0 2]
 [1 1 0 0]]
```
When I try running it with the sample data from the documentation, the output was correct. Does anyone know why I'm missing the last row with this sample data?

**Comment by thirumalrao** [comment]
looks like you have interchanged row and column indices. per your code, try
print(csr_matrix((data, indptr, indices)).toarray())

**Comment by vjonnala** [comment]
Refer the documentation https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html
You did not include an indptr for 4th row. Try this:
indptr = np.array([0, 1, 2, 4,**5**])
indices = np.array([0, 3, 0, 1, 0])
data = np.array([1, 2, 1, 1, 1])

**Comment by joezhang2** [comment]
Thanks everyone!
