### ISSUE TITLE
Efficient way for csr_matrix

### ISSUE THREAD

**Issue by ranjeetkumar** [iit-cs579/main#279]
Out of two, which one is more efficient?

1) csr_matrix((data, (row_ind, col_ind)), [shape=(M, N)])
where data, row_ind and col_ind satisfy the relationship a[row_ind[k], col_ind[k]] = data[k].
2) csr_matrix((data, indices, indptr), [shape=(M, N)])
is the standard CSR representation where the column indices for row i are stored in indices[indptr[i]:indptr[i+1]] and their corresponding values are stored in data[indptr[i]:indptr[i+1]]. If the shape parameter is not supplied, the matrix dimensions are inferred from the index arrays.

**Comment by davidghiurco** [comment]
you're mixing apples and oranges here. As the professor discussed in class, CONSTRUCTING the csr_matrix requires a data array, and a corresponding row_idx and col_idx array. (your option #1)

Option #2 that you list is how CSR STORES the data that it was constructed with.

Long answer short: pass in the 3 arrays

**Comment by ranjeetkumar** [comment]
Thanks @davidghiurco  I have done by option 1.  I was just curious to know the difference b/w both options. We can also construct by option 2  that is not related to assignment. See the doc https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html

**Comment by davidghiurco** [comment]
I wasn't aware that you can construct it that way too. But to be honest option 1 is a lot friendlier on the eyes. I personally hate introducing levels of indirection unless they provide a significant benefit.

**Comment by ranjeetkumar** [comment]
@davidghiurco yes  it will cause more levels of indirection by option 2. In some cases, option 2 might be good option. Thanks for your input.
