### ISSUE TITLE
more tokenization test cases

### ISSUE THREAD

**Issue by aronwc** [iit-cs579/main#280]
Here are a couple more test cases to consider for tokenization.
```python
>>> tokenize("??necronomicon?? geträumte sünden.<br>Hi", True)
array(['necronomicon', 'geträumte', 'sünden.<br>hi'], 
      dtype='<U13')
>>> tokenize("??necronomicon?? geträumte sünden.<br>Hi", False)
array(['necronomicon', 'geträumte', 'sünden', 'br', 'hi'], 
      dtype='<U12')
```

**Comment by davidghiurco** [comment]
I pass these tests too but mean_accuracy_per_setting still different :( Starting to think I should try running my solution on different machines to see output.

**Comment by aronwc** [comment]
I wouldn't spend all day getting the outputs to match exactly.
