### ISSUE TITLE
Need help with eval_all_combinations accuracy

### ISSUE THREAD

**Issue by Kirubakumaresh** [iit-cs579/main#281]
My scores are not matching with the Log output.  I tested tokenize with the new cases shared by professor. Doc test passed. All done but output not matching.
The issue could be in tokenize/min_freq/token_pair. Need your help in this.

If it is OK to share, Can someone put the below debugging line inside the eval_all_combinations loop and share me the output. This would help me in nailing down the module to focus on.

#Please change as per your naming convention.
print("eval_all_combinations:fn={},punct={},acc={},min_freq={},shape={}".format(fn,punct,accuracy,min_freq,X.shape))

Sample output:
eval_all_combinations:fn=(function token_features at 0x00000229C5954D90,),punct=True,acc=0.6950000000000001,min_freq=2,shape=(400, 5170)
eval_all_combinations:fn=(function token_pair_features at 0x00000229C2E788C8,),punct=True,acc=0.7275,min_freq=2,shape=(400, 59797)
eval_all_combinations:fn=(function lexicon_features at 0x00000229C2E78AE8,),punct=True,acc=0.6475,min_freq=2,shape=(400, 2)
eval_all_combinations:fn=(function token_features at 0x00000229C5954D90, function token_pair_features at 0x00000229C2E788C8),punct=True,acc=0.725,min_freq=2,shape=(400, 64967)
............etc

**Comment by davidghiurco** [comment]
As discussed in class, accuracies will never match 100% on the dot. Floating point manipulations vary based on machine architecture. As long as your accuracies are reasonably close to Log.txt you should be fine

**Comment by AndrewLu1992** [comment]
What is the k number in your cross_validation function?
change the # of k to see if it still mismatches the log result
