### ISSUE TITLE
Issue in top_coefs

### ISSUE THREAD

**Issue by vmanikes** [iit-cs579/main#282]
Hello,
Do we need to map the `coefs` and `vocab` in the same way below:
`coeffs = [[1,2,3,-4,-5,-6]]`
`vocab = {a:0,b:1,:c:3,d:4,e:5,:f:6}`
to
`result = [(a:1),(b:2),(c:3),(d:-4),(e:-5),(f:-6)]`

Am I doing it right?
and how to classify into positive and negative words?

**Comment by davidghiurco** [comment]
I have the same problem. I can get all the coefficients using coef_ but I'm not sure about the internals of this attribute and have no idea how to use it

**Comment by vjonnala** [comment]
You need to sort the coefficients in descending order and then map the top n coefficients with their feature name found in the vocab.

**Comment by cicirao** [comment]
How many lists do you guys have in your clf.coef_? I've only got one. 
However, through L11.ipynb, there are three. I wonder what makes the difference. Because this can affect the negative and positive words. How can I fix it?

**Comment by vmanikes** [comment]
`      label...1 or 0; if 1, return the top coefficients
              for the positive class; else for negative.`

Does it mean that if label = 1 we need to put the top n values and if it is 0 then we need to put the last n values ?

**Comment by aronwc** [comment]
@cicirao In L11, there were three classes, so `coef_` is a matrix. In this assignment, there are only two classes, so only one array is needed (positive values correspond to features predictive of class 1; negative values correspond to features predictive of class 0).

@vmanikes Yes, making sure to sort properly.

**Comment by vmanikes** [comment]
`      label...1 or 0; if 1, return the top coefficients
              for the positive class; else for negative.`

Does it mean that for 1 we need to return the top n values and for 0 we need to return the last n vales?

**Comment by cicirao** [comment]
@aronwc I see. Thank you!

**Comment by ddabhane** [comment]
Do we need to sort vocab because since it is a dictionary every time we run the code the sequence will change?

**Comment by davidghiurco** [comment]
Yeah thats what I did and i'm getting correct output. Need to convert
negative coefficients to absolute value though to match Log.txt putput
