### ISSUE TITLE
log file appears wrong

### ISSUE THREAD

**Issue by vchariharan** [iit-cs579/main#283]
Below is text from log file:
TOP COEFFICIENTS PER CLASS:
negative words:
neg_words: 0.66113
token_pair=the__worst: 0.37465
token_pair=is__so: 0.31499
token_pair=about__the: 0.30307
token_pair=like__a: 0.27059

positive words:
pos_words: 0.52554
token_pair=it__is: 0.24468
token_pair=a__lot: 0.21013
token_pair=to__find: 0.20849
 token_pair=the__and: 0.20232

As it can be see, the token pair between a and b should be token_pair=a_b and npt b_a.. Elements to be arranged alphabetically(As given in token_pair function description). Then how is such outputs possible?
token_pair=it__is: 0.24468
token_pair=the__and: 0.20232
token_pair=to__find: 0.20849
token_pair=like__a: 0.27059

If its not correct, can you please share the latest log because, if any issue in token_pair, the effort would be propagating to all other functions.

**Comment by viyatgandhi** [comment]
what I understood, it does not say alphabetical order:

>  Note that the order of the tokens in the feature name
>     matches the order in which they appear in the document.
>     (e.g., a__b, not b__a)

Example itself is alphabetical order that is why it is a_b and not b_a
so if example is [d,b,a,f] then it would be  [d,b,a] and [b,a,f] so d__b, d__a and b__a

Hope it is helpful.

**Comment by aronwc** [comment]
Right, what @viyatgandhi says.

**Comment by vchariharan** [comment]
@aronwc @viyatgandhi i understood. Please let me know if my understanding below is correct?

feats = defaultdict(lambda: 0)
token_pair_features(np.array(['a', 'b', 'c', 'b','c','e']), feats)
sorted(feats.items())
Out[183]: 
[('token_pair=a__b', 1),
 ('token_pair=a__c', 1),
 ('token_pair=b__b', 1),
 ('token_pair=b__c', 4),
 ('token_pair=b__e', 1),
 ('token_pair=c__b', 2),
 ('token_pair=c__c', 1),
 ('token_pair=c__e', 1)]

Is the output correct?
