### ISSUE TITLE
token_pair_features consider pair of same element?

### ISSUE THREAD

**Issue by davidghiurco** [iit-cs579/main#285]
Should token_pair=a__a (or such entries) be included or excluded from consideration? The answer makes a difference in final accuracies for main() output. (And in my case at least, excluding pairs of the same entry actually raises the maximum accuracy by a bit to 0.78499999999999992 instead of 0.77000000000000013, and also increases the mean accuracies by a bit)

**Comment by cicirao** [comment]
I don't think so. I wonder if that would be a little overfitting?

**Comment by davidghiurco** [comment]
@cicirao what do you think? That we should KEEP token_pair=a__a or that we should NOT KEEP token_pair=a__a ....
I think we should not keep it because that sounds not right. But token_pair_features description does not specify whether same pairs should be kept or not. Need clarification from @aronwc

**Comment by cicirao** [comment]
I don't think we should include a_a. For me it's just making no sense. I'm thinking about classifying a twitter user. Using bio_bio as one pair just does not seem right.

**Comment by davidghiurco** [comment]
I agree. That's why I'm not sure what the behavior of the function should be because it's not stated. There are a few instances in the train data where the same token appears twice in the same window and so token_pair=a__a is added as a feature.

**Comment by cicirao** [comment]
Are you asking about in the token_pair, or in the actual generated pairs? My answer to the first would be not include, and for the second is include as it generates.

**Comment by cicirao** [comment]
* token_pair function

**Comment by davidghiurco** [comment]
well if token_pair_features() does not add token_pair=a__a to feats then it will not be generated it will be ignored. I'm not sure what you're asking

**Comment by cicirao** [comment]
For [a,b,c], the token_pair_features() return a_b, b_c, a_c.  In this case, it does not return a_a or b_b or c_c. This is what I said in the function, a_a is not included. 
But for a special list [a,b,a], the same function can return a_b, b_a, a_a. The a_a here is generated but not on purpose set in the function.

**Comment by davidghiurco** [comment]
yes I'm asking about instances such as [a, b, a]. should token_pair=a_a be a part of the returned features? That's what is not clear about token_pair_features() description

**Comment by cicirao** [comment]
Yeah. OK, in this way I think just leave a_a as it generates. If one word appears multiple times in one text, if should have more weight than other words. In fact, for [a,a,a], it returns a_a, a_a,a_a. It makes sense since a appears a lot of times.

**Comment by aronwc** [comment]
Yes:
```python
>>> feats = defaultdict(lambda: 0)
>>> token_pair_features(['a', 'b', 'a'], feats, 3)
>>> feats.items()
dict_items([('token_pair=a__a', 1), ('token_pair=a__b', 1), ('token_pair=b__a', 1)])
```

Sentences that repeat words are different from those that don't, so this feature attempts to capture that.
