### ISSUE TITLE
params for read_data

### ISSUE THREAD

**Issue by vmanikes** [iit-cs579/main#286]
Hello,
While doing parse test data will the parameter for the `read_data()` method will be same as the one written in main method?

**Comment by cicirao** [comment]
Change "train" to "test". You can check the actual download file for file name.

**Comment by vmanikes** [comment]
Thank you @cicirao

**Comment by ddabhane** [comment]
Do we need to sort vocab because since it is a dictionary every time we run the code the sequence will change?
