### ISSUE TITLE
Issue in Vectorize in sparse matrix

### ISSUE THREAD

**Issue by vaibhavaggarwal96** [iit-cs579/main#287]
Failed example:
    X.toarray()
Expected:
    array([[1, 0, 1, 1, 1, 1],
           [0, 2, 0, 1, 0, 0]], dtype=int64)
Got:
    array([[1, 0, 1, 1, 1, 1],
           [0, 2, 0, 1, 0, 0]], dtype=int32)

getting this issue. Can someone tell me the difference in int32 and int64 and how to resolve it.

**Comment by davidghiurco** [comment]
pass dtype=int64 as argument to building your csr_matrix

**Comment by vaibhavaggarwal96** [comment]
thanks
