### ISSUE TITLE
doctest: "Using the vocabulary fit to the training data, read"??

### ISSUE THREAD

**Issue by cicirao** [iit-cs579/main#290]
I run each doctest and it was fine. But when I tried to run all, it appeared an error. It seems to be something related to the first sentence of parse_test_data function. How can I fix it? I don't want to ruin the instruction : P.
![screen shot 2016-10-20 at 21 50 02](https://cloud.githubusercontent.com/assets/3103675/19585146/accee25e-970f-11e6-980c-164f669a9222.png)

**Comment by aronwc** [comment]
Ah, that's a quirk of nosetests -- it searches for all functions with "test" in their name and runs them as if they are a test. In this case, it thinks`parse_test_data` is a test function, so it tries to call it, with no parameters.

Workaround: ` python -m doctest a2.py`

**Comment by cicirao** [comment]
Oh! Haha. Thanks.
