### ISSUE TITLE
ValueError: Found array with 0 feature(s) (shape=(1, 0)) while a minimum of 1 is required.

### ISSUE THREAD

**Issue by hegdenagaraj4** [iit-cs579/main#292]
I am not sure why this error. I understand that my vocab has no element in this case. I am not sure what needs to be done. If I use try and except and ignore the error then I get an Attribute error: LogisticRegression has no attribute coef_ in top_coefs. I am not sure if these are two separate errors or corelated.

**Comment by ClaytonTurner** [comment]
try except is effectively going to skip over your try code which is going to cause more (and likely different issues) down the line. You really need to handle the bug where it's happening.

Try printing out your parameters and their sizes to see if maybe you aren't populating your variables. It's hard to tell what may be happening with just this little bit.

**Comment by hegdenagaraj4** [comment]
Thanks @ClaytonTurner  I fixed it. thank you
