### ISSUE TITLE
'Pos/Neg_words' doesn't appear in top_coefs at all

### ISSUE THREAD

**Issue by JianweiQ** [iit-cs579/main#293]
My output of top_coefs is totally different from the log.txt, and the coefficients of 'neg_words' and 'pos_words' are very small. The output is as follows. I've been working on this bug for the whole night... Does anyone have the same issue? What could be the possible reasons? Thanks!

TOP COEFFICIENTS PER CLASS:
negative words:
token_pair=and__their: 0.64848
token_pair=and__suddenly: 0.37228
token_pair=would__rate: 0.31407
token_pair=movie__then: 0.29866
token_pair=my__seat: 0.29152

coef of 'neg_words' is -0.019345    #output by myself

positive words:
token_pair=who__made: 0.52684
token_pair=are__with: 0.24772
token_pair=see__new: 0.20754
token_pair=of__plot: 0.20726
token_pair=unique__and: 0.20051

coef of 'pos_words' is 0.026725    #output by myself

**Comment by joezhang2** [comment]
The pos_word and neg_words are calculated in the lexicon_features function. Assuming that function works as intended, the next place I would look at is your best_fits_classifier to check that lexicon_features appears within the best_results for features. 

If it does not appear there, I would look into your eval_all function and check you are looping through the parameters correctly.

**Comment by changediyasunny** [comment]
@JianweiQ  Look into  #282 . hope t helps. I am also trying same.

**Comment by JianweiQ** [comment]
Thanks for your reply. However, lexicon_features does appear in my best_results (as below), and in fact 'neg_words'/'pos_words' do exist in the feature list as I can output their coefficients.

best cross-validation result:
{'features': (<function token_pair_features at 0x11332fb70>, <function lexicon_features at 0x11332fd08>), 'accuracy': 0.77249999999999996, 'punct': True, 'min_freq': 2}
worst cross-validation result:
{'features': (<function lexicon_features at 0x11332fd08>,), 'accuracy': 0.64749999999999996, 'punct': True, 'min_freq': 10}

**Comment by JianweiQ** [comment]
I figured that out. The problem occurred when I transform a dict into an array: feat_names=[fn for fn,c in vocab.items()].  I thought the order of items will be preserved.

Thank you guys!
