### ISSUE TITLE
Min_freq Worstcase Log.txt

### ISSUE THREAD

**Issue by saurabhsawhney** [iit-cs579/main#294]
best cross-validation result:
{'punct': True, 'accuracy': 0.77000000000000013, 'features': (<function token_pair_features at 0x0000029BC1264BF8>, <function lexicon_features at 0x0000029BC1264C80>), 'min_freq':
2}
worst cross-validation result:
{'punct': True, 'accuracy': 0.64749999999999996, 'features': (<function lexicon_features at 0x0000029BC1264C80>,), 'min_freq': **10**}

LOG.TXT
best cross-validation result:
{'features': (<function token_pair_features at 0x114172c80>, <function lexicon_features at 0x114172d08>), 'punct': True, 'accuracy': 0.77000000000000013, 'min_freq': 2}
worst cross-validation result:
{'features': (<function lexicon_features at 0x114172d08>,), 'punct': True, 'accuracy': 0.64749999999999996, 'min_freq': **2**}

In worst case, I am getting the right accuracy but min freq is 10 instead of 2 as there is a tie at 2,5 and 10 and we print the last value in main. Do we need to again sort on any criteria?

**Comment by davidghiurco** [comment]
This exact question has been asked before. Refer to #262
Short answer: This is expected and completely normal.

**Comment by ClaytonTurner** [comment]
Thanks for referring this to the other issue @davidghiurco
