### ISSUE TITLE
TypeError: 'NoneType' object is not iterable in parse_test data

### ISSUE THREAD

**Issue by vmanikes** [iit-cs579/main#297]
When I am passing vocab to parse_test data and it is showing this error
`    X,vocab1 = vectorize(tokens_list_true,best_result['features'],best_result['min_freq'],vocab) `

Is there anything that need to be taken care in vectorize(vocab=None) type?

**Comment by vjonnala** [comment]
Try checking if your token_list is None or vectorize function loops over a non iterable object.

**Comment by ClaytonTurner** [comment]
Yeah, type-check all involved variables
