### ISSUE TITLE
Logistic Regression with cross validation

### ISSUE THREAD

**Issue by theTechie** [iit-cs579/main#298]
`ValueError: This solver needs samples of at least 2 classes in the data, but the data contains only one class: 1`

Anyone got this error ?

Looks like when i do cross-validation, the labels picked for training belong to the same class.

**Comment by ClaytonTurner** [comment]
print out your training/testing data to confirm this. It may be an issue previous to this causing this.

**Comment by theTechie** [comment]
There was a typo in my code which made me panic. I figured it out. Thanks !
