### ISSUE TITLE
top misclassified documents

### ISSUE THREAD

**Issue by thirumalrao** [iit-cs579/main#299]
I am doing clf.predict_proba on X_test to get predicted labels and compared it with test_labels. Don't see any difference... What should we compare test_label against ?

**Comment by vjonnala** [comment]
You need to compare test_labels with predicted test class labels and then sort in descending order of predicted probability of incorrect class.

**Comment by AndrewLu1992** [comment]
clf.predict_proba(X_test) returns the predicted conditional prob of predicted class for each record.
clf.predict(X_test) returns the predicted label.
Then you need to check which record is mispredicted and rank the mispredicted by prob in descending order.

**Comment by thirumalrao** [comment]
thanks @vjonnala @AndrewLu1992 

It was my bad.. I was doing a fit on test data before doing predict. That was causing the issue.

**Comment by Shringa13** [comment]
So, we have to calculate probability of only mispredicted values? how to relate  test_docs, mispredicted and predict_proba values?
