### ISSUE TITLE
Mean accuracy per setting

### ISSUE THREAD

**Issue by changediyasunny** [iit-cs579/main#300]
Hi Folks,
I am confused over how get such settings for " def mean_accuracy_setting()"?
As per Log.txt file, consider for example:    **min_freq=2: 0.72250**
how to get this setting ? what should be other parameters like **feature_fns, punct** for this setting?

I guess I am missing something important ?

**Comment by aronwc** [comment]
To compute `min_freq=2: 0.72250`, you average the accuracies for all settings where `min_freq=2`.

**Comment by vjonnala** [comment]
mean_accuracy_setting() takes "results" as an argument. Your results should contains all the parameters like accuracy, features, min_freq etc. For each setting, compute the mean accuracy for all combinations.

**Comment by changediyasunny** [comment]
Great. Got it. thanks @aronwc  @vjonnala
