### ISSUE TITLE
got this value error for clf.predict

### ISSUE THREAD

**Issue by hegdenagaraj4** [iit-cs579/main#301]
ValueError: X has 17880 features per sample; expecting 17653
Hello Clayton, 
Not able to understand the error. Is it because of a mistake in tokenize?Please help.
Thanks in advance.

**Comment by ClaytonTurner** [comment]
Is this your shape parameter causing the issue?

**Comment by AndrewLu1992** [comment]
This error means your logistic classifier is trained or set on something has 17653 features but you are using it on X.

**Comment by hegdenagaraj4** [comment]
@ClaytonTurner Yes .
Traceback (most recent call last):
  File "a2.py", line 742, in <module>
    main()
  File "a2.py", line 733, in main
    predictions = clf.predict(X_test)
  File "/home/raj/anaconda3/lib/python3.5/site-packages/sklearn/linear_model/base.py", line 268, in predict
    scores = self.decision_function(X)
  File "/home/raj/anaconda3/lib/python3.5/site-packages/sklearn/linear_model/base.py", line 249, in decision_function
    % (X.shape[1], n_features))
ValueError: X has 17880 features per sample; expecting 17653
 @AndrewLu1992 exactly. So does that mean i am returning more tokens ?

**Comment by AndrewLu1992** [comment]
@hegdenagaraj4  Have you set vocab parameter in vectorize function t0 the vocab that is the result from training X data? If not, then check you vectorize function if you handle the situations that vocab is passed in.

**Comment by hegdenagaraj4** [comment]
@AndrewLu1992  yes I handled the case of vocab. But I am getting the same error.

**Comment by pratik27shah** [comment]
Hi...what does handling of vocab case means..are we suppose to have the same number of entries for the dataset.....

**Comment by AndrewLu1992** [comment]
@pratik27shah @hegdenagaraj4  It is supposed to have the same # of features for both training and testing processed data. If vocabulary is passed into the vectorize function, it means that you do not to build one from token_list but directly use the vocab to build the frequency matrix and just return the vocabulary passed in.

**Comment by AndrewLu1992** [comment]
The vocabulary is supposed only to be built during model training, but do not rebuild it when testing against new data, instead use it directly to preprocess your testing data.

**Comment by hegdenagaraj4** [comment]
@AndrewLu1992 I followed the logic. I have updated my file. I am not building the vocabulary if it is passed , but the error is still seen. I will debug more.

**Comment by hegdenagaraj4** [comment]
Fixed it. Thanks.
