### ISSUE TITLE
mean_accuracy_per_setting

### ISSUE THREAD

**Issue by vinaykai** [iit-cs579/main#302]
Hi everyone,
this is my output for mean accuracy setting. It's not exactly matching the output for the log file as there might be some problem with the format. I believe the values are right it's just the format.
Can somebody please tell me where I might be wrong?

Mean Accuracies per Setting:
[(0.75166666666666659, (<function token_pair_features at 0x0000022746473158>, <function lexicon_features at 0x0000022746473BF8>)), (0.74291666666666678, (<function token_features at 0x00000227464730D0>, <function token_pair_features at 0x0000022746473158>, <function lexicon_features at 0x0000022746473BF8>)), (0.73249999999999993, (<function token_features at 0x00000227464730D0>, <function token_pair_features at 0x0000022746473158>)), (0.72999999999999998, (<function token_pair_features at 0x0000022746473158>,)), (0.72285714285714298, 2), (0.72011904761904755, 'False'), (0.71964285714285714, 5), (0.7086904761904762, 'True'), (0.70071428571428562, 10), (0.70041666666666658, (<function token_features at 0x00000227464730D0>, <function lexicon_features at 0x0000022746473BF8>)), (0.69208333333333349, (<function token_features at 0x00000227464730D0>,)), (0.65125, (<function lexicon_features at 0x0000022746473BF8>,))]
(<function token_pair_features at 0x0000022746473158>, <function lexicon_features at 0x0000022746473BF8>): 0.75167
(<function token_features at 0x00000227464730D0>, <function token_pair_features at 0x0000022746473158>, <function lexicon_features at 0x0000022746473BF8>): 0.74292
(<function token_features at 0x00000227464730D0>, <function token_pair_features at 0x0000022746473158>): 0.73250
(<function token_pair_features at 0x0000022746473158>,): 0.73000
2: 0.72286
False: 0.72012
5: 0.71964
True: 0.70869
10: 0.70071
(<function token_features at 0x00000227464730D0>, <function lexicon_features at 0x0000022746473BF8>): 0.70042
(<function token_features at 0x00000227464730D0>,): 0.69208
(<function lexicon_features at 0x0000022746473BF8>,): 0.65125

**Comment by vjonnala** [comment]
Output for mean_accuracy_per_setting() should be a list of (accuracy, setting) tuples. Since the function takes "results" as an argument and "results" contain accuracy, punct, feature names, min_freq, your output should contain these settings along with accuracy of that setting. Re-check "results" attributes.

**Comment by vinaykai** [comment]
Actually I'm facing the exact same problem mentioned in issue #268. But I'm not able to find out which keyword will be used.

**Comment by AndrewLu1992** [comment]
@vinaykai  Or you can establish a map to detect which setting it is as strings.

**Comment by vinaykai** [comment]
somewhere in eval_all_combinations or mean_accuracy_per_setting we must convert the function into it's names for the sake of displaying it similar to the log file. Does anyone know where exactly this must be performed?
Also we must store the different combinations for functions as a list right? So further when we need the function names we must iterate through them again right?

**Comment by AndrewLu1992** [comment]
@vinaykai use hashtable (dictionary in Python)
