### ISSUE TITLE
import scipy

### ISSUE THREAD

**Issue by yteng2** [iit-cs579/main#303]
I'm not sure what the reason is, but i have to import scipy  to let scipy.sparse.csr_matrix working. Other wise i will get an Name error: name 'scipy' is not defined. since professor noted that no imports allowed besides. is it ok to import scipy?

**Comment by AndrewLu1992** [comment]
from scipy.sparse import csr_matrix, the csr_matrix is already imported.
You can directly use csr_matrix without "scipy.sparse."

**Comment by yteng2** [comment]
problem sloved, thanks
