### ISSUE TITLE
plot_sorted_accuracies

### ISSUE THREAD

**Issue by vaibhavaggarwal96** [iit-cs579/main#304]
what we have to generate a graph on the basis of accuracy and setting. But i don't understand how to map accuracy with setting and what does this setting signisfy

**Comment by vjonnala** [comment]
As far as I understood,
"results" returned from eval_all_combinations() should have an attribute accuracy. You need to plot graph by sorting ['accuracy'] in "results".

**Comment by AndrewLu1992** [comment]
You can use strings to represent each combination of settings. In the graph, setting is index of each combination in your result list sorted according to accuracy.
