### ISSUE TITLE
Cross Validation Accuracy

### ISSUE THREAD

**Issue by Sand567** [iit-cs579/main#305]
Hi,

I am seeing an error when I am trying to call cross validation accuracy from eval all combinations saying 

C:\Users\Sandeep\Anaconda3\lib\site-packages\scipy\sparse\csr.py in check_bounds(indices, N)
    235             max_indx = indices.max()
    236             if max_indx >= N:
--> 237                 raise IndexError('index (%d) out of range' % max_indx)
    238 
    239             min_indx = indices.min()

IndexError: index (399) out of range

Would anyone of you please help?

**Comment by AndrewLu1992** [comment]
You need to provide more info.

**Comment by Sand567** [comment]
As per the professor's code the KFold takes in n=len(labels),nfolds=k. But When i trying to find out the combinations of features, we would need to make a call to cross validation accuracy to get the accuracy score.

Here what I doing here is ..
>>>docs, labels = read_data(os.path.join('data', 'train'))
>>>feature_fns = [token_features, token_pair_features, lexicon_features]
>>>eval_all_combinations(docs,labels,[True,False],feature_fns,[2,5,10])

When I try to do this I see the below error

C:\Users\Sandeep\Anaconda3\lib\site-packages\scipy\sparse\csr.py in check_bounds(indices, N)
235 max_indx = indices.max()
236 if max_indx >= N:
--> 237 raise IndexError('index (%d) out of range' % max_indx)
238 
239 min_indx = indices.min()

IndexError: index (399) out of range

**Comment by Sand567** [comment]
I tried printing the len(labels) it shows 400

**Comment by AndrewLu1992** [comment]
what is your parameters used to call the cross_validation_accuracy function?

**Comment by Sand567** [comment]
cross_validation_accuracy(clf, X, labels, k)
clf - LogisticRegression() classifier
X - csr matrix
labels - list of ints, 1=positive, 0=negative label
k - nfolds

**Comment by AndrewLu1992** [comment]
I mean your real solid parameters.

**Comment by Sand567** [comment]
X - got from calling Vectorize
labels - got from the main method
clf - LogisticRegression()
k - 5

**Comment by Sand567** [comment]
These are what I am passing to the function cross_validation_accuracy() . ABOVE

**Comment by AndrewLu1992** [comment]
Then your bug probably hidden in vectorize function.

**Comment by Sand567** [comment]
The Doctests pass for the dataset given but how would I find out where would the error lie in this huge data set ?

**Comment by AndrewLu1992** [comment]
Dataset is always correct.

**Comment by AndrewLu1992** [comment]
Dataset is always correct.
