### ISSUE TITLE
MISCLASSIFIED TEST DOCUMENTS Output Issue

### ISSUE THREAD

**Issue by pratik27shah** [iit-cs579/main#306]
The output for missclassified documents is coming
at number 3
truth= 1 predicted= 0 proba= 0.989929626199
Being a freshman in college.........

and this comes at number 4
truth= 1 predicted= 0 proba= 0.989907834012
In defense of this movie.........................................

but the professor's log shows the output the other way around..so is this acceptable,as the change of order is due to proba and that keeps differing from system to system.

**Comment by shorabhd** [comment]
same issue!

**Comment by AndrewLu1992** [comment]
I doubt there could be any difference if you have implemented all correctly. The factors that affect the ranking is a lot. Double check vectorize, tokenize and fit_best_classifier functions.

**Comment by AndrewLu1992** [comment]
And check if you followed ranking logic described in #311 and #309
