### ISSUE TITLE
#299 continuation 

### ISSUE THREAD

**Issue by Shringa13** [iit-cs579/main#309]
So, we have to calculate probability of only mispredicted values? how to relate test_docs, mispredicted and predict_prob values?

**Comment by joezhang2** [comment]
You can get a matrix of the probabilities for each class, 0 and 1 (predict_prob values) and you can also get a matrix for the what the classifier predicts, this is covered in the discussion under #309.

Once you have those two, compare the predictions with the labels to find which predictions are wrong and save the index of those wrong predictions. Then look up the probabilities of the wrong predictions. 

Ex. Say the correct labels are [0,0,1,1] and our predictions are [1,0,1,0] and the probabilities are [((0,.3), (1, .7)), ((0,.8), (1, .2)), ((0,.15), (1, .85)), ((0,.99), (1, .01)) ]

We compare and find we improperly classified documents 1 and 4, so look up the those two probabilities: ((0,.3), (1, .7)) and ((0,.99), (1, .01)). We thought document 4 was class 0 with a probability of .99 and we thought document 1 was class 1 with a probability of .7. 
We can rank them to get (document 4, document 1) and now we can look up the test_docs to get the raw strings for those 2 documents.

**Comment by AndrewLu1992** [comment]
@joezhang2  Well done.

**Comment by Shringa13** [comment]
Thank you @joezhang2  and @AndrewLu1992
