### ISSUE TITLE
parse_test_data() non-existant doctest failing?!?!?

### ISSUE THREAD

**Issue by davidghiurco** [iit-cs579/main#310]
Running each individual doctest separately passes. Running the entire script also gives expected output. But if I run the following:

david@MSI-GT72-2QE ~/Desktop/cs579/a2 $ nosetests --with-doctest a2.py
E......
======================================================================
ERROR: Using the vocabulary fit to the training data, read
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/david/anaconda3/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
TypeError: parse_test_data() missing 2 required positional arguments: 'best_result' and 'vocab'

----------------------------------------------------------------------
Ran 7 tests in 0.006s

FAILED (errors=1)

I don't understand how I can fail a doctest that is non-existant? How can this be happening. I have not added absolutely any doctests of my own. Only ones are the professor's?

**Comment by AndrewLu1992** [comment]
I think it probably some issues in nosetests and your command typed in bash. Maybe you can try other options in addition to --with-doctest. As long as you can run script and get expected output, it is sufficient for this assignment.

**Comment by cicirao** [comment]
I asked this question. See issue #290 https://github.com/iit-cs579/main/issues/290

**Comment by davidghiurco** [comment]
@cicirao tha makes sense now. Thank you for refering that issue.
