### ISSUE TITLE
ValueError: Found array with (0) features

### ISSUE THREAD

**Issue by Smrutipatel14** [iit-cs579/main#313]
I get error like below @vjonnala this happens in fit_best_accuracy()
![unnamed](https://cloud.githubusercontent.com/assets/14853001/19621912/608db0ce-9862-11e6-99a5-501b4e9d422b.png)

**Comment by vjonnala** [comment]
Try checking the feature names passed to the vectorize() function.

**Comment by Smrutipatel14** [comment]
Fixed
