### ISSUE TITLE
Token pair features is causing vectorize to run for long in eval_all_combinations method.

### ISSUE THREAD

**Issue by ishujaswal** [iit-cs579/main#314]
When I try to run my code for eval_all_combinations without including token_pair_features i.e. 
feature_fns = [token_features, lexicon_features]
my code is running faster as compared to when included token pair features( where my code goes to infinite loop and run for very long; couldn't even calculate)

Can anyone help me with this? How can I improve the efficiency for token pair feature method?

**Comment by vjonnala** [comment]
Could you please check your loops in token_pair_features() by unit testing i.e., running the method on small data and check if it is fine.

**Comment by Tsreenivasan** [comment]
Mine too, with over 13 million tokens being generated in this function, use of multiple looping constructs is hurting the performance of the Program.

Try to change the logic of the pair finder, perhaps use Indices over multiple loops?
meaning, try to avoid the iteration when u'll end up not finding a writable token in your loops.

**Comment by shalinchopra** [comment]
You can first check if the windows (as mentioned in the token_pair_features) are getting generated properly. If that's fine then generating pair of tokens from those windows won't take much time as you can use itertools.combinations() functionality which will help you to generate the required pair of tokens.

**Comment by sandeep-17IIT** [comment]
windows is not imported.. can we write new imports??

**Comment by vjonnala** [comment]
windows is not an import. Its a size of interval we need to take. Refer token_pair_features() documentation for the details(windows).

**Comment by sandeep-17IIT** [comment]
i was thinking about sliding_windows in python... however using index & list slicing i manage to get the right result for doc test ... this still requires 2 loops at min regardless any method ..

**Comment by ishujaswal** [comment]
Hey,

Thanks for your help. But, i did not get your point. Can you please explain
a bit.

In my code, I am using combinations method to find the combinations and
iterating over it.
Not sure how can I remove the iteration

-Ishu
