### ISSUE TITLE
ValueError: X has 17064 features per sample; expecting 16640 

### ISSUE THREAD

**Issue by kartikaygautam** [iit-cs579/main#316]
<img width="673" alt="screen shot 2016-10-22 at 8 38 08 pm" src="https://cloud.githubusercontent.com/assets/21162800/19623649/7fcc6aa4-9897-11e6-9885-2d2f5d1044a9.png">
<img width="727" alt="screen shot 2016-10-22 at 8 38 15 pm" src="https://cloud.githubusercontent.com/assets/21162800/19623650/7fd1751c-9897-11e6-80f9-8b4f268efd2a.png">

**Comment by AndrewLu1992** [comment]
This probably caused by you refit the model on testing data.
Double check if you handle the case that vocab != None. Refer to #312

**Comment by kartikaygautam** [comment]
Yo ma man, Thanks a ton ! ! ! i had totally forgotten about that ! had to write 3 lines and all works perfectly !!! time to submit \m/

**Comment by mamun-cse-diu** [comment]
tf_transformer_bin = TfidfTransformer(use_idf=True).fit(X_train_tok)
X_train_tf = tf_transformer_bin.transform(X_train_tok)
X_test_tf = tf_transformer_bin.transform(X_test_tok)

print(X_test_tf[0,:])

-----------------

ValueError                                Traceback (most recent call last)

<ipython-input-215-ce85d9944e43> in <module>
      1 tf_transformer_bin = TfidfTransformer(use_idf=True).fit(X_train_tok)
      2 X_train_tf = tf_transformer_bin.transform(X_train_tok)
----> 3 X_test_tf = tf_transformer_bin.transform(X_test_tok)
      4 
      5 print(X_test_tf[0,:])

2 frames

/usr/local/lib/python3.8/dist-packages/sklearn/base.py in _check_n_features(self, X, reset)
    398 
    399         if n_features != self.n_features_in_:
--> 400             raise ValueError(
    401                 f"X has {n_features} features, but {self.__class__.__name__} "
    402                 f"is expecting {self.n_features_in_} features as input."

ValueError: X has 4209 features, but TfidfTransformer is expecting 7478 features as input.
