### ISSUE TITLE
Pushing Changes to Git

### ISSUE THREAD

**Issue by RittickDatta** [iit-cs579/main#317]
When I am pushing my changes, my final accuracies.png is not getting pushed.

I get a message that my folder is up to date with master repo.

Any ideas?

**Comment by AndrewLu1992** [comment]
Have you added your accuracies.png to stage?

**Comment by RittickDatta** [comment]
In my plot accuracies method, i had created file with name as "accuracies" and format as PNG. I think i pushed an earlier version along with a2.py and when i checked now, it was not the final accuracies.png

**Comment by AndrewLu1992** [comment]
Maybe you are in the different branch? Check if your current branch is where you modified the png picuture

**Comment by RittickDatta** [comment]
I got it, it is saved as a binary file but can be viewed. ("accuracies")

But my folder also contains the original accuracies.png when the assignment was first posted.

**Comment by ClaytonTurner** [comment]
You can change that by just modifying the extension on the end of it (like appending ".png" to the end of the filename)

**Comment by RittickDatta** [comment]
I am specifying the format as PNG and filename as "accuracies". Yet a binary file is created. Should i keep the name as "accuracies.png" ?

**Comment by AndrewLu1992** [comment]
I think you should.

**Comment by RittickDatta** [comment]
It worked, thanks guys.
