### ISSUE TITLE
Lecture 18, Slide 18

### ISSUE THREAD

**Issue by RittickDatta** [iit-cs579/main#318]
For TF equation, is the following understanding of the denominator correct?

It is the maximum frequency of an item k in the jth doc.

For each other document, there will be a different item k with the highest frequency for that other document.

**Comment by ClaytonTurner** [comment]
I believe term frequency is when referring to a single document.

"This is a sentence containing the word this"

Here, this appears 2 times out of a total 8 words so the term frequency would 2/8 (1/4)

The example section on the wikipedia page for tf-idf does a good job of breaking this down: https://en.wikipedia.org/wiki/Tf%E2%80%93idf

**Comment by aronwc** [comment]
Correct.

**Comment by RittickDatta** [comment]
Thanks Clayton.
