### ISSUE TITLE
Issue in featurize()

### ISSUE THREAD

**Issue by ddabhane** [iit-cs579/main#319]
What does a document in this context imply?
Is it a movie title, movie genre or a entire row of movie data frame?
Is num_features, the number of terms in the doc?

Can someone elaborate what this function does?

**Comment by gershwinlover** [comment]
I think it's genre.

**Comment by gershwinlover** [comment]
I'm more curious about why it is used like this "movies, vocab = featurize(movies)" in the main...

**Comment by ddabhane** [comment]
@gershwinlover exactly I was thinking about it too because its just returning movies data frame and don't know where that vocab is coming from.

**Comment by hegdenagaraj4** [comment]
Please correct me if I am wrong, genres is tokenized before. Now I am confused with tf(i,d), i being the frequency of the term in document d where document is a movie. So if I have [action, comedy,thriller] then the frequency of [action] would it be 1 or do I have to calculate it across all of the document? check for the number of times the word [action] appears in the "movies" and then take the frequency?

**Comment by aronwc** [comment]
In your example, tf(action, d) =1

**Comment by hegdenagaraj4** [comment]
Thank you Professor.

**Comment by ddabhane** [comment]
So the document for each movie is the list of genre(tokens) associated with it and num_features is the number of genres in that list. So in the above example num_features will be 3. If I am right then tf(genre, d) will always be 1 because all docs have genres where each of them appears only once.

Am I right?

**Comment by aronwc** [comment]
- num_features is the total number of unique features across all documents.
- tf(genre,d) may or may not always be one in this dataset, but you shouldn't assume it.

**Comment by RittickDatta** [comment]
@aronwc feature Is feature, a token from the list, for each row in movies['tokens'] ?

**Comment by ddabhane** [comment]
@RittickDatta Yes, I think you are right and the list is the doc for each movie

**Comment by RittickDatta** [comment]
@ddabhane @aronwc Do we have to include tokens from the title in this list? I am assuming that we don't have to include it.

**Comment by aronwc** [comment]
No, just the genres.

**Comment by ddabhane** [comment]
@aronwc Some movies do not have genres, hence they have (no genres listed) under the genres header. In this case the tokenize_string() is creating tokens like ['no', 'genres', 'listed']. So I assume we do not have to consider these tokens as features. Am I doing right? 
If yes then what will be content of CSR matrix for these movies without any genre?

**Comment by aronwc** [comment]
I'd just leave those tokens. So, it will be ['no', 'genres', 'listed']

**Comment by vmanikes** [comment]
So professor can you explain in the `max(k,d)` 

1. what would be `k`, it is mentioned that it can be any term, so how can I pick that, For example, for the movie `Batman` its genre is `[comedy,romance,sci-fi]` what could be the `k` from this. 
2. Does `d` would be all documents or a single doc.

**Comment by aronwc** [comment]
if a document's tokens are [comedy, comedy, comedy, horror], then max_k tf(k, d) is 3. It asks: what is the frequency of the most common term in this document.

This is for a single doc.

**Comment by ddabhane** [comment]
@aronwc There is no such case where the tokens in a document are repeating like the example you mentioned earlier. Each document has unique tokens. 
So will max_k tf(k, d) will always be 1 for dataframe we are using in the assignment?

**Comment by cwang90** [comment]
If there is a movie which has genre like Horror|Horror, in tokenize function, the corresponding column content should be [horror] or [horror, horror]?

**Comment by ddabhane** [comment]
@cwang90 According to me it will be  [horror, horror].

**Comment by aronwc** [comment]
Correct; "Horror|Horror" will be tokenized to ['horror', 'horror']. featurize will then have one entry for horror, weighted according to the given tfidf formula.

**Comment by vmanikes** [comment]
@aronwc but how come a single movie have 2 same genres

**Comment by aronwc** [comment]
Please write the tokenize/featurize methods to be general for any string
input.

**Comment by vmanikes** [comment]
`[action, adventure, horror, sci-fi]` if the term is action,what would be `max(k,d)` because every term is repeated only once here

**Comment by aronwc** [comment]
1
