### ISSUE TITLE
Vocab in featurize

### ISSUE THREAD

**Issue by ranjeetkumar** [iit-cs579/main#321]
In featurize function, in doc it is written:
Returns:
      The movies DataFrame, which has been modified to include a column named 'features'.
Vocab is not mentioned there.
In main, we need to return vocab too.
So, I return a dictionary with key as all the unique combined features of all the documents and values starting from 0 to n in the ascending order of keys.

Output of this line "print(sorted(vocab.items())[:10])"  from main
I got something like this {action:0 , adventure: 1 ....}

Is this correct?

**Comment by aronwc** [comment]
You're right. I've added this missing documentation in the [latest commit](https://github.com/iit-cs579/assignments/commit/5c0b80d97b5b4ab8513f4bb3fc8a788482c2cd25). It now reads:

```
    Params:
      movies...The movies DataFrame
    Returns:
      A tuple containing:
      - The movies DataFrame, which has been modified to include a column named 'features'.
      - The vocab, a dict from term to int. Make sure the vocab is sorted alphabetically as in a2 (e.g., {'aardvark': 0, 'boy': 1, ...})
 ```

**Comment by ranjeetkumar** [comment]
Thanks a lot
