### ISSUE TITLE
positive restriction of cosine similarity

### ISSUE THREAD

**Issue by Neotrino** [iit-cs579/main#322]
In function make_predictions(), the requirement said that we must restrict this weighted average to movies that have a positive cosine similarity with movie i. But I think this cosine similarity should always be positive(it could be 0, but this won't affect the result), as it is defined as: dot(a, b) / ||a|| * ||b||, and members of a and b should be non-negative according to tfidf(i,d)  definition. Correct me, if I'm wrong.

**Comment by aronwc** [comment]
Yup, but please do the check anyway.

**Comment by Neotrino** [comment]
Thanks. Another issue is what if I'm predicting a movie's rating which has no one is similar to it. In other words, the movie I'm predicting share no common genres token with any movie that this user has rated before. This will result in all the cosine_similarities are zeros, thus all the weights are zeros. I found a such case while testing the movie dataset which caused me a divide by 0 error.

**Comment by AndrewLu1992** [comment]
I think if restricted to positive similarity , cosine similarity == 0 case should not be included. @Neotrino

**Comment by aronwc** [comment]
Actually, let's do something a little different @Neotrino.

I've clarified this in the [latest commit](https://github.com/iit-cs579/assignments/commit/543ed56d00a3a92353b6bfe62d421104d6090a09)

>  If there are no other movies with positive cosine similarity to use in the prediction, use the mean rating of the target user in ratings_train as the prediction.

**Comment by Neotrino** [comment]
Thanks.
