### ISSUE TITLE
vocab in featurize()

### ISSUE THREAD

**Issue by RittickDatta** [iit-cs579/main#323]
If we have two movies:

movie 1: ['action', 'comedy', 'horror']
movie 2: ['comedy', 'comedy']

For 'comedy', what will be value in vocab dictionary? 

Is it a count of 'comedy' across all documents or a count of the number of times it occurs in unique documents?

**Comment by vmanikes** [comment]
I guess it is `{action:0,comedy:1,horror:2}`. I followed the vocab creation similar to `a2`. Correct me if I am wrong

**Comment by RittickDatta** [comment]
Your values seem to be the index of items in movie 1.

**Comment by joezhang2** [comment]
I think @vmanikes is trying to say we want to add all the unique tokens into the vocab, so if we have:
`movie1: ['action', comedy', 'comedy]
movie2: ['horror', 'horror']
movie3: ['action', adventure']`
Our vocab would be {adventure:0, action:1, comedy:2, horror:3}

**Comment by RittickDatta** [comment]
@joezhang2 can you explain the value for adventure in the dictionary?
