### ISSUE TITLE
How to update the values of a CSR matrix?

### ISSUE THREAD

**Issue by kartikaygautam** [iit-cs579/main#325]
For example, Given a CSR matrix : - 

how do i multiply each value of the matrix by the minimum of the values in the row,
such that the original matrix now reflects the changes

basically this is a two part question, the first deals with manipulations and the second with the in-matrix update

**Comment by ClaytonTurner** [comment]
You kind of have to go in a roundabout way to do this. You can use a temporary second csr matrix for operations for speed. Looping, while easier, is going to take a real long time.

http://stackoverflow.com/questions/23973718/updating-elements-of-a-csr-matrix-in-python

**Comment by kartikaygautam** [comment]
Hey, i already found out a way around it through some idioms mentioned in the documentation. Forgot to close the issue. Thanks anyways though :D
