### ISSUE TITLE
TypeError: 'Series' object is not callable

### ISSUE THREAD

**Issue by RittickDatta** [iit-cs579/main#327]
movies["features"] is of type Series. Each row contains a csr_matrix. 

if I have the following:

movies[movies.movieId == 31]["features"] , how can i access the first row? I get an error saying 'Series' object is not callable

**Comment by Swapnil2095** [comment]
Same here.
@RittickDatta ;If u solved it , please let me know.

**Comment by RittickDatta** [comment]
Hi Swapnil,

I used iterrows() on the series object and fetched the data in movies['features']. It solves the issue.
