### ISSUE TITLE
Issue in featurize

### ISSUE THREAD

**Issue by pratik27shah** [iit-cs579/main#328]
The explanation states that "tf(i, d) is the frequency of term i in document d and    max_k tf(k, d) is the maximum frequency of any term in document d" So if I have a case where the genres is 
**Case1:  [Action|Romantic|Drama]**.So my calculations would be:
tf("Action",d)=1 (As action word occurs only once )
max_k tf(k, d) =1 as all the term are occurring  maximum only once.

Case2:  [Action|Romantic|Action] is the same word gets repeated twice.
tf("Action",d)=2 (As action word occurs only twice)
max_k tf(k, d) =2 as action occurs maximum times.

So is my understanding correct?

**Comment by ClaytonTurner** [comment]
Yes, your numbers are correct here, though in case2 you have written "(As action word occurs only **once**)" when I think you meant to write twice

**Comment by pratik27shah** [comment]
thanks...
