### ISSUE TITLE
Notebook Version Control 

### ISSUE THREAD

**Issue by benjaminwalters** [iit-cs579/main#33]
Is there a good way to see git diffs between commits when using an ipython notebook? It picks up a lot of metadata changes. And there is a lot of json that contains the code. A quick google search revealed a couple tools, but I'm wondering if you have any suggestions? Or if you would be opposed to us writing code in a separate file and placing the proper calls in the notebook?

**Comment by aronwc** [comment]
Yes, this is an unfortunate aspect of notebooks. I've looked at many of the workarounds people have suggested, but they seem like only partial solutions, so I haven't used them yet.

If you want to develop in a .py file and paste into the notebook, that's fine, though it sounds like a lot of cut and pasting. You might look into the [%edit](https://ipython.org/ipython-doc/dev/interactive/magics.html) magic.

**Comment by benjaminwalters** [comment]
I am going to check out this one: http://nbdiff.org/

Yeah. The copy and pasting is what I'm worried about. I think it might be easiest to place all the function calls in the beginning, edit in the .py file as I work, and then maybe paste the code in once it all works.
