### ISSUE TITLE
Issue for featurize Calculations

### ISSUE THREAD

**Issue by pratik27shah** [iit-cs579/main#331]
for calculting log10(N/df(i)) it states that  N is the number of documents (movies)
    df(i) is the number of unique documents containing term i.

So if I have a case [Action|Action |Comdey]-->Doc 1  [Action|Romantic]--->Doc 2
So df(i) for action should be N=2 (as 2 unqiue documents are there) and df(Actions)=3 (As Action occurs 2 times in Doc 1 and 2 times in Doc2).Is this the correct way ?

**Comment by vmanikes** [comment]
No 

> df(i) is the number of unique documents containing term i
 
Which means that in how many docs does action appear, it doesn't deal with the multiple occurrences of the word `action`.
I hope it clarifies
