### ISSUE TITLE
csr_matrix issue

### ISSUE THREAD

**Issue by vaibhavaggarwal96** [iit-cs579/main#333]
while inserting tfidf value in csr_matrix the value are implicitly coverts from float to int. Example tdidf value is 0.97 and is csr_matrix is represented as 0 and for tdidf value of 1.023 and in csr_matrix it get as 1. So it is okay or is something wrong ?

**Comment by Nirali28** [comment]
I guess you are converting it into int.
Remove dtype='int64' if you have added while creating csr_matrix.

**Comment by ishujaswal** [comment]
I agree with @Nirali28. It must have been getting converted while matrix creation.

**Comment by vaibhavaggarwal96** [comment]
And you know what? I agree with both of you. Thanks @Nirali28
