### ISSUE TITLE
What to do with extra doctests?

### ISSUE THREAD

**Issue by joezhang2** [iit-cs579/main#334]
For the assignment, I created additional unit tests to check my math/logic. I was wondering if we should leave them in a3.py or will that cause an issue when grading? 

I vaguely recall something being said in class about storing them in another file, but I am not too sure if that is the proper procedure

**Comment by ClaytonTurner** [comment]
This shouldn't cause issues as we just use your defined functions that were originally in the assignment for testing your code. It wouldn't hurt to remove them but I don't think it's an issue. Worst case scenario just backup the file with the extra unit test code and make a copy with all the functions we're testing and have it be the file we grade via name
