### ISSUE TITLE
In make_predictions function, will there be users in test data but not in train data?

### ISSUE THREAD

**Issue by cicirao** [iit-cs579/main#335]
will there be users in test data but not in train data?
I think it's possible. 
How do we deal with this kind of situation?

**Comment by vjonnala** [comment]
Please refer the documentation for the function. It says:
"   Using the ratings in ratings_train, predict the ratings for each
    row in ratings_test. "
So, user id's should be same in both the data sets and then make predictions based on the ratings given.

**Comment by cicirao** [comment]
@vjonnala I don't understand.
I know that we use the ratings in ratings_train to predict the ratings in ratings_test. But, it also says that we predict by using all ratings by user u. So it's still possible that user u is in test but not in train data.

**Comment by ranjeetkumar** [comment]
This is good question. In this assignment, data is such that we don't have such scenario. In real world scenario, this can happen. I am curious to know, how to handle this situation? One solution, I can think of finding the similar user and taking that user's rating. Anyways, we don't have to worry about that.

**Comment by aronwc** [comment]
Right, this shouldn't happen in this assignment.
