### ISSUE TITLE
Return value of Featurize

### ISSUE THREAD

**Issue by vmanikes** [iit-cs579/main#337]
In the `featurize` method it is mentioned that we have to return a` tuple` with `movies` dataframe and `vocab` (`tuple(movies,vocab)`) , But in the main method is expecting 2 return values from featurize `movies, vocab = featurize(movies)`.

**Comment by ranjeetkumar** [comment]
tuple takes only one argument. In your example, you are giving two. If you write like tuple((movie,vocab)) then it will be correct. 
We can do the same thing in different ways
1) return movies, vocab
2) return (movies,vocab)
3 return  tuple((movies,vocab))
