### ISSUE TITLE
Assignment 1

### ISSUE THREAD

**Issue by dmartiinez** [iit-cs579/main#34]
Sorry, I am a little confused, are we doing our coding inside the python notebook?

**Comment by prateekagrawal06** [comment]
yes... we r dng the coding in ipython notebook

**Comment by dmartiinez** [comment]
so, we open the file that prof gave up in

**Comment by dmartiinez** [comment]
never mind, I figured it out! Thanks!

**Comment by prateekagrawal06** [comment]
are u talking about the config settings??
