### ISSUE TITLE
make_predictions issue

### ISSUE THREAD

**Issue by vinaykai** [iit-cs579/main#340]
While calling the cosine_sim function I am getting this error:
KeyError: 26131

I am printing the cosine_sim every time it is calculated. It prints a couple hundred values before it shows this error. Did anyone get this error or does anyone know what might be the problem?

**Comment by pratik27shah** [comment]
your rows and columns are not of same length .but it would be nice if you provided the entire error log

**Comment by Tsreenivasan** [comment]
We need more on the logs to address this, are you sure all the the CSR matrixes have the same length? this is vital that they are accurate for every token and are the same length of your vocab.

**Comment by vinaykai** [comment]
This is the entire log:


---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
C:\Users\Ganesh\Anaconda3\lib\site-packages\pandas\core\series.py in __getitem__(self, key)
    582         try:
--> 583             result = self.index.get_value(self, key)
    584 

C:\Users\Ganesh\Anaconda3\lib\site-packages\pandas\indexes\base.py in get_value(self, series, key)
   1979             return self._engine.get_value(s, k,
-> 1980                                           tz=getattr(series.dtype, 'tz', None))
   1981         except KeyError as e1:

pandas\index.pyx in pandas.index.IndexEngine.get_value (pandas\index.c:3332)()

pandas\index.pyx in pandas.index.IndexEngine.get_value (pandas\index.c:3035)()

pandas\index.pyx in pandas.index.IndexEngine.get_loc (pandas\index.c:4018)()

pandas\hashtable.pyx in pandas.hashtable.Int64HashTable.get_item (pandas\hashtable.c:6610)()

pandas\hashtable.pyx in pandas.hashtable.Int64HashTable.get_item (pandas\hashtable.c:6554)()

KeyError: 26131

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-14-451204c3c143> in <module>()
    253 
    254 if __name__ == '__main__':
--> 255     main()

<ipython-input-14-451204c3c143> in main()
    234     ratings_train, ratings_test = train_test_split(ratings)
    235     print('%d training ratings; %d testing ratings' % (len(ratings_train), len(ratings_test)))
--> 236     predictions = make_predictions(movies, ratings_train, ratings_test)
    237     print('error=%f' % mean_absolute_error(predictions, ratings_test))
    238     print(predictions[:10])

<ipython-input-14-451204c3c143> in make_predictions(movies, ratings_train, ratings_test)
    202         for index2,row2 in ratings_train.iterrows():
    203             if(row2['userId']==user):
--> 204                 print("training",movies['features'][row2['movieId']])
    205                 print("test",movies['features'][movie])
    206                 cosim=cosine_sim(movies['features'][row2['movieId']],movies['features'][movie])

C:\Users\Ganesh\Anaconda3\lib\site-packages\pandas\core\series.py in __getitem__(self, key)
    610                                                              kind='getitem')
    611                 if type(new_key) != type(key):
--> 612                     return self.__getitem__(new_key)
    613                 raise
    614 

C:\Users\Ganesh\Anaconda3\lib\site-packages\pandas\core\series.py in __getitem__(self, key)
    581         key = com._apply_if_callable(key, self)
    582         try:
--> 583             result = self.index.get_value(self, key)
    584 
    585             if not lib.isscalar(result):

C:\Users\Ganesh\Anaconda3\lib\site-packages\pandas\indexes\base.py in get_value(self, series, key)
   1978         try:
   1979             return self._engine.get_value(s, k,
-> 1980                                           tz=getattr(series.dtype, 'tz', None))
   1981         except KeyError as e1:
   1982             if len(self) > 0 and self.inferred_type in ['integer', 'boolean']:

pandas\index.pyx in pandas.index.IndexEngine.get_value (pandas\index.c:3332)()

pandas\index.pyx in pandas.index.IndexEngine.get_value (pandas\index.c:3035)()

pandas\index.pyx in pandas.index.IndexEngine.get_loc (pandas\index.c:4018)()

pandas\hashtable.pyx in pandas.hashtable.Int64HashTable.get_item (pandas\hashtable.c:6610)()

pandas\hashtable.pyx in pandas.hashtable.Int64HashTable.get_item (pandas\hashtable.c:6554)()

KeyError: 26131

**Comment by shalinchopra** [comment]
@vinaykai 
---> print("training",movies['features'][row2['movieId']])
Here row2['movieId'] = 26131, 
so you are accessing , movies['features'][26131] i.e. get me the 'features' at row no. 26131 which is not present as our movies['features'] is of size len(movies) < 26131.
Instead you need to get the movies['features'] for the movieId = 26131.

I hope this helps.

**Comment by vinaykai** [comment]
@shalinchopra, thank you, I will try this

**Comment by kartikaygautam** [comment]
Wow @shalinchopra, you are so intelligent :P :P thanks for being there for us :D
