### ISSUE TITLE
UserWarning: Boolean Series key will be reindexed to match DataFrame index.

### ISSUE THREAD

**Issue by anushamrl** [iit-cs579/main#342]
My program is fetching the predictions and mean absolute error but I get a UserWarning in method make_predictions. Below is the complete warning statement.

UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  top_ratings = [ratings[ratings.userId==0][ratings.movieId == tmid]['rating'].iloc[0] for tmid in top_movie_ids]

I'm not sure why this warning is issued. Can this warning be ignored? Anybody else facing the same? 
Thanks.

**Comment by ClaytonTurner** [comment]
So I think this has to do with the left side of your boolean expression not using ".loc" - I feel like this can be ignored

http://stackoverflow.com/questions/29263506/python-pandas-data-frame-warning-suggest-to-use-loc-instead

**Comment by anushamrl** [comment]
Thankyou.
