### ISSUE TITLE
About Repeated Terms in CSR Matrix

### ISSUE THREAD

**Issue by linglei1134** [iit-cs579/main#343]
I have a question in featurize method.
Let's say a genre is 'Horror|Romance|Romance'
'Romance' occurred twice, so inside the csr-matrix, will the entry of 'Romance' needed to have tfidf multiplied by 2? Or still using the same tfidf?
For an example, tfidf('Romance', d) = 0.47, so what it appears in the entry of csr-matrix will it be 0.94 or 0.47? while 'Romance' occurred twice.
Though I tested it, it didn't affect the final output, but I still want to know.

**Comment by aronwc** [comment]
From the formula: 
> tfidf(i, d) := tf(i, d) / max_k tf(k, d) * log10(N/df(i))

In this example, `tfidf(romance, d) = 2 / 2 * log10(N/df(romance))`
and `tfidf(horror, d) = 1 / 2 * log10(N/df(horror))`

**Comment by Smrutipatel14** [comment]
@linglei1134 even though your genre appears twice, the tfidf value is calculated same both times, so there is no multiplication of values required. You just map this value to right genre column in your csr_matrix.
In your example, it will be 0.47 and not 0.94.

**Comment by linglei1134** [comment]
I forgot the calculation of tfidf has already considered the sum of data when creating the csr-matrix.
I got it now, thank you guys!
