### ISSUE TITLE
make_predictions returning an array of arrays.

### ISSUE THREAD

**Issue by ishujaswal** [iit-cs579/main#345]
I am getting an array of arrays as an output from make_predictions as shown below:

[array([[ 2.7945653]]), array([[ 2.62385286]]), array([[ 2.76558239]]), array([[ 4.24064843]]), array([[ 3.22115155]]), array([[ 4.11423684]]), array([[ 3.92040563]]), array([[ 3.98286924]]), array([[ 3.21565818]]), array([[ 3.32692774]])]

I have tried iterating over it and all other flattening methods to make a flat array list but nothing is working. Can anyone please help me with this?

**Comment by pratik27shah** [comment]
There is an error in the syntax of the dot product.You may have not used the values property of the csr matrix for multiplication

**Comment by KSP16SCM52J** [comment]
Just return the 0th index of the result of cosine similarity.

**Comment by Smrutipatel14** [comment]
@ishujaswal You are getting this error because output of your cosine_sim() is a 1x1 matrix. You need to use 0th index to get the value from this matrix.

**Comment by saurabhsawhney** [comment]
There is no error, use [0][0] index of what u return from cosine function.

**Comment by ishujaswal** [comment]
@pratik27shah @KSP16SCM52J @Smrutipatel14 @saurabhsawhney  Thank you guys.. It's working fine now :)
