### ISSUE TITLE
'location' in a tweet

### ISSUE THREAD

**Issue by RittickDatta** [iit-cs579/main#349]
I have a tweet and when I view the details of the tweet, I can see the field 'geo_enabled' set to true and 'location' set to 'New York'.

But when I view tweet.keys(), 'location' and 'geo_enabled' field is not visible. So, I am not able to access the location of the tweet.

What could be the reason ?

**Comment by aronwc** [comment]
The location can come from one of several places for a tweet:

tweet['user']['locaton']
tweet['place']
tweet['geo']['coordinates']

Only a small percentage of tweets will have geo coordinates.

-Aron
