### ISSUE TITLE
Question about a4

### ISSUE THREAD

**Issue by cwang90** [iit-cs579/main#354]
In collect.py, can I use downloaded static data in the subsequent phases of analysis or I have to use specific API to get dynamic data?

**Comment by aronwc** [comment]
collect.py should download new, dynamic data.
You may use additional static data in cluster/classify, but you must
ultimately do the clustering/classification on the data returned by
collect.py.

E.g., you may use an additional, static dataset to help train your
classification model, then use it to classify the data returned by collect.

**Comment by cwang90** [comment]
If I want to use additional static data set, first I should cluster them to get label, then using label and data to build and train model, then I still need to cluster new data which is returned by collect, finally I use trained model to test on new data, is it correct?

**Comment by ClaytonTurner** [comment]
Yes

**Comment by Shringa13** [comment]
I did not understand the static data concept?
Can you please explain it again?

**Comment by ClaytonTurner** [comment]
So you can have data that is static, meaning it doesn't change, you're not getting new data. This can be used to train up a classifier. When you go to test, however, you need dynamic data, so some data that you are pulling from a resource like Twitter or Facebook.

So static data could be like I download 5000 twitter users' info today and keep it just to create an algorithm, run some clustering to get a label or using information from their profile/tweets to make a label that I want to classify. When I want to do classification I need to pull down newer users from Twitter to actually run the classification on - the model that I use could be trained partially or solely by my old, static data, but the classification needs to be done on the newer, dynamic data.

**Comment by Shringa13** [comment]
Thank you Clayton

**Comment by cwang90** [comment]
In cluster.py, I have to apply community detection algorithm, can I use other way to cluster data? Like in assignment a2, if doc name contain pos, it belongs to cluster 1, if name contains neg, it belongs to cluster 0.
