### ISSUE TITLE
TwitterRequestError: Twitter request failed (401)

### ISSUE THREAD

**Issue by RittickDatta** [iit-cs579/main#356]
Hi Professor,

I get the following error on collecting data:
TwitterRequestError: Twitter request failed (401)

I looked up the error code and it means: "Missing or incorrect authentication credentials. Also returned in other circumstances, for example all calls to API v1 endpoints return 401."

I did not modify my credentials and i was able to collect data an hour back. What could be the issue ?

**Comment by ClaytonTurner** [comment]
Are you making a new call or are you usong a call that you 100% know works. 

Make a simple call to make sure you can get info  (something from an older lecture or the first assignment). If this works, then your new call may be deprecated, malformed, or youre bumping into a privacy barrier. If not, then maybe try getting new tokens.

**Comment by RittickDatta** [comment]
Hi Clayton,

I was able to fetch all data that i needed with my calls. I did not modify my code later, except some folder creation to store the data.

I printed the status codes of the retrieved users, i get 401 for one user. Can this be a privacy barrier?

**Comment by ClaytonTurner** [comment]
If it's for one user, then that user likely has their profile information set to private rather than public so you can't get their information. So yes.

**Comment by RittickDatta** [comment]
So, can i simply assign an empty list for a person, when i get a 401 error?

**Comment by RittickDatta** [comment]
Turns out, one in every, say 10 or 20 users keep their account private. A status_code check helps to resolve this issue.
