### ISSUE TITLE
About Sentiment Words Set in A4

### ISSUE THREAD

**Issue by linglei1134** [iit-cs579/main#358]
Hi, 
I have a question in assignment 4.
For the data itself, I will tweet it raw from Twitter.
For the sentiment words set (such as positive and negative words set) that used for features of data, are we allowed to use the large words set developed by others (such as Hu and Liu, KDD-2004)? Or we need to create our own simple words set?

**Comment by aronwc** [comment]
You can use existing word lists as part of your classification routine.

**Comment by linglei1134** [comment]
Got it. Thank you.
