### ISSUE TITLE
rest vs streaming api

### ISSUE THREAD

**Issue by ranjeetkumar** [iit-cs579/main#359]
For collecting data about tweets for particular search query, which will be better for assignment 4, rest or streaming api?

**Comment by saiarjuntanguturi** [comment]
[](https://dev.twitter.com/streaming/overview)
Really depends on your use case, and what kind of data you're trying to obtain. The streaming API is used to establish an HTTP connection to Twitter's servers, and retrieve live (tweets that are being posted at the moment) tweets. 
Whereas, the REST API can be used to search past tweets by user/location/etc.

The streaming API is most likely more useful for the dynamic data portion of A4, and if you were using static data to train your model, the REST API could be a good idea. Although you could also use the streaming API for static data (i.e. retrieve tweets live, save them to a file via pickle, and use this data to train your model).

**Comment by ranjeetkumar** [comment]
thanks @saiarjuntanguturi , this is helpful. For me, REST api will be better.
