### ISSUE TITLE
Question about cluster

### ISSUE THREAD

**Issue by cicirao** [iit-cs579/main#361]
Previously, we usually have one component in a graph. And when we do community detection, we try to cut edges and make it become multiple components.
But, I'm thinking about an opposite situation. Can I do this?
I have, say 50, twitter users (nodes). Each user has a name and a description. But the original status is that, they are not connected. The graph is 50 nodes without edges. Can I try compute their similarity by using their names and description, and then, use the similarity to cluster and connect them? (e.g. if two nodes' similarity is larger than a specific number, then connect them?)

**Comment by aronwc** [comment]
Yes, but for this assignment, please use social links to inform the clusters, not the text. E.g., look at the users followers/friends to construct the graph.

**Comment by cicirao** [comment]
@aronwc I see. Thanks.
