### ISSUE TITLE
Fewer Model Coefficients

### ISSUE THREAD

**Issue by RittickDatta** [iit-cs579/main#365]
Hi professor,

I have 2 class labels but my model has coefficients for only 1 class.
I trained the classifier with equal amount of data for each class.

How can i get coefficients for both classes?

**Comment by aronwc** [comment]
In LogisticRegression, clf.coef_[0] are coefficients for positive class, and -clf.coef_[0] are coefficients for negative class.

**Comment by RittickDatta** [comment]
Thanks, professor.
