### ISSUE TITLE
Language issues

### ISSUE THREAD

**Issue by hegdenagaraj4** [iit-cs579/main#366]
Dear Professor,
 some of the tweets are in different language. Chinese, Arabic, Spanish, Hindi. etc. How do I avoid them? Is it my query keyword? Or is there any way that I can handle this?

**Comment by aronwc** [comment]
See the lang field of a tweet:
https://dev.twitter.com/overview/api/tweets

**Comment by hegdenagaraj4** [comment]
thank you
