### ISSUE TITLE
Issue with Community Detection

### ISSUE THREAD

**Issue by LSP16SCM43R** [iit-cs579/main#367]
Hi all, I have collected around 5000 tweets based on the location. What would be the best way to do community detection? If I try using 'following' as the criteria, it takes a lot of time due to the number of users and twitter rate limits. I want to know other possible ways. It would be really great if somebody could help me in this regard.

**Comment by aronwc** [comment]
You can collect friends or followers for a subset of the data.

**Comment by LSP16SCM43R** [comment]
Thank you Professor!

As per my understanding, from the tweets collected, If I select 50 distinct users and build a network based on these 50 users and their friends, I would have a graph containing 500+ nodes for community detection, Hope this would suffice for the assignment.

**Comment by aronwc** [comment]
yes.
