### ISSUE TITLE
[HW4] Collect data

### ISSUE THREAD

**Issue by sure00** [iit-cs579/main#368]
Hi Professor and all 
    I am trying to filter the friends of the person who mentioned Trump to construct the network. 
    Is there any API that can check whether his/her friends also have any Tweets that mentioned about Trump?

    I find a API which is users/show can see the user`s most recent Tweet but not all Tweets.

**Comment by aronwc** [comment]
No, you'd have to collect the tweets from each user and search yourself. This would take a while, so maybe just try on a subset.

**Comment by sure00** [comment]
Thanks
