### ISSUE TITLE
connected components

### ISSUE THREAD

**Issue by ranjeetkumar** [iit-cs579/main#374]
By using search/tweets API, I collected 100 users with specified topic(let say cricket). Then I collected all the friends of each user. When I build  a network of this, I got many sub-components. 

I tried varying the number of friends nodes for each user. I got the following graph :
![lessuser](https://cloud.githubusercontent.com/assets/1698169/20464518/8e1ee44a-af6e-11e6-9cd7-2a3a3091d3c8.PNG)
![mediumuser](https://cloud.githubusercontent.com/assets/1698169/20464520/904aeb56-af6e-11e6-9f62-ed525d1c2a4f.PNG)
![userlist](https://cloud.githubusercontent.com/assets/1698169/20464526/928b7e4e-af6e-11e6-929c-9ff7f6de4acf.PNG)

For applying, Girvan-Newman algorithm , We need one single connected component. As of now, I am thinking of taking the largest component from the graph and then applying Girvan-Newman algorithm. Is this approach correct?

Can anyone let me know, how to solve this problem?

**Comment by Swapnil2095** [comment]
Same problem here.

**Comment by aronwc** [comment]
As I discussed in class, you might try constructing a graph where a weighted edge between A and B represents the Jaccard similarity between the friends of A and B. This will be more densely connected.

**Comment by ranjeetkumar** [comment]
Thanks
