### ISSUE TITLE
Possible idea for cluster.py

### ISSUE THREAD

**Issue by cicirao** [iit-cs579/main#375]
If I use friends/followers, the cluster looks really boring and not interesting. I'm thinking, if I can use the user_mention as well? Like, I have several users  and I've got their ~3,200 tweets, if A mentions B in a tweet, then connect A and B. This creates more connections. Can I do this for A4?

**Comment by cicirao** [comment]
![cluster](https://cloud.githubusercontent.com/assets/3103675/20465240/92ee781e-af1e-11e6-9f8a-d0e1ac712494.png)
If I do followers, it's like this, a very boring graph.

**Comment by vmanikes** [comment]
Sounds like a nice idea and I guess if we follow your idea we can overcome the twitter rate limiting factor also for `friends/followers`

**Comment by aronwc** [comment]
You're welcome to use mentions to create a graph if you wish.

**Comment by cicirao** [comment]
Thanks!

**Comment by Tsreenivasan** [comment]
@cicirao One Question,  are you computing the betweenness every time u delete an edge, or is it computed once?

getting the Betweenness centrality takes 20 seconds for graphs over 2000 V and 8000 E.
