### ISSUE TITLE
any other algorithm that is suited for large networks?

### ISSUE THREAD

**Issue by thirumalrao** [iit-cs579/main#376]
Looks like girvan-newman is not particularly suited for very large graphs. Is there any other community detection algorithm someone has tried that works well with large graphs(>10000 nodes and >30000 edges) ?

nx.edge_betweenness_centrality took >8hrs on my macbook pro to find the best edge for 1 iteration.

**Comment by cicirao** [comment]
As the professor mentioned, you can use a sub_graph.

**Comment by thirumalrao** [comment]
This is for a subgraph... I had collected 100 users and their friends, but
am using a subset. I could always reduce the size of the subset, but
curious to know if someone has tried a different algorithm.
