### ISSUE TITLE
Collecting Data to file

### ISSUE THREAD

**Issue by pratik27shah** [iit-cs579/main#379]
Hi,
I am collecting data from FaceBook which takes few seconds for 1200 comments so is it fine if I store data in dataframe and use to_pickle to write data to csv file and read_pickle to read data from csv?

**Comment by aronwc** [comment]
yes

**Comment by ClaytonTurner** [comment]
I would think this is fine (granted to_pickle creates a python serialized object as opposed to a csv)

**Comment by pratik27shah** [comment]
thank you
