### ISSUE TITLE
Getting the right screen_name for collec.py

### ISSUE THREAD

**Issue by vinaykai** [iit-cs579/main#380]
Hi everyone, I'm searching for tweets that contain a particular string so I'm using search/tweets.
Once I retrieve the Object I want to know which is the screen_name of the user but I find it in two locations:
1. tweet['entities']['user_mentions']['screen_name']
2. tweet['user']['screen_name']

Both of these have different values so I'm confused which one is the right one.

**Comment by vmanikes** [comment]
The second One

**Comment by vinaykai** [comment]
Are you sure? Because in this link for user it says that the perspectival attributes embedded within this object are unreliable

https://dev.twitter.com/overview/api/tweets

**Comment by vmanikes** [comment]
I am not sure about that but in the first case of yours it the `screen_name` of the mentioned user in the tweet, i.e. If I tweet 

> @justinbieber He is good :+1: 

1. `tweet['entities']['user_mentions']['screen_name']` gives screen_name of justin bieber
2. `tweet['user']['screen_name']` gives my screen_name

Hope this helps

**Comment by aronwc** [comment]
Yes, it's the second one.
