### ISSUE TITLE
connecting nodes and edge scores

### ISSUE THREAD

**Issue by sramaraju** [iit-cs579/main#381]
Hi,
For creating the graph, can we use location/timezone of  the users(nodes) to connect them? Or, is it specific to use their social links( friends/followers) for connecting the nodes of the graph. 

 Ex: can I connect users tweeting about the same trends or mentions ( # or @) belonging to same geolocation/timezone.

**Comment by sramaraju** [comment]
As per @361, it is encouraged to construct the graph using their social links (Followers/ friends)

**Comment by aronwc** [comment]
Please use social links, not location/timezone.
