### ISSUE TITLE
Could we using exist Twitter data labeled by sentiment to buld model

### ISSUE THREAD

**Issue by sure00** [iit-cs579/main#383]
Hi Professor
    I want to analysis the twitters about somebody. So could we follow textbook to Download Twitter data labeled by sentiment from http://cs.stanford.edu/people/alecmgo/trainingandtestdata.zip' and then use that to build the train model?

**Comment by sure00** [comment]
I am trying to build a model to predict my data. So I want to check whether I can use the  http://cs.stanford.edu/people/alecmgo/trainingandtestdata.zip which used in notes to build my model?

**Comment by aronwc** [comment]
Sure, but you should also collect new data to classify.
