### ISSUE TITLE
Final

### ISSUE THREAD

**Issue by qsong4** [iit-cs579/main#385]
Hello professor,

What is the question type of Final exam, is it as same as Midterm?

Thanks!

**Comment by aronwc** [comment]
Yes

**Comment by ishujaswal** [comment]
What will be the time duration of the exam?

**Comment by aronwc** [comment]
The normal class period.

**Comment by cicirao** [comment]
I'm reading l21.ipynb, the final review. Under the "demographics" section, the last term under this section is "regularization (why?)". But I didn't see this "regularization" in L12 or L13. Where can I find it? Or what does it mean?

**Comment by sure00** [comment]
That is the lecture that talked in Dec. 9, 2016

**Comment by yzhao1216** [comment]
Do we need to bring calculator?

**Comment by aronwc** [comment]
No calculators allowed.

**Comment by davidghiurco** [comment]
@cicirao regularization is discussed in lec 15. It is the process of controlling how many parameters a modl can have and how big those parameters can be.

**Comment by theTechie** [comment]
What was the time duration for the Final's on campus ?
I am an online student from India and there was a confusion if it was 75 or 90 minutes.

**Comment by aronwc** [comment]
75.
