### ISSUE TITLE
CSR Matrix

### ISSUE THREAD

**Issue by rmasand1** [iit-cs579/main#388]
In the CSR Matrix documentation, there is an example:

> >>> indptr = np.array([0, 2, 3, 6])
>>> indices = np.array([0, 2, 2, 0, 1, 2])
>>> data = np.array([1, 2, 3, 4, 5, 6])
>>> csr_matrix((data, indices, indptr), shape=(3, 3)).toarray()
array([[1, 0, 2],
       [0, 0, 3],
       [4, 5, 6]])

Is the indptr here similar to the row_ptr in example of Lecture 13?

**Comment by ClaytonTurner** [comment]
Think of the indptr as a tell as to how many items are on the coming up row:

1st row <- 0,2 (so 0 and 1 for a length of 2 so we have 2 non-zero items (1 and 2))
2nd row <- 2,3 (so 2 for a length of 1 so we have 1 non-zero item (3))
3rd row <- 3,6 (so 3,4, and 5 for a length of 3 so we have 3 non-zero items (4,5 and 6))

**Comment by aronwc** [comment]
Yes

**Comment by vmanikes** [comment]
but in the class example it talks about the `col_ind` but this example is about lengths. So which one to follow

**Comment by ishujaswal** [comment]
@vmanikes  The explanation is same in class lecture as well.

**Comment by rmasand1** [comment]
@ishujaswal it's the same explanation, the only difference is that if we were solving this the way it's done in Lec 13, our data and indices array would be same, but ind_ptr would be [0,2,3] ,according to what I understood.

**Comment by aronwc** [comment]
You're right that in our example in class, we would have used `ind_ptr=[0,2,3]` instead of `ind_ptr=[0,2,3,6]` (the final `6` is implied). Either way is fine.
