### ISSUE TITLE
When to split testing and training data?

### ISSUE THREAD

**Issue by yepinxia** [iit-cs579/main#389]
Hi professor and TA, 

As title mentioned, should I split it before vectorize and building the document-term matrix or after? 
right now, I have separate files for the training and testing data. So I can do either way. 

Also, similarly, should I perform feature selection on both training and testing data? or just training data?

Thanks!

Pinxia

**Comment by aronwc** [comment]
The best practice is to split before vectorize.
Feature selection is performed on the training data, and only the selected
features are used when classifying the testing data.

**Comment by yepinxia** [comment]
Thank you!
