### ISSUE TITLE
Unreadable Notebook: NotJSONError("Notebook does not appear to be JSON

### ISSUE THREAD

**Issue by morlowsk** [iit-cs579/main#39]
I am getting the following error when I try to run ipython:

[W 12:25:40.027 NotebookApp] 400 GET /api/contents/a1.ipynb?type=notebook&_=1441128339659 (127.0.0.1) 3.34ms referer=http://localhost:8888/notebooks/a1.ipynb

Is anybody else getting the same error?

**Comment by aronwc** [comment]
Which version of ipython do you have?

```
$ ipython -V
4.0.0
```

This works fine for me:
```
$ pwd
/Users/awculott/t/osna/main/asg/a1
$ ipython notebook a1.ipynb 
```

**Comment by morlowsk** [comment]
Mine isn't working even with the newest version.
```
morlowski at morlowski-UX305FA in [~/Desktop/CS Classes/CS 579/morlowsk-asg/asg/a1]  on git:master ✗  381a823 "my first commit"
12:34:59 › ipython -V               
4.0.0
```

How did you install notebook? I did:

```
sudo pip install jupyter
```

**Comment by aronwc** [comment]
That should be fine. Let's take a look at a1.ipynb to be sure it's what we expect:

```
$ head a1.ipynb 
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# CS579: Assignment 1\n",
    "## Collecting a political social network\n",
    "\n",
    "In this assignment, I've given you a list of Twitter accounts of 15 U.S. presedential candidates.\n",
```

**Comment by morlowsk** [comment]
Yeah I get something completely different. It looks like you have json, whereas I don't:

```
morlowski at morlowski-UX305FA in [~/Desktop/CS Classes/CS 579/morlowsk-asg/asg/a1]  on git:master ✗  381a823 "my first commit"
12:35:04 › head a1.ipynb 
# Imports you'll need.
from collections import Counter
import ConfigParser
import matplotlib.pyplot as plt
import networkx as nx
import sys
import time
from TwitterAPI import TwitterAPI

#%matplotlib inline
```

**Comment by aronwc** [comment]
You probably saved the file from your browser. Instead, I recommend cloning the whole repo (in a separate folder). Then, you can copy a1.ipynb directly.

Otherwise, when viewing it on Github, you can click "View Raw" to get the raw contents of the file:
https://raw.githubusercontent.com/iit-cs579/main/master/asg/a1/a1.ipynb
