### ISSUE TITLE
Issue in summarize.py

### ISSUE THREAD

**Issue by ddabhane** [iit-cs579/main#390]
What is exactly is required in **Number of instances per class found** and **One example from each class** ?

Thanks!

**Comment by aronwc** [comment]
One example from each class:
- E.g., if you are doing sentiment classification of tweets, list one
positive and one negative tweet found during the collect.py process, as
classified by your classifier.


Number of instances per class found:
- As in the above example, list the number of positive and negative
examples classified by your classifier.
