### ISSUE TITLE
Classification 

### ISSUE THREAD

**Issue by Swapnil2095** [iit-cs579/main#391]
Hi,

I am doing positive -negative sentiment analysis on news.
I took 6000 tweets. Most of the tweets are same after my classification.

Please tell me-
you just have to make classification of tweets that's it, right?

**Top Positive Tweets ->**
9 0 RT @indraroy: Brilliant breaking story from @CNNIBNLive .... AAP MLA Kartar Singh doesnt disclose benami property worth crores. Super @bhup…
9 0 RT @indraroy: Brilliant breaking story from @CNNIBNLive .... AAP MLA Kartar Singh doesnt disclose benami property worth crores. Super @bhup…
9 0 RT @indraroy: Brilliant breaking story from @CNNIBNLive .... AAP MLA Kartar Singh doesnt disclose benami property worth crores. Super @bhup…
9 0 RT @indraroy: Brilliant breaking story from @CNNIBNLive .... AAP MLA Kartar Singh doesnt disclose benami property worth crores. Super @bhup…
9 0 RT @indraroy: Brilliant breaking story from @CNNIBNLive .... AAP MLA Kartar Singh doesnt disclose benami property worth crores. Super @bhup…
9 0 RT @indraroy: Brilliant breaking story from @CNNIBNLive .... AAP MLA Kartar Singh doesnt disclose benami property worth crores. Super @bhup…
9 0 RT @indraroy: Brilliant breaking story from @CNNIBNLive .... AAP MLA Kartar Singh doesnt disclose benami property worth crores. Super @bhup…
9 0 RT @indraroy: Brilliant breaking story from @CNNIBNLive .... AAP MLA Kartar Singh doesnt disclose benami property worth crores. Super @bhup…
9 0 RT @indraroy: Brilliant breaking story from @CNNIBNLive .... AAP MLA Kartar Singh doesnt disclose benami property worth crores. Super @bhup…
9 0 RT @indraroy: Brilliant breaking story from @CNNIBNLive .... AAP MLA Kartar Singh doesnt disclose benami property worth crores. Super @bhup…

**Top Negative Tweets ->**
3 8 RT @ZeeNews: Scientists record worst ever coral die-off on Australia's Great Barrier Reef https://t.co/mmj9LqGALQ https://t.co/NPQCHp55Ec
3 8 RT @ZeeNews: Scientists record worst ever coral die-off on Australia's Great Barrier Reef https://t.co/mmj9LqGALQ https://t.co/NPQCHp55Ec
3 8 RT @ZeeNews: Scientists record worst ever coral die-off on Australia's Great Barrier Reef https://t.co/mmj9LqGALQ https://t.co/NPQCHp55Ec
3 8 RT @ZeeNews: Scientists record worst ever coral die-off on Australia's Great Barrier Reef https://t.co/mmj9LqGALQ https://t.co/NPQCHp55Ec
3 8 RT @ZeeNews: Scientists record worst ever coral die-off on Australia's Great Barrier Reef https://t.co/mmj9LqGALQ https://t.co/NPQCHp55Ec
3 8 RT @ZeeNews: Scientists record worst ever coral die-off on Australia's Great Barrier Reef https://t.co/mmj9LqGALQ https://t.co/NPQCHp55Ec
3 8 RT @ZeeNews: Scientists record worst ever coral die-off on Australia's Great Barrier Reef https://t.co/mmj9LqGALQ https://t.co/NPQCHp55Ec
3 8 RT @ZeeNews: Scientists record worst ever coral die-off on Australia's Great Barrier Reef https://t.co/mmj9LqGALQ https://t.co/NPQCHp55Ec
3 8 RT @ZeeNews: Scientists record worst ever coral die-off on Australia's Great Barrier Reef https://t.co/mmj9LqGALQ https://t.co/NPQCHp55Ec
3 8 RT @ZeeNews: Scientists record worst ever coral die-off on Australia's Great Barrier Reef https://t.co/mmj9LqGALQ https://t.co/NPQCHp55Ec
Classification Done Successfully!!

**Comment by changediyasunny** [comment]
Not sure about your classification. but I'd suggest look into tweets fetched again.  they seem to contain retweets and out of 6000, more than 65% of tweets would be duplicated/ retweeted.
Try removing retweets.

**Comment by theTechie** [comment]
You will need to look into since_id and max_id in `search/tweets` api to avoid this
