### ISSUE TITLE
Number of Clusters

### ISSUE THREAD

**Issue by yepinxia** [iit-cs579/main#394]
Hi Professor and TAs - 

I used the Jaccard similarity to construct my network with a threshold of 0.005. I tried betweenness and eigenvalue approach to cluster my twitter users. But they seem to belong to one giant cluster (~500), and about twenty single unconnected node. 

when I use betweenness - greedy algorithem to remove edges, each time the split 1 or 2 vs the rest. 
see my edges betweenness histogram below

![betweenness](https://cloud.githubusercontent.com/assets/8060299/20738272/843def2e-b677-11e6-8164-3b48d0ec9ca3.png)

for eigen values, huge amount of edges has 0, the rest are about 0.01-ish. here is a distribution of my eigen values. 

![eigenvalues](https://cloud.githubusercontent.com/assets/8060299/20738155/dd1a1f60-b676-11e6-9aa2-042e6933d41b.png)

please advice! is it okay if the result is one giant cluster??

Thank you!

P.

**Comment by aronwc** [comment]
My guess is the clustering is first removing the outliers. Perhaps focus on the nodes that have at least two edges? Otherwise, you could add constraints to the clustering algorithm to require communities to have more than X and less than Y members.

**Comment by yepinxia** [comment]
Hi professor, 

Which approach is better? betweenness or eigenvalue? if I use eigenvalue, I could easily control the size of clusters, but I feel that's a bit more arbitrary to select the threshold..
Thanks, again!
P.

**Comment by aronwc** [comment]
I think you'll find girvan newman more stable and easier to use for this
assignment (neither is superior in all cases).

**Comment by yepinxia** [comment]
Thank you!
