### ISSUE TITLE
format of summary.txt

### ISSUE THREAD

**Issue by ranjeetkumar** [iit-cs579/main#396]
How to write the answer for the following:
1) Average number of users per community:
2) Number of instances per class found:
3) One example from each class:

1. Suppose, I got 5000 nodes in community 1 and 3000  nodes in community 2 , then
 Average number of users per community = (5000+3000)/2 = 4000
 This is quite misleading if 7999 nodes in community 1 and 1 nodes in community then it  average will 4000
 Is this interpretation of  average number of users per community correct or we have to write simply the no of nodes per community.

2) I am writing like this
Number of instances per class found:  Positive instances 2003  negative instances 4000
Do we have to write this in any specific format?

3) One example from each class:
positive example: <example_tweet>
negative example: <negative_tweet>
Do we have to write this in any specific format?

**Comment by aronwc** [comment]
- The average is correct.
- No specific format.
- The main thing to ensure is that this file is created based on the data
collected in collect.py. So, it should change each time I run your program.
-Aron

**Comment by ranjeetkumar** [comment]
Thanks a lot!
