### ISSUE TITLE
Twitter status code 400

### ISSUE THREAD

**Issue by jaydeeppatel1701** [iit-cs579/main#40]
connection has been established. last night i was getting my status code 200 and all queries were working completely fine. Now it is 200. What is the reason for that?

**Comment by shreeshbhat** [comment]
Check https://dev.twitter.com/overview/api/response-codes for explanations
of different status codes

**Comment by jaydeeppatel1701** [comment]
@shreeshbhat i checked that error, the request is completely fine as it was working fine last night, i am figuring out why it cannot be served. if you have any idea??

**Comment by poojamankani** [comment]
What is the accompanying error message that you get along with the error code?

**Comment by shreeshbhat** [comment]
You might be getting error status 40 ( bad request ) because of wrongly
coded request. If not, try to simplify your request and see if it is
working.

**Comment by shreeshbhat** [comment]
Sorry, 400*

**Comment by jaydeeppatel1701** [comment]
@poojamankani No error message with code.

**Comment by aronwc** [comment]
If `response` is the object returned by the request, try printing `response.text`.

**Comment by carolgrrr** [comment]
Did you try re-running your whole notebook from the beginning? I've run into some weird errors when I come back to one chunk of code after some time away. Sometimes that chunk is missing an import or an initialization from somewhere earlier in the notebook, and re-running fixes the issue.
