### ISSUE TITLE
matplotlib inline issue

### ISSUE THREAD

**Issue by SyedHamdanSher** [iit-cs579/main#400]
Are we suppose to use %matplotlib inline in the main a0.py file or it just for ipynb file ? 
Can I comment the %matplotlib inline in the a0.py python file? Since we are already saving the final output picture.

Thank you.

**Comment by nerdySingh** [comment]
When you're running on a main file don't use inline method use plt.show()
when you import matplotlib.pyplot as plt.

**Comment by SyedHamdanSher** [comment]
We actually don't need to show in this assignment, we just need to save the image. But I get you thanks for the info.
