### ISSUE TITLE
#401

### ISSUE THREAD

**Issue by nerdySingh** [iit-cs579/main#401]
Can we use a command line method to write the output to the Log.txt file?

**Comment by rzskhr** [comment]
I don't think that we need to submit the Log.txt file, it is for our reference I suppose. See point 9 in the assignments page (https://github.com/iit-cs579/assignments).

As per my knowledge the deliverables for first assignment are "a0.py", "ShortAnswer.txt" and "network.png".

Can someone confirm this?

**Comment by aronwc** [comment]
Correct
