### ISSUE TITLE
Partitions returned by girvan newman

### ISSUE THREAD

**Issue by SanchayanMaity** [iit-cs579/main#403]
How many partitions is partition_girvan_newman expected to return? Any guidance on expected suitable number of components?

**Comment by aronwc** [comment]
For the data used in the main method, partition_girvan_newman should return two communities.

**Comment by SanchayanMaity** [comment]
@aronwc Sorry about that professor. I see now. Was completely concentrating on implementing things from top to bottom in the file and did not see the main function. Thanks for the clarification.
