### ISSUE TITLE
node2num_paths confusion

### ISSUE THREAD

**Issue by apate131** [iit-cs579/main#404]
The description of the bfs function says node2num_paths is "dict from each node to the number of shortest paths from the root node that pass through this node". That sounds like the betweenness score, except for a node instead of an edge. The output in the doctest isn't consistent with this. It seems like the sample output is the number of shortest paths to each node.

Clarification?

**Comment by SanchayanMaity** [comment]
Even I have the same confusion and considered it as the number of shortest paths to each node. But due to the confusion I avoided using that dictionary perhaps where I could. There is a closed issue from a previous class on the same thing, but, that still did not clear it up exactly.

**Comment by aronwc** [comment]
I've clarified the documentation:
https://github.com/iit-cs579/assignments/commit/1d7ab136373adcadd97382912a2dd80b401d5ba9#diff-fd0d01ab3523a3eebf0e7b1f098bd465

> node2num_paths...dict from each node to the number of shortest paths from 
>                                the root node to this node.

The test case is correct.

> So for node D, there is only one shortest path from E to D (E-D). The only node in the example graph that has a different value is G, as there are two different paths of the same distance (E-F-G) and (E-D-G).
