### ISSUE TITLE
path_score(graph, root, k, beta):

### ISSUE THREAD

**Issue by SyedHamdanSher** [iit-cs579/main#406]
Hi,

Calculation of the similarity between two nodes X,Y is given by -:
(beta^i)*n ? i.e. beta to the power of i multiplied by n <------- is this right ??
where
    - $\beta \in [0,1]$ is a user-provided parameter
    - $i$ is the length of the shortest path from $x$ to $y$
    - $n$ is the number of shortest paths between $x$ and $y$ with length $i$

Thank you.

**Comment by SanchayanMaity** [comment]
Yes it's multiplied by n. I was not sure either but my answers match with the log when using multiply.
