### ISSUE TITLE
doubt in token_pair_features  in a2

### ISSUE THREAD

**Issue by SanchayanMaity** [iit-cs579/main#409]
Can someone provide a more detailed/example of token_pair_features? If the array were [a, b, c, d, e, f, g, h] what would token_pair_features output be for k=3?

**Comment by EFA16SCM55A** [comment]
Please, could you tell me which chapter or lecture that discuses token_pair_features; sorry I didn't face any example or info about that and I'm asking to know in case I missed it while I'm going through the lectures...Thanks

**Comment by SanchayanMaity** [comment]
Look in the assignment 2 python file. See [here](https://github.com/iit-cs579/assignments/blob/master/a2/a2.py#L122)

**Comment by EFA16SCM55A** [comment]
We have Quiz this week and midterm next week for this course need your effort, and the professor doesn't update it yet to start working on it.
Good luck

**Comment by SanchayanMaity** [comment]
Any further input on this please?

**Comment by aronwc** [comment]
> If the array were [a, b, c, d, e, f, g, h] what would token_pair_features output be for k=3?

```python
>>> feats = defaultdict(lambda: 0)
>>> token_pair_features(np.array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']), feats, k=3)
>>> sorted(feats.items())
[('token_pair=a__b', 1), ('token_pair=a__c', 1), ('token_pair=b__c', 2), ('token_pair=b__d', 1), ('token_pair=c__d', 2), ('token_pair=c__e', 1), ('token_pair=d__e', 2), ('token_pair=d__f', 1), ('token_pair=e__f', 2), ('token_pair=e__g', 1), ('token_pair=f__g', 2), ('token_pair=f__h', 1), ('token_pair=g__h', 1)]
```

**Comment by SanchayanMaity** [comment]
Thank you very much. That clears things up.

**Comment by SanchayanMaity** [comment]
@aronwc One doubt. How exactly is the second value of the tuple calculated? At first I thought, as (b,c) comes in picture while considering 'a' with a window of 3 and also 'b' with a window of 3, so it gets a value of 2. But this does not match for token pair (g,h). Another similar logic I considered was if the second value of the tuple has been encountered before or something similar.

**Comment by aronwc** [comment]
There is only one window that contains (g,h); that is the window (f,g,h). We don't consider partial windows. E.g., since k=3, we need at least three characters in each window. So, (g,h,_) is not a valid window.

**Comment by SanchayanMaity** [comment]
Thank you for the clarification.

**Comment by EFA16SCM55A** [comment]
Sorry, but I couldn't understand this point
"Another similar logic I considered was if the second value of the tuple has been encountered before or something similar". please explain it more and thanks
