### ISSUE TITLE
Issue while running jupyter notebook on windows 7 32 bit .

### ISSUE THREAD

**Issue by shivankb** [iit-cs579/main#41]
whenever i am clicking on the ipython notebook launcher , it redirects me to http://localhost:8889/tree , but all the browsers show me the webpage in an improper format . kindly refer the screenshot , what should i do to display the webpage in the proper format.
![image](https://cloud.githubusercontent.com/assets/13937469/9624778/921178ca-516d-11e5-9840-e31cf7aa83a9.png)

**Comment by ironhide23586** [comment]
Did you try running it through the command line interface by typing in "ipython notebook a1.ipynb"?

--
Yours Sincerely,
Souham Biswas
Computer Science Graduate Student (MS)
Illinois Institute of Technology, Chicago, IL, USA

Contact Nos.: +1-(312)-866-1163 (Mob.), +1-(312)-846-1535 (Home)

**Comment by shivankb** [comment]
yeah , I have done that actually . The issue is regarding the display of the menu and links display on the webpage which is irregular. I am facing the same issue on the internet explorer , chrome as well . I have tried both the ways of accessing ipython using Cmd and launcher on the Anaconda , but it did not resolve the issue.

**Comment by aronwc** [comment]
Have you tried going to <http://localhost:8889/notebooks/a1.ipynb>?

**Comment by shivankb** [comment]
yes aron ,

i had tried to go on the mentioned link , it shows me the following webpage 
![image](https://cloud.githubusercontent.com/assets/13937469/9638525/e9bdc842-51c4-11e5-96c2-ccbb5079a1c6.png)

i had then changed my port number to http://localhost:8888/notebooks/a1.ipynb and then the page was displayed but with the same display issue
![image](https://cloud.githubusercontent.com/assets/13937469/9638610/47830d98-51c5-11e5-8010-416a0568188b.png)

**Comment by aronwc** [comment]
I assume you're using Windows?

Perhaps you need to change Jupyter's startup folder? See here <http://jupyter-notebook-beginner-guide.readthedocs.org/en/latest/execute.html>

> 3.1.1. Change Jupyter Notebook startup folder (Windows)
- Copy the IPython Notebook launcher from the menu to the desktop.
- Right click on the new launcher and change the “Start in” field by pasting the full path of the folder which will contains all the notebooks.
- Double-click on the IPython Notebook desktop launcher (icon shows [IPy]) to start the Jupyter Notebook App, which will open in a new browser window (or tab). Note also that a secondary terminal window (used only for error logging and for shut down) will be also opened. If only the terminal starts, try opening this address with your browser: http://localhost:8888/.

**Comment by jaydeeppatel1701** [comment]
click on new notebook -> python 2 option. that worked for me.

**Comment by shivankb** [comment]
this issue has been resolved for me and hence closing it.
