### ISSUE TITLE
doc_test for featurize(tokens, feature_fns) in a2

### ISSUE THREAD

**Issue by Pmac23** [iit-cs579/main#410]
According to the doc-test for this function, the feature_funs should be a list of strings, where each string a function name.
 >>> feats = featurize(np.array(['i', 'LOVE', 'this', 'great', 'movie']), [token_features, lexicon_features])
 >>> feats
which should be
 >>> feats = featurize(np.array(['i', 'LOVE', 'this', 'great', 'movie']), ['token_features', 'lexicon_features'])
 >>> feats

**Comment by aronwc** [comment]
No, the function names should not be enclosed in quotation marks.
