### ISSUE TITLE
Query on vectorize in a2

### ISSUE THREAD

**Issue by SanchayanMaity** [iit-cs579/main#413]
@aronwc 

Is it possible to have some more detailed explanation of vectorize with regards to csr matrix transformation? I am finding the scipy documentation difficult to grasp completely on how to approach the implementation for generation of csr matrix.

**Comment by SanchayanMaity** [comment]
Actually never mind. Managed to figure it out. Sorry for the noise.

**Comment by SanchayanMaity** [comment]
Is it possible to have a involved test case for verification provided for vectorize? My implementation works for the doctest but with an actual run with imdb  data gives "ValueError: unable to infer matrix dimensions" which is thrown from csr_matrix. I used the below as basis for the CSR matrix generation from the scipy website

'''
>>> docs = [["hello", "world", "hello"], ["goodbye", "cruel", "world"]]
>>> indptr = [0]
>>> indices = []
>>> data = []
>>> vocabulary = {}
>>> for d in docs:
...     for term in d:
...         index = vocabulary.setdefault(term, len(vocabulary))
...         indices.append(index)
...         data.append(1)
...     indptr.append(len(indices))
...
>>> csr_matrix((data, indices, indptr), dtype=int).toarray()
array([[2, 1, 0, 0],
       [0, 1, 1, 1]])
'''

It seems my for loop traversals and indices/indptr calculation do not work out for the real data with my indices being 85439 and indptr being 401.

**Comment by nerdySingh** [comment]
the car matrix worked for me using the above implementation, but it takes an awful amount go time say about 11s.

**Comment by aronwc** [comment]
@SanchayanMaity See related conversation here: #288
