### ISSUE TITLE
Doctest for featurize in A2

### ISSUE THREAD

**Issue by echibe** [iit-cs579/main#415]
The specification says that the function:

```
Returns:
      list of (feature, value) tuples, SORTED alphabetically
      by the feature name.
```

but the example output is not alphabetized. ('token=LOVE' is not higher than 'token=great')

Is there something with the capitalization that i'm missing?

**Comment by aronwc** [comment]
Yes, caps come first:

```python
>>> a = ['token=great', 'token=LOVE']
>>> sorted(a)
['token=LOVE', 'token=great']
```

**Comment by Pmac23** [comment]
But the tokenize function converts the string in to lowercase and then tokenizes the string. How can we get Uppercase/caps tokens here?

**Comment by echibe** [comment]
@Pmac23 I believe the Doctect just uses some sample tokens as examples. When ran, the program shouldn't have any uppercase values
