### ISSUE TITLE
Doctest in vectorize function

### ISSUE THREAD

**Issue by echibe** [iit-cs579/main#416]
It seems as though the toarray() function doesn't show the dtype if it is of type int64. If I change the csr matrix type to int8, for example, the toarray() output would show that dtype but it does not for int64. 

The doctest fails because of this. This is my output:
How can I make the dtype appear when specifying int64?

```
Expected:
    array([[1, 0, 1, 1, 1, 1],
           [0, 2, 0, 1, 0, 0]], dtype=int64)
Got:
    array([[1, 0, 1, 1, 1, 1],
           [0, 2, 0, 1, 0, 0]])
```

**Comment by aronwc** [comment]
I wouldn't worry about this. Feel free to change the test accordingly.
I'm not able to reproduce your problem; perhaps our versions differ?

```python
>>> import scipy
>>> scipy.__version__
'0.19.1'
>>> import numpy
>>> numpy.__version__
'1.13.3'
>>> from scipy.sparse import csr_matrix
>>> csr_matrix([[1,2,3]]).toarray()
array([[1, 2, 3]], dtype=int64)
```
