### ISSUE TITLE
Vectorize clarification

### ISSUE THREAD

**Issue by apate131** [iit-cs579/main#417]
According to the featurize() doctest, lexicon_features() will add neg_words and pos_words to feat even if no negative or positive words are found.

So then, in vectorize(), do we include neg_words and pos_words in the csr even if all the docs have ('neg_words', 0) or ('pos_words', 0)? In other words, does ('neg_words', 0) count towards the min_freq?

**Comment by aronwc** [comment]
No.

**Comment by EFA16SCM55A** [comment]
In inside vectorize  function, we just have token_features to deal with. I can't understand how we will include featurize() function which deals with both of them!?
