### ISSUE TITLE
Cross-Validation-Accuracy

### ISSUE THREAD

**Issue by nerdySingh** [iit-cs579/main#420]
so once we get csrmatrix and vocab we call cross_validation_accuracy(). when we use KFOLD(n,n_folds) where n_folds=5 and n is the size of the csr_matrix?

**Comment by aronwc** [comment]
Yes. n is the number of rows in the csr_matrix.

**Comment by SyedHamdanSher** [comment]
and number of the rows will be the number of labels we have.
