### ISSUE TITLE
accuracy

### ISSUE THREAD

**Issue by mellodi** [iit-cs579/main#421]
I am confused right now. I have calculated my accuracy and I have the same "best cross-validation result" as the log file and my "worst cross-validation result" has the same elements ( same punct, features, and min_freq) except my result have higher accuracy. That even make my "Mean Accuracies per Setting" result look different. Does anyone know what may went wrong

**Comment by nerdySingh** [comment]
hi even I’m confused slightly at that part of accuracy,
When we generated the csr matrix and the vocab we call cross_validation_acc
Can you tell me how did you go about from here if you can help!

**Comment by SanchayanMaity** [comment]
My complete results for eval_all_combinations are different. Not sure if it is possible or the implementation is wrong somewhere :(.

best cross-validation result:
('token_features token_pair_features lexicon_features', True, 0.71000000000000008, 2)
worst cross-validation result:
('token_pair_features', False, 0.62750000000000006, 10)

All possible combinations results

('token_features token_pair_features lexicon_features', True, 0.71000000000000008, 2)
('token_features lexicon_features', False, 0.70999999999999996, 2)
('token_features lexicon_features', True, 0.70500000000000007, 2)
('token_features', True, 0.69500000000000006, 2)
('token_features lexicon_features', False, 0.69500000000000006, 5)
('token_features token_pair_features', True, 0.69250000000000012, 2)
('token_features token_pair_features lexicon_features', True, 0.69250000000000012, 5)
('token_features lexicon_features', False, 0.68999999999999995, 10)
('token_features lexicon_features', True, 0.68750000000000011, 5)
('token_features', False, 0.6875, 2)
('token_features', False, 0.6875, 5)
('token_pair_features lexicon_features', True, 0.6875, 2)
('token_features token_pair_features lexicon_features', False, 0.6875, 2)
('token_features', True, 0.68499999999999994, 5)
('token_features token_pair_features lexicon_features', False, 0.68499999999999994, 5)
('token_features token_pair_features lexicon_features', True, 0.68250000000000011, 10)
('token_pair_features', True, 0.6825, 2)
('token_pair_features lexicon_features', False, 0.6825, 2)
('token_pair_features lexicon_features', False, 0.68249999999999988, 5)
('token_features token_pair_features', True, 0.68000000000000005, 5)
('token_features token_pair_features', False, 0.67999999999999994, 2)
('token_features token_pair_features', False, 0.67749999999999999, 5)
('token_features lexicon_features', True, 0.67749999999999999, 10)
('token_features token_pair_features lexicon_features', False, 0.67749999999999999, 10)
('token_pair_features lexicon_features', True, 0.67500000000000004, 5)
('token_pair_features lexicon_features', True, 0.67500000000000004, 10)
('token_features', True, 0.67249999999999999, 10)
('token_features', False, 0.67000000000000004, 10)
('token_pair_features', True, 0.67000000000000004, 5)
('token_features token_pair_features', False, 0.66500000000000004, 10)
('token_features token_pair_features', True, 0.65999999999999992, 10)
('token_pair_features', False, 0.65749999999999997, 2)
('lexicon_features', True, 0.65500000000000003, 2)
('lexicon_features', True, 0.65500000000000003, 5)
('lexicon_features', True, 0.65500000000000003, 10)
('lexicon_features', False, 0.65500000000000003, 2)
('lexicon_features', False, 0.65500000000000003, 5)
('lexicon_features', False, 0.65500000000000003, 10)
('token_pair_features', False, 0.65250000000000008, 5)
('token_pair_features lexicon_features', False, 0.65250000000000008, 10)
('token_pair_features', True, 0.64750000000000008, 10)
('token_pair_features', False, 0.62750000000000006, 10)

**Comment by EFA16SCM55A** [comment]
The same problem but I think the output is different because of the way we fit and predict clf in cross_validation_accurcy function

**Comment by mellodi** [comment]
actually, mine was different because of a mistake in my tokenizer function

**Comment by SanchayanMaity** [comment]
@mellodi I suspect the tokenizer function as well but I can't see what's inherently wrong with it. I use regular expressions. Do you suppress HTML too within the tokenizer?

**Comment by EFA16SCM55A** [comment]
I have not thought it will be the reason. Thanks, I will see.

**Comment by mellodi** [comment]
@SanchayanMaity I only search if they have punctuation in their words or not, nothing else

**Comment by SanchayanMaity** [comment]
@mellodi Ok, thanks for the info. I will forgo regular expressions and try the simpler way and check.
