### ISSUE TITLE
Total Running Time

### ISSUE THREAD

**Issue by SyedHamdanSher** [iit-cs579/main#427]
My main function is taking 10-14 mins to run and print the output. is this acceptable? or I have to reduce the timing, the accuracy are close to the ones mentioned in the log file.

**Comment by aronwc** [comment]
I’d recommend finding ways to reduce the running time. You might time each function to isolate the bottleneck.

**Comment by aagrekar** [comment]
@SyedHamdanSher it was taking long for me too. I then realized that the number of rows in my sparse matrix were being appended every time the code opted a different setting. this in turn was increasing the training data size and the logistic regression model took long to fit.. It might be worth checking there if not already resolved.

**Comment by SyedHamdanSher** [comment]
Thanks I will look into that
