### ISSUE TITLE
TwitterConnectionError

### ISSUE THREAD

**Issue by czhao18** [iit-cs579/main#43]
Hi, all, I got this error when I was trying to get all the friends for all candidates: 
TwitterConnectionError: HTTPSConnectionPool(host='api.twitter.com', port=443): Read timed out.

it's totally fine when I got friends for one candidate.

**Comment by aronwc** [comment]
@czhao18 This usually means your Twitter connection was open too long without data being received. 
I'd suggest either re-initializing your twitter object (by calling get_twitter again), or re-starting the notebook.

**Comment by czhao18** [comment]
re-initialize the twitter object works fine, problem solved!
