### ISSUE TITLE
Issue on csr matrix

### ISSUE THREAD

**Issue by lzq100123** [iit-cs579/main#430]
There are some cases that the data to form csr matrix is zero
How should we deal with these cases?
just return an empty csr matrix and discard the corresponding classifier setting?

**Comment by nerdySingh** [comment]
I’m returning none if that’s the case and in eval all I’ll call accuracy of
csr is not none

**Comment by lzq100123** [comment]
I think I deal with the case as same as you did by only call accuracy of csr is not zero
