### ISSUE TITLE
abt term in featurize of hw3

### ISSUE THREAD

**Issue by lzq100123** [iit-cs579/main#432]
Hi, I am confused about what the correct definition of term is in tfidf.

Does the term mean word and number in a string without punctuation or we just implement token_string method to get these terms?

Is it right to extract terms from column title and genres in movies or we just extract them from title?

Thanks

**Comment by EFA16SCM55A** [comment]
The professor stated that "The vocab, a dict from **term** to int. Make sure the vocab is sorted alphabetically as in a2 (e.g., {**'aardvark'**: 0,"
so the term means word
Also, he stated that"**token**, extracted  from the **'genre' field** of each movie"
I haven't read in the instruction anything about column title or using it!???so please tell me in which of the 4 functions he talks about title column!
I hope I helped you.

**Comment by lzq100123** [comment]
Thanks for you help.
Do you think term only contains [A~Z, a~z] without number and punctuation inside of a word? 
In the instruction of featurize method, I  don't think professor gave a full description about term.
In the lecture notes, it implied term is feature, and we can find "authors, title, actor, director..." is the set of features for movie profile in page 15. So I think the column title of movies must be a place we should extract terms from. 
I am confused about if we should also extract terms from genres since column genres also contains words

**Comment by aronwc** [comment]
See the tokenize method. Features only come from the genre field.

**Comment by lzq100123** [comment]
Thanks , it's very helpful
