### ISSUE TITLE
make_predictions issue

### ISSUE THREAD

**Issue by mellodi** [iit-cs579/main#434]
when we predict a user rating in the ratings_test should we use it as a new data(row) in the ratings_train or we shouldn't consider them at all, and assume that they all happened at the same time?

**Comment by ckomurluiit** [comment]
Referring to the description of the method: "[...] Compute the weighted average rating for every other movie that u has rated. [..]", you should use only movies in the training set. The newly predicted movie won't be part of the training set as it hasn't been rated by the user u.
