### ISSUE TITLE
df(i) : Unique Documents containing term i

### ISSUE THREAD

**Issue by RonitRudra** [iit-cs579/main#435]
The <strong>df(i)</strong> calculation requires unique documents. If you check the dataset, the number of unique titles is lesser than the number of rows which means there are duplicates. On further exploration I found out that although the movie titles had been repeated, the tokens generated were different as the genre column was different for the duplicate instances.
So, my question is, should I ignore the duplicate title instances or drop them from the data frame?

**Comment by vpatel812** [comment]
See issue #320

**Comment by RonitRudra** [comment]
@vpatel812 Thank You. That resolves the issue.
