### ISSUE TITLE
Error Evaluation

### ISSUE THREAD

**Issue by tejamaripuri** [iit-cs579/main#438]
How much error is acceptable? I got 0.8, will that be enough?

**Comment by SanchayanMaity** [comment]
Am getting error=0.912771. I also wanted to know the accepted error and if I have my function implementation wrong.

**Comment by nerdySingh** [comment]
error=0.778167
[ 2.55263158  2.62279152  2.62279152  3.74309392  3.40582297  4.26530612
  3.76584158  3.86616162  3.28888889  3.38888889]
i got this.....

**Comment by SanchayanMaity** [comment]
How did you get two different values for linalg and math.sqrt? Shouldn't they be same? After fixing my make_predictions functions, I now get 0.787455 for np.linalg.norm or math.sqrt which you mention.

**Comment by Pmac23** [comment]
@SanchayanMaity I have the same MAE. And I strongly believe we all should get the same.

**Comment by nerdySingh** [comment]
@SanchayanMaity when i use the sqrt method i dont get 0 for some values as compared to np.linalg.norm method. Anways both the methods have a .01 difference which is really small so im still gonna do some debugging to see where i might be going wrong.

**Comment by EFA16SCM55A** [comment]
@nerdySingh I used dot in cosin sim and I get the same their result . However,  I'm looking for the better solution to improve the speed for my code rather than using loop or math.sqrt & dot  I found them talking about np.linalg.norm, but I have some error to use it b/c this is the first time I use it.

**Comment by nerdySingh** [comment]
np.linalg.norm if you're getting  a shape error then  take the transpose of either a or b array!!

**Comment by SanchayanMaity** [comment]
@EFA16SCM55A  @nerdySingh is correct. I was also getting error when I finally implemented make_predictions. In the implementation of np.linalg.norm the transpose has to be taken. Found it by referring one of the older closed issue tickets. See discussion in #326 and #345.
