### ISSUE TITLE
Execution Time

### ISSUE THREAD

**Issue by MalharPatwari** [iit-cs579/main#439]
What should be the approximate execution time? Mine takes 5-6 minutes!!

**Comment by RonitRudra** [comment]
Mine takes around 20 seconds. You should look for bottlenecks in your code, typically loops and searches. Use dictionaries to eliminate access times.  The professor has included defaultdicts and counters in the imports for a reason. Are you converting CSR matrices to arrays by any chance? That would slow the code down as CSR operations are much faster than numpy ndarray operations. Also, when building the CSR matrices make efficient use of dictionaries to assign values to the correct indices.
Those are a few of the things I can suggest off the top of my head.

**Comment by SanchayanMaity** [comment]
Mine takes around

```
real	0m27.688s
user	0m23.577s
sys	0m0.053s
```

You can profile your code to check for bottlenecks.

**Comment by mellodi** [comment]
Do we lose points if our run time is between 3:30 to 4 minutes?!

**Comment by aronwc** [comment]
It's probably okay, but I would take a moment to see if you can make it more efficient.

**Comment by MalharPatwari** [comment]
My code takes 5 minutes in my laptop but takes 50 seconds in higher config laptop.
