### ISSUE TITLE
get_friends(screen_name) function

### ISSUE THREAD

**Issue by dmartiinez** [iit-cs579/main#44]
for this function, are we supposed to return a list with all the user's friend's name or screen name?

**Comment by FatemaT** [comment]
It has to return a list with user's friend's screen names which is the same as their usernames

**Comment by prateekagrawal06** [comment]
a list that contains screen names of all the friends

**Comment by aronwc** [comment]
Yes, this should be the 'screen_name' value for each user that a candidate follows.

**Comment by dmartiinez** [comment]
ok thank you! I just wasn't sure because each friend had a name key and a screen name key.

**Comment by dmartiinez** [comment]
one more thing...
I am getting this:
[u'red_scrubs',
 u'rmuchmor',
 u'Magic_Mych',
 u'vvaldiv',
 u'serenawilliams',...]

am i supposed that "u" in the beginning of each user name?

**Comment by aronwc** [comment]
Yes, that just means the strings are in unicode (as opposed to, e.g., ascii
encoding).

More here: <
http://stackoverflow.com/questions/11279331/what-does-the-u-symbol-mean-in-front-of-string-values
>

**Comment by ramyarao242** [comment]
Hi,
when i am trying to get friends for 'HillaryClinton' I am getting everything about HillaryClinton in the output, and not just the friend's list. Although i am sending only friend's list request . Why is this happening?

**Comment by aronwc** [comment]
My guess is you are using the wrong API request. It should be "friends/list."

**Comment by FatemaT** [comment]
Oh it's the friend/ list I had the same thing but you have to only add the screen_name from that output  to the returned list

**Comment by ramyarao242** [comment]
Hi,

I used the same API,as told, and now when i am trying to return screen_name of user, i get an error saying  : 
KeyError: 'users'.
why a\is this happening, we have to return user's screen _name .

**Comment by aronwc** [comment]
KeyError means your trying to access a dictionary value using a key that
does not exist in the dictionary.
I would print out the keys for the object to see if it what you expect.
Yes, you want to return a list of screen_name strings.

**Comment by ramyarao242** [comment]
Hi,
Yes got solution for this error. I was just trying to access users within
another loop.. Which was not required at all.
