### ISSUE TITLE
collect.py Run time

### ISSUE THREAD

**Issue by randalkwok** [iit-cs579/main#442]
How long are we allowed to collect data for? 

If I'm making my graph using common friends on Twitter as an edge and Twitter limits 15 requests every 15 minutes for friends, that means I have to collect data for 24 hours to get the friends of 1440 users right?

Is this unreasonable since you will be running our collect.py? Should I use less users? It will take an hour to get the friends of only 60 users.

**Comment by aronwc** [comment]
If your collect code is written in such a way that I can stop it after a few minutes and still get some output to use in the other files, that would be helpful.
For your main analysis, you can run it longer.

**Comment by SyedHamdanSher** [comment]
Mine takes around 8 hours. I am just storing all the data into .pkl files so that I don't have to re-run Twitter API and deal with rate limits.

**Comment by EFA16SCM55A** [comment]
I think to get the best analysis, we need to collect more and more data but it takes time and I have many things to deal with so I limited the count of the data that I need to collect to overcome the time problem.
