### ISSUE TITLE
a4 lexison question

### ISSUE THREAD

**Issue by suuuf** [iit-cs579/main#443]
For classification can we use a third part lexicon or should we make our own lexicon?

**Comment by pmedrano1** [comment]
I am interested in this as well. Professor said in the description of a4: "You may use any of the algorithms in scikit-learn, networkx, scipy, numpy, nltk to perform your analysis".
But can we use others like TextBlob for example?

**Comment by aronwc** [comment]
I recommend training a text classifier for this part. You can use any python library that allows you to train a text classifier.
