### ISSUE TITLE
code implementation

### ISSUE THREAD

**Issue by mellodi** [iit-cs579/main#444]
Is there any limitation on how we should or should not, implement our code? For example, can we use libraries even for tokenizing and featuring?

**Comment by EFA16SCM55A** [comment]
He mentioned that we can use the library in classification part when he answered a student , so I think we can use what we want-. I myself have reused some codes from class notes and a0&a1&a2+python library to progress in this assignment; I didn't start from a scratch for 90% of the tasks in this assignment. The only problem in this assignment is the time, to write to file, to collect the data that won't change with time and make sure it won't be against our analysis if it is changed. Others part  is like review and use the awesome python library.
