### ISSUE TITLE
Bonus Assignment Question

### ISSUE THREAD

**Issue by echibe** [iit-cs579/main#445]
How should we submit the bonus assignment? Copy it to our private repos?

**Comment by SyedHamdanSher** [comment]
I have similar question should we do a pull request to the master repo (main) ?

**Comment by SanchayanMaity** [comment]
I believe one can just push stuff to one's own private repo.

**Comment by aronwc** [comment]
Yes. Just push to your private repo like the other assignments.
You can either manually create the bonus directory, or you can pull directly from the [assignments repo](https://github.com/iit-cs579/assignments/) using (execute from the root of your private repo on your local machine):
```sh

git remote add template https://github.com/iit-cs579/assignments
git fetch template
git merge template/master
```

**Comment by dkaramchandani** [comment]
For people who dont know how to create bonus directory, use the below instructions:
1. Navigate to your private repository
2. Click on Upload files
3. Drag and drop the entire folder containing the bonus.py file. 
4. Enter your comments and hit submit.
Ensure to have at least 1 file for this to work.

**Comment by Flywomen** [comment]
Okay, thank you very much!
