### ISSUE TITLE
abt the edge we need to consider in the bonus question

### ISSUE THREAD

**Issue by jubeater** [iit-cs579/main#448]
In the bonus.py file, it seems that we only need to consider the already exist edge(node and it's nei) in the networkx graph and score them.
While in the example (abt the JB and band) given in the bonus.md file. It seems is also possible to contains a jaccard socre between the two nodes that not directly connected. Do we need to considering that?

**Comment by aronwc** [comment]
The point is to score potential new edges for the specified node. So, the method should return scores for all edges that don't yet exist in the graph containing the specified node as one endpoint.

So, if the node is A, and the graph contains nodes A,B,C,D and an edge already exists between A and B, then the method should return scores for edges AC and AD.

**Comment by aronwc** [comment]
Yes.

**Comment by jubeater** [comment]
thx professor

**Comment by jubeater** [comment]
professor, sry to bothering u again
For the jaccard score for the nodes without common friends, what's is the format of the 0?
can i just assign 0 , like (('E', 'A'), 0) in the final list?
or i need assign it to float value round to some digits, like (('E', 'A'), 0.0)?

**Comment by aronwc** [comment]
It is a float.

**Comment by jubeater** [comment]
so did that mean it's okay to assign the zero value to "0.0"?

**Comment by aronwc** [comment]
I don't really understand your question, but the second value is a float. If you represent the value 0 as a float, then you're fine.

**Comment by jubeater** [comment]
thanks you, professor. i have thought there may be a difference between float value "0.0" and float 
value "0.000".
