### ISSUE TITLE
Can the Jaccard value be > 1?

### ISSUE THREAD

**Issue by nith1989** [iit-cs579/main#452]
Can the value we get for 2 nodes be greater than 1 in this form of Jaccard?

**Comment by nith1989** [comment]
I got my answer - no! Thanks

**Comment by nith1989** [comment]
No, I seem to be getting values greater than 1 in some cases.

**Comment by nith1989** [comment]
I realized a minor mistake in my code - my values are below  now. Thanks.

**Comment by RanadeepP** [comment]
Hi,Could you tell me why the values are to be less than zero?I am asking this because i have a scenario where it is coming more than one.I have worked it out by hand according to the formula.
