### ISSUE TITLE
Can Jaccard values be >1?

### ISSUE THREAD

**Issue by Cheths** [iit-cs579/main#453]
I have Jaccard scores more than 1 for a  few edge combinations.
Is this incorrect?

**Comment by nerdySingh** [comment]
even i am getting values > 1and most of them are coming 0 can anyone give an update>?

**Comment by RanadeepP** [comment]
Same here.But it happened in a rare case.

**Comment by Cheths** [comment]
@aronwc 
Professor,
could you please clarify?

**Comment by aronwc** [comment]
It is up to you to figure out if the formula permits values > 1.
-Aron

**Comment by sparkkid1234** [comment]
@RanadeepP  I don't think it's that rare, considering the formula in the pdf, which is the sum of the inverse of degree divided by the inverse of the sum of the degree. I think it's pretty likely for the numerator fraction to be larger than the fraction in the denominator, thus making the score > 1

**Comment by Cheths** [comment]
Thanks Professor!
