### ISSUE TITLE
nosetest doctests fails for print_num_friends and followed_by_hillary_and_donald methods

### ISSUE THREAD

**Issue by leochirag** [iit-cs579/main#459]
1. doctests for the above two mentioned methods fail individually after several attempts, but when testing through all methods collectively using "python -m doctest a0.py" **shows all tests passed 0 tests failed**. My program returns everything and matches the Log.txt output though.

2. Secondly, what happens if the friends of the candidates change during the course of assignment submission and fails to match the number in Log.txt ?

Any help would be appreciated.

Thanks,
Chirag

**Comment by sramesh16** [comment]
Hi Chirag,
Just saw a mail from you and thought of asking you for some help.
I am having trouble creating Twitter-app. This is needed for getting tokens.
If you have been throgh this step, could you please guide me.
my email-is is sramesh16@hawk.iit.edu we can do a chat if you are available.

Thanks and Regards,
Ramesh S

**Comment by leochirag** [comment]
@sramesh16 Did it get solved ? Were you able to generate the tokens ?

**Comment by sramesh16** [comment]
Yes I got the Tokens. Give the github url and completed.
I am having trouble reading the candidate.txt it is not printing the names
of candidates. I am in the process of debugging the same.

Thanks and Regards,
Ramesh S
