### ISSUE TITLE
Error on running given function bipartisan_count()

### ISSUE THREAD

**Issue by syembadi** [iit-cs579/main#46]
Any one facing this issue with this function? (I made no changes to the code in this function)

TypeError: unhashable type: 'dict'
----> 5         print('%20s %d' % (r, len(set(democrats) & set(candidate2friends[r]))))

![image](https://cloud.githubusercontent.com/assets/11398180/9672079/233e50a8-525d-11e5-8ecd-8cc33a0aa2b0.png)

**Comment by FatemaT** [comment]
I had the same problem at first .. Make sure your get_friend method is returning a list of the friends names and not dictionaries

**Comment by syembadi** [comment]
Yeah, good catch. Solved my bug, thank you.
