### ISSUE TITLE
a2    def cross_validation_accuracy(clf, X, labels, k)

### ISSUE THREAD

**Issue by qiaoxiaoqiao1** [iit-cs579/main#461]
When I run cross_validation_accuracy,I face some error:
![error](https://user-images.githubusercontent.com/42417485/53996928-e4255200-40ff-11e9-86e2-fd9a6256a865.png)

Is there anyone can help me identify what's wrong?

**Comment by aronwc** [comment]
Hi,
First, please don't post your solution code here (or send to others).
Second, it looks like wherever you are calling the `cross_validation_accuracy` function, you are not passing in any of the required parameters (`clf, X, labels, k`)

**Comment by qiaoxiaoqiao1** [comment]
I figured it out.
It's because the docstring of this function does not contain doctest, thus I can't use nosetests to test it. I should create my own doctest for this function. 
Thanks, Professor! @aronwc
