### ISSUE TITLE
Questions about tokenize function

### ISSUE THREAD

**Issue by nrj5k** [iit-cs579/main#462]
Hello 

So how should the sentence ```this song is great mary-jane and to quote voltaire "with great power comes great responsibility".``` be tokenized, with and without punctuations? 
Just to understand how the output is expected to be.

Thank you

**Comment by qiaoxiaoqiao1** [comment]
I think the difference between with and without punctuations is mary-jane, the token should be "mary" "jane" without punctuations, the token should be "mary-jane" with punctuations.

**Comment by nrj5k** [comment]
and what about with, will it be ```"with``` or ```with```?

**Comment by qiaoxiaoqiao1** [comment]
with, because punctuation " is not inside of a word

**Comment by aronwc** [comment]
Correct

**Comment by nrj5k** [comment]
Awesome, thank you.

**Comment by vjstark** [comment]
If characters like $,&, @ occur within a word do we need to keep these wile keep_punct is true or ignore them.
Also, while using regex if the sentence has --mary-jane--, the returned value is --mary-jane-- when keep_punct is true. Is this valid or do we remove trailing and leading -.

**Comment by aronwc** [comment]
> If characters like $,&, @ occur within a word do we need to keep these wile keep_punct is true or ignore them.
keep

> Also, while using regex if the sentence has --mary-jane--, the returned value is --mary-jane-- when keep_punct is true. Is this valid or do we remove trailing and leading -.

remove trailing and leading - (so, output is `mary-jane`)
