### ISSUE TITLE
token_pair_features function

### ISSUE THREAD

**Issue by agericke** [iit-cs579/main#465]
Does this function ignore case? Or should we take into account?

For example if I have:
`token_pair_features(np.array(['i', 'love', 'LOVE']), feats)`
The output should be:
` sorted(feats.items())`
`[('token_pair=i__love', 1), ('token_pair=i__LOVE', 1), ('token_pair=love__LOVE', 1)]`
Or:
 `sorted(feats.items())`
`[('token_pair=i__love', 2), ('token_pair=love__love', 1)]`

**Comment by aronwc** [comment]
The first.

**Comment by vgandhi5** [comment]
Shouldn't it be
`[('token_pair=i__LOVE', 1), ('token_pair=i__love', 1), ('token_pair=love__LOVE', 1)]`
because of sorting?

**Comment by aronwc** [comment]
yes; though notice that I'm not asking you to sort inside of `token_pair_features`; that's just for the doctest.
