### ISSUE TITLE
min_freq and vocab in vectorize() clarification

### ISSUE THREAD

**Issue by dwhwang** [iit-cs579/main#468]
I would like some clarification on min_freq and vocab:

If a feature didn't meet min_freq requirement:

- When vocab is none, do we keep it in the vocab?
- When vocab is given, do we delete the feature from the vocab or keep it in the vocab?

The result csr_matrix will be slightly different. 

I'm leaning toward keeping features in both case, but clarification would be helpful.

----

Example: min_freq = 2

| A | B | C | D |
| --- | --- | --- | --- |
| 3 | 1 | 2 | 0 |
| 0 | 0 | 1 | 1 |
| 4 | 0 | 0 | 0 |

- case 1: vocab is none and keep feature in vocab
vocab: {A:0, B:1, C:2, D:3}
matrix: [
[3 0 2 0]
[0 0 1 0]
[4 0 0 0]]

- case 2: vocab is none and drop feature in vocab
vocab: {A:0, C:1}
matrix: [
[3 2]
[0 1]
[4 0]]

- case 3: vocab is given and keep feature in vocab
vocab: {A:0, B:1, C:2, D:3, E:4, F:5}
matrix: [
[3 0 2 0 0 0]
[0 0 1 0 0 0]
[4 0 0 0 0 0]]

- case 4: vocab is given and drop feature in vocab
vocab: {A:0, C:1}
matrix: [
[3 2]
[0 1]
[4 0]]

**Comment by aronwc** [comment]
min_freq is only used when vocab is None.
If a feature does not appear at least min_freq times, do not include it in vocab (or in the returned feature matrix).

**Comment by dwhwang** [comment]
Thank you!
