### ISSUE TITLE
Error while running the nosetest

### ISSUE THREAD

**Issue by sunnymodi21** [iit-cs579/main#469]
I ran nosetest using the following command:
`nosetests --with-doctest a2.py`

The following error was displayed:
`TypeError: parse_test_data() missing 2 required positional arguments: 'best_result' and 'vocab'`

**Comment by vgandhi5** [comment]
Some methods don't contain doctests as the results will vary because of randomized splits.
You can try running the main method to see if your output matches Log.txt.

**Comment by qiaoxiaoqiao1** [comment]
So you mean as long as our output match Log.txt, we don't need to modify anything even we have this error? @vgandhi5

**Comment by aronwc** [comment]
It is because of this:
https://github.com/iit-cs579/main/issues/290

This can safely be ignored. Workaround is to instead run
`python -m doctest a2.py`
