### ISSUE TITLE
Does token_pair_features across to the next document?

### ISSUE THREAD

**Issue by ChenMetanoia** [iit-cs579/main#472]
In tokenize method, we token every word in documents as a token which means it will generate a token array across to every document. 

For example, 
docs = ["Isn't this movie great?", "Horrible, horrible movie"]
print(tokenize(docs, keep_internal_punct=True))
["isn't", 'this', 'movie', 'great', 'horrible', 'horrible', 'movie']

However, In token_pair_features, should we consider the combinations that across the first document to the second document?
Like,
token_pair_features(tokens, feats, k=3):
[('token_pair=great__horrible', 0),
 ('token_pair=horrible__horrible', 1),
 ('token_pair=horrible__movie', 2),
 ('token_pair=isn__t', 3),
 ('token_pair=isn__this', 4),
 ('token_pair=movie__great', 5),
 ('token_pair=movie__horrible', 6),
 ('token_pair=t__movie', 7),
 ('token_pair=t__this', 8),
 ('token_pair=this__great', 9),
 ('token_pair=this__movie', 10)]

you  can see ('token_pair=great__horrible', 0), 'great is in the first document but horrible is in the second document.

**Comment by aronwc** [comment]
No, the token_pairs only consider tokens from the same document.

**Comment by ChenMetanoia** [comment]
Thank you so much professor!
