### ISSUE TITLE
eval_all_combinations doubt

### ISSUE THREAD

**Issue by agericke** [iit-cs579/main#475]
when computing cross_validation_accuracy for each possible combination, how many cross-validation folds should we pass to the function cross_validation_accuracy?

**Comment by aronwc** [comment]
5

**Comment by ddabhane** [comment]
Hi Professor,

I’m Illinois Tech Alumini.

Can you please remove me from this group?

Thanks,
Darshan

**Comment by aronwc** [comment]
Hi @ddabhane You need to click "unwatch" on the repo to stop receiving updates:
https://github.com/iit-cs579/main
Best,
Aron
