### ISSUE TITLE
a2.py main() output

### ISSUE THREAD

**Issue by Rodaina96** [iit-cs579/main#476]
Hello Professor,
Everytime I run the main function I get this error " X has 17925 features per sample; expecting 17698". I don't know from where this might have orginated from. I also wanted to ask if all the output numbers should much exactly the numbers in the log.txt or there could be some small variations.

**Comment by sramesh16** [comment]
Rodiana:
I faced a similar problem yesterday. After spending some time I figured that I was not using the Vocab that gets built properly.  The vocab should be built in the training phase. It should be used in test phase in read-only mode. I ignored any words that were not found in the vocab. Once I started using the Vocab in the test set, I was able to get a proper match. I hope this helps.
regards,
Ramesh S.
