### ISSUE TITLE
Are small changes allowed in the given code?

### ISSUE THREAD

**Issue by mamtakanvinde** [iit-cs579/main#48]
# separate candidates by party.
republicans = [c[0] for c in candidates if c[1] == 'R']
democrats = [c[0] for c in candidates if c[1] == 'D']
print('%d republicans, %d democrats' % (len(republicans), len(democrats)))

This doesnt work for me.
c[0] loops through each elem of the string and not  each candidate. For example, [c[0] for c in candidates if c[1] == 'R'] processes the elements as follows:
H
I
L
A
R
Y
C
L
I
N
T
O
N

....

I get the correct output for this code after modifying it as follows:
republicans = [c.split(' ')[0] for c in candidates if c.split(' ')[1] == 'R']
democrats = [c.split(' ')[0] for c in candidates if c.split(' ')[1] == 'D']
print('%d republicans, %d democrats' % (len(republicans), len(democrats)))

similarly for the code:
candidate2friends = get_all_friends(c[0] for c in candidates) I had to change it to--

candidate2friends = get_all_friends(c.split(' ')[0] for c in candidates)

Is this fine?

**Comment by shreeshbhat** [comment]
You must have constructed candidates wrong. It should be a list of (string,
string ) tuples.

**Comment by mamtakanvinde** [comment]
okay.. got that. Thanks
