### ISSUE TITLE
[a0] read_screen_names() doctest test case

### ISSUE THREAD

**Issue by ppttzhu** [iit-cs579/main#480]
According to instruction:
`Returns: A list of strings, one per screen_name, in the order they are listed in the file.`

However the sequence given by test case is wrong:
`>>> read_screen_names('candidates.txt')`
`['BernieSanders', 'JoeBiden', 'SenWarren', 'realDonaldTrump']`

According to candidates.txt, it should not be alphabetical ordered:
`['realDonaldTrump', 'SenWarren', 'BernieSanders', 'JoeBiden']`

Note that we will sort the output in main()

**Comment by aronwc** [comment]
Clarified instructions to sort alphabetically.
https://github.com/iit-cs579/assignments/commit/176823121ffd675daadcb41c1184325fc0c202f1#diff-bc8bafe2318bafd2e188af0fbd013009

**Comment by ppttzhu** [comment]
Thanks professor, that
