### ISSUE TITLE
[a0] typo in ShortAnswer.txt: no followed_by_hillary_and_donald function

### ISSUE THREAD

**Issue by ppttzhu** [iit-cs579/main#482]
There is no followed_by_hillary_and_donald function in a0, I guess you mean followed_by_bernie_and_donald.

Not sure whether I should post typo in Issues or just send a private Email to professor next time?

Best regards,
Yixin

**Comment by aronwc** [comment]
fixed, thanks!
https://github.com/iit-cs579/assignments/commit/851c25551fdf0fc00bf17222fce9dc876170b9d2

**Comment by ppttzhu** [comment]
Thanks professor, I'll close this issue.
