### ISSUE TITLE
Twitter Request Failed Error

### ISSUE THREAD

**Issue by lakshmyu** [iit-cs579/main#49]
Hi,
I am getting a Twitter Request Error : Twitter Request Failed error when giving higher counts like 200. For smaller counts, I am getting the output. Is this because of any connectivity problem to the Twitter or some issue with the code? Is there any way I can get rid of this error?

Thank You

**Comment by aronwc** [comment]
Try printing the response object you get back (e.g., response.text) to see the specific error message and text. You should be able to set `count` to a maximum of 200.
