### ISSUE TITLE
A typo in l07

### ISSUE THREAD

**Issue by ppttzhu** [iit-cs579/main#491]
Hi professor, I found a typo in l07.ipynb, cell#: In [30]
`prediction = filter_existing_edges(prediction, train_graph, author)[:7]`
should be
`prediction = filter_existing_edges(prediction, train_graph, author)[:6]`
for top 6 predictions.

![image](https://user-images.githubusercontent.com/44450843/65177476-5e724f80-da1c-11e9-8c4b-5566694a0ea7.png)

**Comment by aronwc** [comment]
fixed, thanks!
