### ISSUE TITLE
data types in  csr matrix 

### ISSUE THREAD

**Issue by annonch** [iit-cs579/main#493]
Curiously using example code from the link in A2 

The expected behavior differs from observed. Using int64 does not print the dtype information however int8 does.

Am I missing something?

```
>>> from scipy.sparse import *
>>> from scipy import *
>>> csr_matrix((3,4),dtype='int64').toarray()
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])                                                            # Error
>>> csr_matrix((3,4),dtype='int8').toarray()
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)                                             # no error
>>> import numpy as np
>>> csr_matrix((3,4),dtype=np.int64).toarray()
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])
```

**Comment by aronwc** [comment]
I wouldn't worry about the dtypes for this assignment.
-Aron

**Comment by annonch** [comment]
Okay, just that my test for 'vectorize' will fail...  My guess is platform dependency or version number.. Anyone else see this for osx? I use ports to install everything and pip for python packages.
