### ISSUE TITLE
Definition of Final step in Girvan-Newman

### ISSUE THREAD

**Issue by ppttzhu** [iit-cs579/main#496]
I found the definition of 'Girvan-Newman algorithm final step' in l05 ambiguous. Wish to have more information if it's in the midterm.

1) According to the definition in l05: 
![image](https://user-images.githubusercontent.com/44450843/66727055-731aeb00-ee02-11e9-8749-0c7bb44b932d.png)
The final step for Girvan-Newman should be repeating until there are k clusters.

2) I would not consider the following step as the final step of Girvan-Newman algorithm, because this is just one step in computing betweenness: calculating credit of edges for one source node. 
![image](https://user-images.githubusercontent.com/44450843/66727117-be34fe00-ee02-11e9-941c-a61e762c2011.png)

Noticed that this screen-shot is from Mining of Massive Datasets, however, below definition of Girvan-Newman algorithm is not consistent with our lecture note or [wiki](https://en.wikipedia.org/wiki/Girvan%E2%80%93Newman_algorithm).

![image](https://user-images.githubusercontent.com/44450843/66727498-45837100-ee05-11e9-9f49-5da5a67c05d2.png)

**Comment by aronwc** [comment]
The caption for figure 10.6 could be expanded to say “the final step to compute the betweenness values for one iteration of Girvan newman”.
It is true that this is run many times until k clusters are found.

**Comment by ppttzhu** [comment]
> The caption for figure 10.6 could be expanded to say “the final step to compute the betweenness values for one iteration of Girvan newman”. It is true that this is run many times until k clusters are found.
> […](#)
> On Oct 13, 2019, at 10:07 PM, Yixin Peng ***@***.***> wrote: ﻿ I found the definition of 'Girvan-Newman algorithm final step' in l05 ambiguous. Wish to have more information if it's in the midterm. According to the definition in l05: The final step for Girvan-Newman should be repeating until there are k clusters. I would not consider the following step as the final step of Girvan-Newman algorithm, because this is just one step in computing betweenness: calculating credit of edges for one source node. Noticed that this screen-shot is from Mining of Massive Datasets, however, below definition of Girvan-Newman algorithm is not consistent with our lecture note or wiki. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

“the final step to compute the betweenness values for one iteration of Girvan newman” is not accurate, because the final step to compute the betweenness values should be:
![image](https://user-images.githubusercontent.com/44450843/66728209-1a028580-ee09-11e9-8313-558175193663.png)

**Comment by aronwc** [comment]
Yes I’m
