### ISSUE TITLE
Project Folder

### ISSUE THREAD

**Issue by rlakde** [iit-cs579/main#498]
Hi Professor,

Where exactly we need to integrate our code in the folder structure given? Can you please give us some guidance on how the files in the given folder are linked and which files we need to update?

Thanks,
Rohit

**Comment by aronwc** [comment]
I discussed this in two separate lectures (I believe it's 10/16 and 10/23, but I may be off by one). See the [instructions](https://github.com/iit-cs579/sample-project/blob/master/Instructions.md).
In short, I've given you stubs for 6 commands, which I will run to grade your project. How you do this is up to you.

**Comment by rlakde** [comment]
Thank you very much, Professor :)
