### ISSUE TITLE
Expected shape/orientation of drawn graph?

### ISSUE THREAD

**Issue by carolgrrr** [iit-cs579/main#50]
This is a similar questions to #47, regarding the network changing every time you run the code.

I have drawn a graph that *seems* very close to the example in the sample code. But if I run the code again by creating a new graph and drawing it, the orientation of the nodes and edges changes slightly. I am using a digraph, so the resolution from #47 does not apply to my question.

1st example:
<img width="530" alt="g1" src="https://cloud.githubusercontent.com/assets/4088293/9722541/aea1d61e-5574-11e5-8c0c-c474f7a34a72.png">

2nd example:
<img width="518" alt="g2" src="https://cloud.githubusercontent.com/assets/4088293/9722542/b2d59a54-5574-11e5-93b6-696b431b5c90.png">

3rd example:
<img width="520" alt="g3" src="https://cloud.githubusercontent.com/assets/4088293/9722543/c14c821e-5574-11e5-83cc-7b08f822b8df.png">

All of these graphs have the same number of nodes and edges, but as you can see they look different. Is this behavior expected? Or is there a better way to create the graph that will result in it being drawn consistently each time?

**Comment by carolgrrr** [comment]
I just saw #42 , which answers my question. Closing issue.

**Comment by shreeshbhat** [comment]
This is expected behavior.

**Comment by aronwc** [comment]
Expected behavior.

**Comment by jiranun** [comment]
I knew that the graph would always be generated in different way, but I have a problem with my graph. It seems like the node are overlapped by each other. I have the same number of nodes and edges, but it looks ugly :( Anybody knows the reason?

![screen shot 2015-09-07 at 5 05 42 pm](https://cloud.githubusercontent.com/assets/13938351/9723252/c2958496-5582-11e5-9238-99ad228e5d6d.png)

**Comment by shreeshbhat** [comment]
There must be a bug in your create_graph method. Please recheck the logic.

**Comment by jiranun** [comment]
Does the order of adding nodes and edges effect the graph? 

The graph has 130 nodes and 276 edges now. It seems like the degree of each node are quite similar to the sample code. I really have no idea if there's a bug

Anyway, thank you. I will try to find the bug again

**Comment by shreeshbhat** [comment]
Order of adding nodes will effect graph a little. When we add nodes after
getting values from dictionary, the dictionary doesn't give us values in a
sorted manner. But, for you, the structure of graph is quite different. So,
i m concluding that your logic might be having a bug.
Sorry, someone else can give a better insight to this.
