### ISSUE TITLE
result return by twitter api is not in a proper format

### ISSUE THREAD

**Issue by shivakumar-15** [iit-cs579/main#51]
Hi,
The twitter api call for friends/list returns result as a class 
this class contains attribute text which contains the raw data in unicode format
when i simply print it shows a dict
but not able to access the elements in it
it says " TypeError: string indices must be integers "
so when i look at the type it says unicode
so how to convert to dict or is there any other way to access it

**Comment by JaySurplus** [comment]
Hi, 
I returns a list of dicts, [{dic1:} , {dic;2} ... ] , you should access a `value` by using `dic['key']` , 
Check the following link to check all available parameters :
     https://dev.twitter.com/rest/reference/get/friends/list

**Comment by mamtakanvinde** [comment]
json() function of TwitterAPI will give you the data in unicode format. Then you can access all the contents of the data through dictionary keys. For example 

data=twitter_response.json()
id=data['id']
if there are nested dictionaries you can use access a particular value by using data['key1']['key2']
