### ISSUE TITLE
problem with reading twitter.cfg in Windows 7

### ISSUE THREAD

**Issue by pavithrachandrakasu** [iit-cs579/main#52]
Dear Aron,

I have read the issue related to this in GitHub but my issue seems quite different from that one.

If I hard code my twitter credentials(keys) in twitter_request method. My entire code is working fine. 

But if use twitter.cfg file I am facing issue in my get_friends() method like below: 

C:\Users\dell\Anaconda\lib\site-packages\TwitterAPI\TwitterAPI.pyc in __iter__(self)
    177         :raises: TwitterConnectionError, TwitterRequestError
    178         """
--> 179         return self.get_iterator()
    180 
    181     def get_rest_quota(self):

C:\Users\dell\Anaconda\lib\site-packages\TwitterAPI\TwitterAPI.pyc in get_iterator(self)
    164         """
    165         if self.response.status_code != 200:
--> 166             raise TwitterRequestError(self.response.status_code)
    167 
    168         if self.stream:

TwitterRequestError: Twitter request failed (401)

When I reviewed this error, it looks like Unauthorized access or Time zone issue. 

But if it is Unauthorized access, then it should not work if I hard code my values. My time zone is correct. I have cross verified it. 

Please let me know what can be done to resolve this.

**Comment by JaySurplus** [comment]
Have you sync your sys time ?  Also can you push your current code to github then i can take a look ?

**Comment by pavithrachandrakasu** [comment]
I have re created my twitter.cfg again. It is working fine now. Thanks a lot for your time.

**Comment by JaySurplus** [comment]
Good to hear,  then I will close this issue.
