### ISSUE TITLE
Different graph diagram

### ISSUE THREAD

**Issue by nithinrajeev** [iit-cs579/main#53]
I have been facing an issue with the graph. I was getting the correct nodes and edges but my final output was coming as follows. I am using a Mac so I executed my same code on an Ubuntu laptop and my final output came exactly as you have posted in the sample output. I have attached both the screenshots. How should I proceed with this?
<img width="677" alt="screen shot 2015-09-09 at 2 04 12 pm" src="https://cloud.githubusercontent.com/assets/12204861/9771530/760eee34-56fc-11e5-96d6-e28d49740855.png">
Output on Ubuntu
![windows output](https://cloud.githubusercontent.com/assets/12204861/9771954/ed61b294-56fe-11e5-8d04-39cb2a78d9ae.png)

**Comment by jiranun** [comment]
I also have the same problem. I use macbook air.

**Comment by dhanashreek** [comment]
I am also facing the same issue. I am using Ubuntu 14.04

**Comment by aronwc** [comment]
It's possible you have slightly different versions of the libraries installed. 

Again, I wouldn't worry too much over the orientation of the graph, as long as you have the right number of nodes and edges and the arrows are pointing in the right directions.

**Comment by JaySurplus** [comment]
The graph could be slightly differently with each function calls/code runs.
