### ISSUE TITLE
confusion about the function "robust_request" in a1.ipynb

### ISSUE THREAD

**Issue by ZhaoWang-IIT** [iit-cs579/main#55]
I did not see when and where this function was called ?
Can we make this function run automatically? For example, I called Twitter API to get friends, and if it reaches the rate limit, then I have to wait for 15 minutes and click "run" to run it again. Can we make it run automatically 15 minutes later?

**Comment by benjaminwalters** [comment]
You would replace your "twitter.request" call with a call to robust_request. I think it takes an extra parameter (the twitter object). Now, if it gets an error message, it will wait 15 minutes and try again. But be careful, I don't think it checks the error type. So if you are receiving any other type of error (such as incorrect parameters), it will keep failing every 15 minutes.
