### ISSUE TITLE
Approximate time taken by girvan_newman()

### ISSUE THREAD

**Issue by karthikbmk** [iit-cs579/main#59]
Hello Professor,

What's the approximate time taken to execute Girvan_newman() ? I'm computing betweenness only once per call in this function, even then it's taking approximately 5 minutes to form clusters.
Is this fine , or should I try optimizing the code further ?

**Comment by mamtakanvinde** [comment]
It does not take so much time for me. max to max 2 minutes.

**Comment by jiranun** [comment]
It takes 2-3 minutes for me. I think it's ok if the result is correct.

**Comment by aronwc** [comment]
Yes, 5 or less should be about right.
