### ISSUE TITLE
Does girvan_newman's output has to be exactly same?

### ISSUE THREAD

**Issue by mamtakanvinde** [iit-cs579/main#60]
Its giving me the correct length of communities but gives me wrong number of removed edges.
my output of this algorithm is as follows:
removed 87 edges
componet sizes= [701, 11]
removed 90 edges
componet sizes= [695, 6]
removed 164 edges
componet sizes= [694, 1]
removed 1 edges
componet sizes= [693, 1]
removed 1 edges
componet sizes= [692, 1]
removed 1 edges
Is the output supposed to change? I guess not.

**Comment by aronwc** [comment]
Looks like you're not resetting the counter to 0 each iteration.
