### ISSUE TITLE
How many multiple communities are supposed to be formed before we recurse again?

### ISSUE THREAD

**Issue by prateekagrawal06** [iit-cs579/main#61]
Rather than recompute betweenness after each edge is removed,
      only compute betweenness once per call to this method. That is,
      compute betweenness once, remove edges until multiple connected
      components are formed, then recurse.

how many edges do we need to remove before we recurse again?

**Comment by jiranun** [comment]
Until the community is separated

**Comment by aronwc** [comment]
closing -- reopen if still unclear.
