### ISSUE TITLE
Error while reading edges.txt

### ISSUE THREAD

**Issue by lakshmyu** [iit-cs579/main#62]
Hi,
I am finding it difficult to read the edges.txt file to an undirected graph. I used read_edgelist() and getting the following error -  TypeError: Failed to convert edge data ([u'&', u'Writing', u'Awards']) to dictionary.
Could you please help me how to fix this issue?
Thank you

**Comment by aronwc** [comment]
The node bars are separated by tabs, not a space, so you'll need to adjust the call accordingly.

**Comment by dmartiinez** [comment]
when i split each file in the line into two nodes, and then try to add the edge it says that I have to call add edge with digraph instance and not a string. Is there a way to split the file so I don't get two strings? or to turn a string into an object?

**Comment by shreeshbhat** [comment]
We have to use undirected graph for this assignment. 
Try creating an undirected graph first and then loop over file adding nodes and edges.

**Comment by dmartiinez** [comment]
I know, but I would still be calling add_age with strings and that's where I get the error.

**Comment by shreeshbhat** [comment]
There must be something wrong with the splitting logic.
Have you tried printing the nodes and edges to see whether they are having expected values or not?

**Comment by dmartiinez** [comment]
yes I did and it prints out the correct things. I am using the split() method, splitting at a tab, which gives me two strings.

**Comment by shreeshbhat** [comment]
Hmm..Interesting. Please post the exact error message.

**Comment by dmartiinez** [comment]
TypeError: unbound method add_edge() must be called with Graph instance as first argument (got str instance instead)

**Comment by shreeshbhat** [comment]
Did you use graph_object_name.add_edge() ?

**Comment by dmartiinez** [comment]
yes. graph.add_edge(n1, n2)

**Comment by shreeshbhat** [comment]
See if the below link helps.
http://stackoverflow.com/questions/4473184/unbound-method-f-must-be-called-with-fibo-instance-as-first-argument-got-cla

**Comment by dmartiinez** [comment]
that's a different error..

**Comment by shreeshbhat** [comment]
I'm stumped. It seems like the same error to me. Re-check with the first assignment how you created graph and make sure there are no trailing spaces or '\n'.

**Comment by dmartiinez** [comment]
i figured it out. thanks! now i am getting graph has 5363 nodes and 6128 edges. any ideas.. I am simply reading each line and splitting it into two nodes and creating an edge between them. I do this for each line. since add_edge doesn't recreate an already existing edge this should work. I am not sure what is happening...

**Comment by shreeshbhat** [comment]
Cheers! What was the solution to the previous problem though?
Please create new issues rather than commenting on the same issue.
It might be related to strings not getting split based on tabs.

**Comment by FatemaT** [comment]
You have to remove the repeated edges. I got the same before but I fixed it by removing the repeated one by repeated I mean there would be two edges such as (x,y)and (y,x) those are the same so check for that remove one of them.

**Comment by morlowsk** [comment]
You need to get rid of the '\n\ character that exists at the back of every line. Simply remove it with:
`strip('\n')`

**Comment by morlowsk** [comment]
You need to get rid of the '\n' character that exists at the back of every line. Simply remove it with:
strip('\n')

**Comment by dmartiinez** [comment]
it should not be creating duplicate edges if its an undirected graph..I checked that this is the case.

**Comment by FatemaT** [comment]
As another student mentioned removing \n by the strip method fixes the problem cause you see there are edges (x,y) (y,x) where x in the second edge has /n at the end and y in the first has /n so if you removed /n it's back to being the same and would be automatically removed.

**Comment by dmartiinez** [comment]
stripping the \n worked..thanks. I am guessing that it was treating the same node twice when one was saved as "node", and the other as "node\n"

**Comment by shreeshbhat** [comment]
@dmartiinez  : Please share the solution of the previous problem (TypeError) you faced.

**Comment by dmartiinez** [comment]
It was so simple..I had just forgot to add () in graph = nx.Graph()

**Comment by shreeshbhat** [comment]
Aah okay.

**Comment by lakshmyu** [comment]
Thank you Professor and friends!!
