### ISSUE TITLE
Difference in normalized cut value

### ISSUE THREAD

**Issue by shreeshbhat** [iit-cs579/main#64]
I am getting different values for normalized cut value as compared to the expected values.
I manually checked the calculation of norm_cut_values using volume & cut-set and it is doing that correctly.
Is there a way to cross verify whether volume and cut-set is correct or not?

Expected:
[0.5394522186431889,
 0.7112986541855564,
 0.6125866583993509,
 0.7394497863247863,
 0.38487710745480397,
 0.169372331833391]

My result:
[0.33504093630249776,
 0.48990899700932306,
 0.38770081496204645,
 0.5461770705834353,
 0.23238345494707968,
 0.09201583708972871]

**Comment by karthikbmk** [comment]
cut  V(S)  V(T)        NCV
153	349	1514	0.539452219
170	281	1599	0.711298654
195	404	1501	0.612586658
98	144	1664	0.739449786
39	108	1641	0.384877107
17	107	1620	0.169372332

**Comment by shreeshbhat** [comment]
Thanks! Looks like my volume calculation is wrong.
