### ISSUE TITLE
score_clusters()

### ISSUE THREAD

**Issue by dmartiinez** [iit-cs579/main#65]
Is this supposed to take some time to compute?

**Comment by shreeshbhat** [comment]
Check : https://github.com/iit-cs579/main/issues/59

**Comment by shreeshbhat** [comment]
Sorry, no, it will take less time.

**Comment by dmartiinez** [comment]
Do we need to print output in same format with each ncv on a separate line?

**Comment by shreeshbhat** [comment]
It will automatically do that. We just have to return a list of float values representing each ncv.

**Comment by dmartiinez** [comment]
I get a list but it's all on one line. Professor has it over several lines.

**Comment by shreeshbhat** [comment]
I am not understanding why it is printing in different lines by default when we return.
Are you trying to print score_clusters()?

**Comment by dmartiinez** [comment]
Ok. When I print it it prints [ncv1,ncv3,etc]
When professor print it its printing [ncv1,
                                                         Ncv2,..]

**Comment by dmartiinez** [comment]
Each ncv is on a separate line... Look st his output.

**Comment by shreeshbhat** [comment]
You can try pprint. But, weirdly, I am not using that and still it is printing in different lines.

**Comment by dmartiinez** [comment]
Ummm. I wonder why mine isn't.

**Comment by shreeshbhat** [comment]
Someone else can shed some light into this. Meanwhile, try pprint method mentioned in one of the lectures.

**Comment by guruosna** [comment]
@dmartiinez: just try returning the ncv instead of printing it, you will get it separate lines

**Comment by aronwc** [comment]
Yes, you should return ncv.
Notebooks automatically use [pretty print](https://docs.python.org/2/library/pprint.html) when you evaluate a variable directly, rather than printing it. E.g.:

```python
a = score_clusters(result, subgraph)
print(a)
[0.5394522186431889, 0.7112986541855564, 0.6125866583993509, 0.7394497863247863, 0.38487710745480397, 0.169372331833391]
```

versus

```python
score_clusters(result, subgraph)
[0.5394522186431889,
 0.7112986541855564,
 0.6125866583993509,
 0.7394497863247863,
 0.38487710745480397,
 0.169372331833391]
```

**Comment by aronwc** [comment]
closing -- reopen if still unclear.
