### ISSUE TITLE
Second block under link prediction

### ISSUE THREAD

**Issue by dmartiinez** [iit-cs579/main#66]
anyone else getting a different output for this block. one of the edges differs for  me. instead of 
('Bill Gates', u'Sue Desmond-Hellmann'), I get ('Bill Gates', 'Team Gleason'),

also when i run jaccard accuracy I get .100 instead .200. anyone else get this?

**Comment by morlowsk** [comment]
I got those results as well.

**Comment by dmartiinez** [comment]
I figured out why but I'm confused about it. I need to Ask the professor. 

In the first box if you change edges to be removed to equal G_train.edges(test_node) it works. 

I'm confused because G_train is supposed to be a copy of subgraph so it should provide the same results no?

But if I you do G_train.edges(test node) we get the correct order for the first 10 edges. But if you do subgraph.edges(test node) you get the order we are getting which is different.

**Comment by aronwc** [comment]
The `edges()` method is accessing a `dict` in the `Graph` object. It's possible that your dictionary returns a different ordering than mine. From [the docs](https://docs.python.org/2/library/stdtypes.html#dict):

> CPython implementation detail: Keys and values are listed in an arbitrary order which is non-random, varies across Python implementations, and depends on the dictionary’s history of insertions and deletions.

I probably should have sorted these items first prior to picking the top 10 to ensure consistency.

So, please feel free to modify the way `edges_to_rem` is created to ensure it is the same set of edges as in the starter code.

**Comment by morlowsk** [comment]
So we can just hard code the edges to remove?

**Comment by aronwc** [comment]
If that's the only way for you to get the same list of edges, then sure.

**Comment by dmartiinez** [comment]
Ok. For me it works by simply changing edges_to_remove = subgraph.edges(test node) to
Edges_to_remove = G_train.edges(test node), so making this change is ok?

I am confused about that though because G_train is an exact copy of subgraph right? So shouldn't it give the same result?

**Comment by aronwc** [comment]
Sure, you can make that change if it works. I don't see why it would make a difference, but perhaps .copy does not preserve dictionary oder

**Comment by bpraveen92** [comment]
@dmartiinez  and @morlowsk  what did you guys do to solve this issue ?
