### ISSUE TITLE
girvan_newman() component size ?

### ISSUE THREAD

**Issue by bpraveen92** [iit-cs579/main#67]
How to estimate the size of a given component ? As the nx.connected_component_subgraph(graph) returns a generator object ? Is there any networkx function to do this ?

**Comment by shreeshbhat** [comment]
The method returns the connected components in graph. We can iterate over each element in that through a list comprehension and save it as "components".
Then, you can check each component's size by using degree function in network.

**Comment by shreeshbhat** [comment]
Sorry, use len() or number_of_nodes() instead of degree().

**Comment by shreeshbhat** [comment]
Refer : https://networkx.github.io/documentation/latest/reference/classes.graph.html#information-about-graph-structure

**Comment by bpraveen92** [comment]
Thanks!
