### ISSUE TITLE
order of the lengths of the cluster

### ISSUE THREAD

**Issue by prateekagrawal06** [iit-cs579/main#69]
Is it compulsory to have the list containing the length of the clusters be in the same order as the out put given by the professor ??
 I am getting the right lengths but in the different order

**Comment by aronwc** [comment]
Yes, please put it in the same order.
You may have to re-order where the recursive call occurs (e.g., before or
after you add a cluster to your result list).

**Comment by aronwc** [comment]
closing -- reopen if still unclear.
