### ISSUE TITLE
The unicode character 'u' removed from nodes

### ISSUE THREAD

**Issue by amitthakral** [iit-cs579/main#70]
After completing the read_graph() method, when I tried running the very next block which is sorting the nodes with highest degree first.
The output I received has unicode character removed from the nodes.
For example, I got ('ONE', 39) instead of (u'ONE', 39).

I don't know the reason. Will it make a difference in the output?

**Comment by aronwc** [comment]
Not sure why it only happens for one, but you can cast them all to unicode using the `unicode` builtin function:
```python
>>> s = 'hello'
>>> s
'hello'
>>> s = unicode(s)
>>> s
u'hello'
```

**Comment by jiranun** [comment]
I have the same issue. Do we need to cast it to unicode?

**Comment by aronwc** [comment]
Please do. Otherwise, you can alter your file reading code to read unicode
directly.

**Comment by bpraveen92** [comment]
I get 5216 nodes and 6060 edges if i try to change the strings encoding to unicode along with a warning message as below:
( C:\Users\Praveen\Anaconda\lib\site-packages\IPython\kernel\__main__.py:18: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal ) 
All other modules work fine except for the read_graph(). Is anyone facing similar issues ?

**Comment by aronwc** [comment]
All,

If you use the [read_edgelist](https://networkx.github.io/documentation/latest/reference/generated/networkx.readwrite.edgelist.read_edgelist.html) networkx method, it assumes utf-8 encoding by default. You shouldn't need to change encodings.

-Aron

**Comment by rbabayan** [comment]
I had the same problem. Try to read "edges.txt" file with codecs.open() function and then create the graph.

**Comment by bpraveen92** [comment]
that worked @rbabayan thanks!

**Comment by aronwc** [comment]
closing -- reopen if still unclear.

**Comment by amitthakral** [comment]
If we use codecs.open() function, we need to add import codecs in first block of assignment.

Is it fine if we modify the code?

**Comment by aronwc** [comment]
Sure.
