### ISSUE TITLE
Edge doesnt exist error in girvan_newman()

### ISSUE THREAD

**Issue by dmallass** [iit-cs579/main#71]
In girvan_newan() method, i am getting an error saying that

 graph.remove_edge(*edge_to_remove)
 NetworkXError: The edge Big History Project-Bill Gates is not in the graph. 

I am calculating the betweenness and trying to remove the edge with highest betweenness.

My graph has the exact same number of  nodes and edges ( 712 nodes and 1710 edges). When i iterated through the edgelist o subgraph, there exists no such edge. But then how the function calculates betweenness for an edge which does not exist.

Has anyone encountered with a similar issue ?

**Comment by bpraveen92** [comment]
see #72

**Comment by dmallass** [comment]
Worked
