### ISSUE TITLE
issue in remove_edge() method

### ISSUE THREAD

**Issue by ramyarao242** [iit-cs579/main#72]
While trying to remove edges with higher betweeness, i am getting the following error
NetworkXError: The edge (u'Bill Gates', u'Big History Project')-0.0912600035981 is not in the graph

any suggestions?

**Comment by bpraveen92** [comment]
may be due to the misplacement of remove_edge iterator. you might have initialized it within the while loop, so that as the girvan function gets called recursively there may not be an edge that has previously been removed

**Comment by ramyarao242** [comment]
hmmm.. but according to what i have understood, at first len(component) is = 1, then it enters the while loop and the edges get removed  and we find communities and when len is not equal to 1, depending on component sizes we either add it to the result or print it out,I am not clear as to how we can remove the edges before while?

**Comment by aronwc** [comment]
To clarify, you will recompute betweenness for each component found. E.g., if the original graph has nodes [1,2,3,4], a sample run may look like this:

```
compute betweenness for [1,2,3,4]
  remove edges (2,3), (1,4)
  split into [1,2], [3,4]
compute betweenness for [1,2]
  remove edge (1,2)
  split into [1], [2]
compute betweenness for [3,4]
  remove edge (3,4)
  split into [3], [4]
```
(This example ignores the min/max size issues.)

My guess is that the betweenness scores are being reused from earlier stages, rather than being recomputed for a sub-community.

**Comment by ramyarao242** [comment]
okay... i was computing betweenness all at once and storing in a dict and then trying to reuse it, okay got it.
