### ISSUE TITLE
facing confusion to calculate volume of set of nodes

### ISSUE THREAD

**Issue by ramyarao242** [iit-cs579/main#73]
Hi,
I know what volume is for a set of nodes, but to calculate the volume for a set of nodes,but for calculating the volume should i consider adjacency matrix or anything of that sort, or consider each node in the nodes list and check if it is present in the edges of the graph? am i thinking in the right direction or complicating things? Is there any in built function? any input will be greatly helpful.

**Comment by AndrewLu1992** [comment]
Read documentation of networkx and you will find out a way to implement the function.
