### ISSUE TITLE
doubt regarding calculation of jaccard_wt

### ISSUE THREAD

**Issue by ramyarao242** [iit-cs579/main#74]
According to my understanding I first create the tow sets A and B as in jaccard() method and then apply the summation formula.. right?

**Comment by carolgrrr** [comment]
I am also confused about this.

I think the numerator is the sum of all terms (1/deg(i)), for all nodes i in both A and B.

The denominator is the sum of 2 terms: (1/ sum of degree of all nodes i in A) and (1/sum of degree of all nodes j in B)

Is this accurate? I know I am currently calculating the jaccard scores incorrectly, but I'm not sure if the error is in my programming logic or my understanding of the computation given.

Thanks in advance.

**Comment by shreeshbhat** [comment]
@carolgrrr : Yes, you are correct.

**Comment by ramyarao242** [comment]
on re-running the jaccard method (not jaccard_wt) the accurracy which was 0.200 has changed to 0.100? I havent done any changes, any suggestions? did anybody face this issue..

**Comment by ramyarao242** [comment]
and also in jaccard_wt method, the way we find A and B is same as the way we get neighborsi and neighborsj right?

**Comment by carolgrrr** [comment]
Converting neighborsi into a graph isn't necessary. You can just use a list of nodes and iterate through them, referencing the original graph when you want to compute degree.

I haven't seen the output of the jaccard method change.

**Comment by ramyarao242** [comment]
thank you all for your inputs
