### ISSUE TITLE
volume and last cell output

### ISSUE THREAD

**Issue by jaydeeppatel1701** [iit-cs579/main#75]
volume argument is (S,graph)
don't we need T for volume because we have 100 nodes(considering 1st cluster) in S, T has 68+100+32+ 40+ 47=287 nodes while graph has 710 nodes.
I do have other way around but it is not working for last cell.
Otherwise we simply calculate v(s)=number of edges in s + cut set
So which solution should i opt for

**Comment by bpraveen92** [comment]
T is all the remaining nodes in the graph and not in the cluster.

**Comment by jaydeeppatel1701** [comment]
do you mean by Graph with 710 nodes or graph with 5062 nodes?
I think we have to consider only the output of girvan newman algorithm. because i am getting the same answer posted in #64

**Comment by bpraveen92** [comment]
The subgraph with 712 nodes, that is the argument that your passing to score cluster function isn't ?

**Comment by jaydeeppatel1701** [comment]
K. So I think I have to pass one cluster and remaing graph as volume function argument. Am i right?

**Comment by bpraveen92** [comment]
yes.

**Comment by jaydeeppatel1701** [comment]
K. Thanks man
