### ISSUE TITLE
different values appearing when running the output file

### ISSUE THREAD

**Issue by ramyarao242** [iit-cs579/main#76]
Hi,
when i am running the last output cell i am getting different output than the one posted. All my methods are working fine, with correct outputs, but this consolidated output is like this.
my output:
removed 1 edges
component sizes= [3, 4]
removed 1 edges
component sizes= [3, 4]
removed 1 edges
component sizes= [3, 4]
stopping for 3
removed 1 edges
component sizes= [3, 4]
stopping for 3
stopping for 4

any idea?

**Comment by shreeshbhat** [comment]
Got the same error. Your third todo must be specific to the previous graph.
You need to write a general method which will work for all graphs.

**Comment by Aceman1982** [comment]
Girvan newman needs to be generic. 

In particular check your minsize and maxsize parameters. If those two arguments are fine then the output should be fine. Also check the return from recursion. For example the below is my output after running the same,

Removed 1 edges
Components = [3, 4]
Removed 2 edges
Components = [2, 1]
Stopping for  2
Stopping for  1
Removed 2 edges
Components = [1, 3]
Stopping for  1
Removed 2 edges
Components = [2, 1]
Stopping for  2
Stopping for  1
Removed 1 edges
Components = [3, 4]
Removed 2 edges
Components = [2, 1]
Stopping for  2
Stopping for  1
Removed 2 edges
Components = [1, 3]
Stopping for  1
Removed 2 edges
Components = [2, 1]
Stopping for  2
Stopping for  1
Removed 1 edges
Components = [3, 4]
Stopping for  3
Removed 2 edges
Components = [1, 3]
Stopping for  3
Removed 1 edges
Components = [3, 4]
Stopping for  3
Stopping for  4

**Comment by jaydeeppatel1701** [comment]
i am getting same output as @ramyarao242
