### ISSUE TITLE
output file check

### ISSUE THREAD

**Issue by mamtakanvinde** [iit-cs579/main#77]
I am getting null value of score_clusters in the OUTPUT.txt file which is generated at the end.
Is it supposed to be like that?. Can any one check and tell me if they are also getting a null value for this variable or not.
Thanks

**Comment by bpraveen92** [comment]
No. I have exact cluster scores on it.

**Comment by dmartiinez** [comment]
Make sure you are returning the cluster list in the score_clusters method and not printing it.

**Comment by mamtakanvinde** [comment]
right, I had just printed it. thanks:)
