### ISSUE TITLE
ugly network

### ISSUE THREAD

**Issue by mamtakanvinde** [iit-cs579/main#78]
previously professor said.ugly graps may b due to outdated version of networkx library. 
I have installed latestt networkx library(1.10) still i get very ugly graphs.  does any one have the same problem.

**Comment by shreeshbhat** [comment]
Professor used 1.9.1 if I remember correctly.

**Comment by mamtakanvinde** [comment]
are you sure

**Comment by shreeshbhat** [comment]
That's the latest version. You can upgrade and check.

**Comment by mamtakanvinde** [comment]
1.10 is latest. i checked

**Comment by shreeshbhat** [comment]
https://networkx.github.io/documentation/latest/reference/news.html

**Comment by mamtakanvinde** [comment]
http://networkx.readthedocs.org/en/networkx-1.10/

**Comment by shreeshbhat** [comment]
hehe okay. Try 1.9.1 and see if it draws neat graphs :)

**Comment by aronwc** [comment]
Don't worry if the graphs aren't pretty.
(Of course, you're welcome to play with the graph drawing method to make it look nicer for your own benefit.)
