### ISSUE TITLE
Error while pushing the code

### ISSUE THREAD

**Issue by phirehal** [iit-cs579/main#81]
Hi, 
I'm unable to push my code to the repository. It says my working directory clean.Could someone help me wth this.

**Comment by mamtakanvinde** [comment]
first u need to add modified files then commit then push..

**Comment by aronwc** [comment]
@phirehal have you sorted this out? If you still have troubles, you can email me your solution as a last resort.

**Comment by phirehal** [comment]
I was able to sort it out and push my code.It was just a wrong directory I was refering to.
