### ISSUE TITLE
Question about midterm

### ISSUE THREAD

**Issue by ZhaoWang-IIT** [iit-cs579/main#83]
Which classroom to take the midterm?

Since many students registered for this class and I remember that many students even had no seat in the first beginning classes. Students may not show up in regular classes, but all students will show up in the midterm, so (1) Will everyone has a seat in this lecture classroom in the case that all students show up? (2) Is there enough space for students to seat away from each other? Because if students seat very closely, it is very easy to be cheated and plagiarized without notice and neighbors will affect each other.

**Comment by aronwc** [comment]
The test will be in the same place, same time as our normal class meetings.  Precautions will be taken.
