### ISSUE TITLE
Finding a partner for your project

### ISSUE THREAD

**Issue by aronwc** [iit-cs579/main#84]
Feel free to leave a note here to find students who are looking for project partners.

**Comment by jaydeeppatel1701** [comment]
If Anyone is still looking for project partner feel free this drop a reminder at jpatel98@hawk.iit.edu

**Comment by goutkannan** [comment]
Hi,

Is Anyone still looking for a teammate .? Please drop me an email
gkannan1@hawk.iit.edu / gout.kannan@gmail.  I have few ideas as well for
the project.

Thanks


Goutham
