### ISSUE TITLE
Understanding a Python Code from Lecture

### ISSUE THREAD

**Issue by shivankb** [iit-cs579/main#85]
While reviewing lecture 03 , i am stuck on a understanding of a code , i want to know how (1. * count/ len(G.nodes()) works.

![image](https://cloud.githubusercontent.com/assets/13937469/10450790/23d405ca-7162-11e5-830b-a41397bb7d1f.png)

**Comment by dougcirqueira** [comment]
What this code does is basically return a list of tuples (degree, p(k)),
for each degree (key) and count (value) returned by
degree_counts.iteritems(), which is a function that returns tuples (key,
value) from a dictionary or Counter,  that is this case.
Moreover, it computes the p(k) for each count returned before adding it as
the pair for each degree in the list of tuples, which is done in the step
1. * count / len(G.nodes()).

I hope this can help!
Best regards!
