### ISSUE TITLE
Understanding Lecture 05 step - Girvan-Newman

### ISSUE THREAD

**Issue by dougcirqueira** [iit-cs579/main#86]
Hi everyone,

I was reading through lecture 05 and I couldn't understand very well how does this transformation happens. It's about the Girvan-Newman Algorithm. I hope someone can help me on that.
Thank you for your consideration!

![issue](https://cloud.githubusercontent.com/assets/4992404/10463160/72169450-71a8-11e5-9075-f79ae44c894b.png)

**Comment by shreeshbhat** [comment]
The first diagram : After completing calculation for one node as source ( Node E ).
The second one  :  Final result after calculating for all nodes.

**Comment by jaydeeppatel1701** [comment]
or mathematically you can calculate betweenness for each edge

**Comment by goutkannan** [comment]
Hi,

What do you mean by "mathematically calculate" it ..? Did you mean,
manually find the shortest paths which passes through that particular edge
and compute the betwenness..?

**Comment by jaydeeppatel1701** [comment]
Professor has explained how to calculate betweenness of edge (B,D). You can compute for all the edges.don't need to create BFS for each node, calculate credit of each edge, add credit of each edge and then divide them by two

**Comment by dougcirqueira** [comment]
The thing is with the 4.5 value, for example. I still don't get it. I
understand from the first iteration of the algorithm, but I can't see how
we get it if we compute manually.

**Comment by goutkannan** [comment]
The node got 4.5 value because there are 2 shortest path with same number of nodes , For example the shortest path from  G - E is G - D - E and G - F - E.

**Comment by jaydeeppatel1701** [comment]
For Edge DG, {A,B,C,D} and {G} SO BETWEENNESS 4*1=4. For {E} to {G}, There are two shortest path. So it will be divided into 1/2.so 4+1/2=4.5

**Comment by aronwc** [comment]
Yes, we run Girvan Newman for each node as the source and sum together the final scores for each edge. Then, divide by two to get the final betweenness edge (since, e.g., we've considered both E and D as sources, we've counted the same edge twice). See the readings for more details.
https://github.com/iit-cs579/main/blob/master/read/lru-10.pdf

**Comment by dougcirqueira** [comment]
Thank you professor and all my awesome classmates! I got it :)!
