### ISSUE TITLE
Spam classification

### ISSUE THREAD

**Issue by ramyarao242** [iit-cs579/main#88]
Hi,

I am not able to understand how  the values have been assigned to matrix X
X = [(0,0),
       (1,0),
       (0,3),
      (1,3)]

For the given examples for spam and unspam sentences. Any help?

**Comment by aronwc** [comment]
This is a matrix:
```
X = [(0, 0),
     (1, 0),
     (0,3),
     (1,3)]
```
rows are documents, columns are feature counts. E.g.:

 . |money|free|
---|---------|----|
doc1| 0   | 0  |
doc2| 1   | 0  | 
doc3| 0   | 3  |
doc4| 1  | 3 |

This means that doc4 has one occurrence of the word money and one occurrence of the word free.
