### ISSUE TITLE
Is demographics now added to the portion for the midterm

### ISSUE THREAD

**Issue by shivakumar-15** [iit-cs579/main#89]
Prof ,you had sent a mail saying "Please review through lecture l13 for the midterm." Does this mean the lectures 12 and 13 are there for midterm or just to go through lecture video for the tips about exam.

**Comment by benjaminwalters** [comment]
Yes. Professor said on Blackboard to study up to lecture 13, which includes both demographic inference lectures.

**Comment by aronwc** [comment]
At minimum, please review sparse matrices from lec13.
