### ISSUE TITLE
Maximize number of tweets that can be collected on user timeline. Is there a way?

### ISSUE THREAD

**Issue by lkshmi** [iit-cs579/main#91]
Hi,

I am trying to collect all statuses/tweets from a user_timeline. Twitter documentation on statuses/user_timeline says the following:
This method can only return up to 3,200 of a user’s most recent Tweets. Native retweets of other statuses by the user is included in this total, regardless of whether include_rts is set to false when requesting this resource.
Twitter page for user in question shows 3800 tweets.So, I was under assumption that I will be able to collect 3200/3800 tweets. But when I ran my funcn, it collected only 3195 tweets and has tweets for only one week(The last one is dated 16th Oct). Looks like retweets etc.. have also been accounted as statuses.
Is there any way to maximize the number of statuses that can be collected? (Asking this question in-spite of knowing that Professor has repeatedly mentioned that it might not be possible to collect historical tweets)
Also, there are some tweets which looks as follows in my collected data but not found on twitter page of user. Any idea about these tweets?

Thanks in advance,
Regards,
Lakshmi Karle

{"contributors": null, "truncated": false, "text": "@xatyam Hey Satyam, we launched Lookup app to chat with local stores. We're sure it saves you time. Do try, pls http://t.co/HUtBkrKht1", "is_quote_status": false, "in_reply_to_status_id": null, "id": 541171781885636609, "favorite_count": 0, "entities": {"symbols": [], "user_mentions": [{"indices": [0, 7], "screen_name": "xatyam", "id": 97902728, "name": "Satyam Gambhir", "id_str": "97902728"}], "hashtags": [], "urls": [{"indices": [112, 134], "url": "http://t.co/HUtBkrKht1", "expanded_url": "http://goo.gl/QFPfu7", "display_url": "goo.gl/QFPfu7"}]}, "retweeted": false, "coordinates": null, "source": "<a href=\"http://twitter.com\" rel=\"nofollow\">Twitter Web Client</a>", "in_reply_to_screen_name": "xatyam", "id_str": "541171781885636609", "retweet_count": 0, "in_reply_to_user_id": 97902728, "favorited": false, "user": {"follow_request_sent": null, "has_extended_profile": false, "profile_use_background_image": true, "id": 2833968280, "verified": false, "profile_text_color": "333333", "profile_image_url_https": "https://pbs.twimg.com/profile_images/571309275952054272/Ot6rOEhF_normal.png", "profile_sidebar_fill_color": "F6FFD1", "entities": {"url": {"urls": [{"indices": [0, 22], "url": "http://t.co/OzflYydoNO", "expanded_url": "http://www.lookup.to", "display_url": "lookup.to"}]}, "description": {"urls": [{"indices": [51, 73], "url": "http://t.co/5eybIMX8AM", "expanded_url": "http://vimeo.com/113021720", "display_url": "vimeo.com/113021720"}, {"indices": [93, 115], "url": "http://t.co/OzflYydoNO", "expanded_url": "http://www.lookup.to", "display_url": "lookup.to"}]}}, "followers_count": 921, "protected": false, "location": "India", "default_profile_image": false, "id_str": "2833968280", "lang": "en", "utc_offset": -25200, "statuses_count": 3821, "description": "Get things done with a message! Check this video - http://t.co/5eybIMX8AM\nDownload #Lookup - http://t.co/OzflYydoNO", "friends_count": 404, "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme19/bg.gif", "profile_link_color": "0099CC", "profile_image_url": "http://pbs.twimg.com/profile_images/571309275952054272/Ot6rOEhF_normal.png", "following": null, "geo_enabled": true, "profile_background_color": "FFF04D", "profile_banner_url": "https://pbs.twimg.com/profile_banners/2833968280/1442400053", "profile_background_image_url": "http://abs.twimg.com/images/themes/theme19/bg.gif", "screen_name": "lookupHQ", "is_translation_enabled": false, "profile_background_tile": false, "favourites_count": 1223, "name": "Lookup", "notifications": null, "url": "http://t.co/OzflYydoNO", "created_at": "Thu Oct 16 12:05:35 +0000 2014", "contributors_enabled": false, "time_zone": "Pacific Time (US & Canada)", "profile_sidebar_border_color": "FFF8AD", "default_profile": false, "is_translator": false, "listed_count": 33}, "geo": null, "in_reply_to_user_id_str": "97902728", "possibly_sensitive": false, "lang": "en", "created_at": "Sat Dec 06 10:06:21 +0000 2014", "in_reply_to_status_id_str": null, "place": null}
{"contributors": null, "truncated": false, "text": "@xtremevicky Hey Vikrant, we launched Lookup app to chat with local stores. We're sure it saves you time. Do try, pls http://t.co/HUtBkrKht1", "is_quote_status": false, "in_reply_to_status_id": null, "id": 541171565606354944, "favorite_count": 0, "entities": {"symbols": [], "user_mentions": [{"indices": [0, 12], "screen_name": "xtremevicky", "id": 19648060, "name": "Vikrant Singh", "id_str": "19648060"}], "hashtags": [], "urls": [{"indices": [118, 140], "url": "http://t.co/HUtBkrKht1", "expanded_url": "http://goo.gl/QFPfu7", "display_url": "goo.gl/QFPfu7"}]}, "retweeted": false, "coordinates": null, "source": "<a href=\"http://twitter.com\" rel=\"nofollow\">Twitter Web Client</a>", "in_reply_to_screen_name": "xtremevicky", "id_str": "541171565606354944", "retweet_count": 0, "in_reply_to_user_id": 19648060, "favorited": false, "user": {"follow_request_sent": null, "has_extended_profile": false, "profile_use_background_image": true, "id": 2833968280, "verified": false, "profile_text_color": "333333", "profile_image_url_https": "https://pbs.twimg.com/profile_images/571309275952054272/Ot6rOEhF_normal.png", "profile_sidebar_fill_color": "F6FFD1", "entities": {"url": {"urls": [{"indices": [0, 22], "url": "http://t.co/OzflYydoNO", "expanded_url": "http://www.lookup.to", "display_url": "lookup.to"}]}, "description": {"urls": [{"indices": [51, 73], "url": "http://t.co/5eybIMX8AM", "expanded_url": "http://vimeo.com/113021720", "display_url": "vimeo.com/113021720"}, {"indices": [93, 115], "url": "http://t.co/OzflYydoNO", "expanded_url": "http://www.lookup.to", "display_url": "lookup.to"}]}}, "followers_count": 921, "protected": false, "location": "India", "default_profile_image": false, "id_str": "2833968280", "lang": "en", "utc_offset": -25200, "statuses_count": 3821, "description": "Get things done with a message! Check this video - http://t.co/5eybIMX8AM\nDownload #Lookup - http://t.co/OzflYydoNO", "friends_count": 404, "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme19/bg.gif", "profile_link_color": "0099CC", "profile_image_url": "http://pbs.twimg.com/profile_images/571309275952054272/Ot6rOEhF_normal.png", "following": null, "geo_enabled": true, "profile_background_color": "FFF04D", "profile_banner_url": "https://pbs.twimg.com/profile_banners/2833968280/1442400053", "profile_background_image_url": "http://abs.twimg.com/images/themes/theme19/bg.gif", "screen_name": "lookupHQ", "is_translation_enabled": false, "profile_background_tile": false, "favourites_count": 1223, "name": "Lookup", "notifications": null, "url": "http://t.co/OzflYydoNO", "created_at": "Thu Oct 16 12:05:35 +0000 2014", "contributors_enabled": false, "time_zone": "Pacific Time (US & Canada)", "profile_sidebar_border_color": "FFF8AD", "default_profile": false, "is_translator": false, "listed_count": 33}, "geo": null, "in_reply_to_user_id_str": "19648060", "possibly_sensitive": false, "lang": "en", "created_at": "Sat Dec 06 10:05:30 +0000 2014", "in_reply_to_status_id_str": null, "place": null}

**Comment by lkshmi** [comment]
Hi,

Just collected the data for other user timelines and noticed that I am finding tweets which are more than an year old in data collected. I am not sure what is so special about the first one that there are 3200 tweets/statuses posted in one week. I think they are using twitter a lot for promotion of their products.
But the second part is still not clear to me i.e. why there are so many tweets in the data I collected but not visible in the twitter page?

Regards,
Lakshmi

**Comment by aronwc** [comment]
Yes, some accounts will post 3200 tweets in a very short time period.

You have to keep scrolling on the Twitter page to get all the way down to
3200. The tweet you posted exists:
https://twitter.com/lookupHQ/status/541171781885636609

-Aron

**Comment by lkshmi** [comment]
Hello Sir,

Thank you.
Yes, the tweet is present. Didnt notice that this tweet is posted last year and was looking for this tweet among this year's tweet.

Regards,
Lakshmi Karle
