### ISSUE TITLE
find average of float numbers

### ISSUE THREAD

**Issue by jaydeeppatel1701** [iit-cs579/main#94]
If someone an help..

list = ['0.199999999999','0.199999999999',.......] 0.19999999999 n times in list, its type is string
i want to find an average, and my ans should be 0.199999999999

**Comment by aronwc** [comment]
float(x) will convert x to a float, but it sounds like list should be populated with floats in the first place.

**Comment by jaydeeppatel1701** [comment]
I already tried that one but I am getting error "float is not callable"  and I downloaded new module fastnumers, it is converting all strings to float but when I did average it is rounding off. In our case 0.2 so I am not getting same and as you mentioned in assignment

**Comment by aronwc** [comment]
Here's an example:
```python
>>> x = '0.199999999999'
>>> float(x)
0.199999999999
```

But, I think the bigger issue is that whatever you're doing to create the list in the first place, you should store floats in that list, not strings.
