### ISSUE TITLE
use regex for tokenize_with_not or some other way

### ISSUE THREAD

**Issue by jaydeeppatel1701** [iit-cs579/main#97]
Is there any regex available for tokenize_eith_not or we have to figure out some other way out?
because using "Some other way" i am getting output for this function as below
clf.coef_.shape
(1,4730)   instead of (1,4734)

**Comment by goutkannan** [comment]
To my knowledge in Regex , Look behind and Look ahead assertions can be
used for tokenize_with_not

**Comment by aronwc** [comment]
Try calling tokenize_with_punct, then modify its output.
